In [48]:
!nvidia-smi

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Fri Aug  8 16:43:52 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:DB:00.0 Off |                    0 |
| N/A   36C    P0            237W /  700W |   70535MiB /  81559MiB |     34%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     90785      C   ...fs2/bulatov/envs/rmt/bin/python3.11      66170MiB |
|    0   N/A  N/A     94058      C   ...06.nfs2/bulatov/envs/rmt/bin/python       3018MiB |
|    0   N/A  N/A     94550      C   ...06.nfs2/bulatov/envs/rmt/bin/python       1326MiB |
+-----------------------------------------------------------------------------------------+

In [49]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import os
import numpy as np
import datasets

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [78]:
model_name = "HuggingFaceTB/SmolLM2-135M"
model = AutoModelForCausalLM.from_pretrained(model_name, attn_implementation='eager')

In [79]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [ ]:
# text = 'I love cats'
texts =

In [81]:
inputs = tokenizer.batch_encode_plus([text], return_tensors='pt')

In [82]:
out = model(**inputs, output_attentions=True)

{'input_ids': tensor([[  57, 2606, 7680]]), 'attention_mask': tensor([[1, 1, 1]])}

In [101]:
out.keys()

odict_keys(['logits', 'past_key_values', 'attentions'])

In [86]:
attentions = out.attentions

In [88]:
len(model.model.layers)

30

In [87]:
len(attentions)

30

In [91]:
attentions[0].shape # b * n_heads * input_size * input_size

torch.Size([1, 9, 3, 3])

In [98]:
head_id_1 = 1
head_id_2 = 8

In [ ]:
num_samples = 100
final_similarity = np.mean([0.5, 0.9, 0.95, ..., 0.99]) # average by samples

In [ ]:
n_layers * (n_heads * n_heads)

tensor([[1.0000, 0.0000, 0.0000],
        [0.2747, 0.7253, 0.0000],
        [0.0871, 0.2810, 0.6319]], grad_fn=<SelectBackward0>)

In [ ]:
res_1 = attentions[0][0][head_id_1]
res_2 = attentions[0][0][head_id_2]

In [ ]:
n_layers

In [ ]:
mean()

In [ ]:
def sim(head_id_1, head_id_2):

In [ ]:
for id1 in range(9):
    for id2 in range(9):
        res.append(sim(id1, id2))

In [ ]:
sim(0, 3a
    )

In [100]:
res_1 - res_2

tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.1132,  0.1132,  0.0000],
        [-0.4013, -0.1817,  0.5830]], grad_fn=<SubBackward0>)

In [94]:
from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [95]:
pip install matplotlib

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting matplotlib
  Downloading matplotlib-3.10.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.59.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (107 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.2 kB)
Requirement already satisfied: numpy>=1.23 in /workspace-SR006.nfs2/bulatov/envs/rmt/lib/python3.11/site-packages (from matplotlib) (2.3.1)
Requirement already satisfied: packaging>=20.0 in /workspace-SR006.nfs2/bulatov/envs/rmt/lib/python3.11/site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in /workspace-SR006.nfs2/bulatov/envs/rmt/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /workspace-SR006.nfs2/bulatov/envs/rmt/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 32.6 MB/s eta 0:00:00a 0:00:01
Downloading contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (355 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.59.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 52.8 MB/s eta 0:00:00
Using cached kiwisolver-1.4.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
Using cached pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
Using cached pyparsing-3.2.3-py3-none-any.whl (111 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.59.0 kiwisolver-1.4.8 matplotlib-3.10.5 pillow-11.3.0 pyparsing-3.2.3
Note: you may need to restart the kernel to use updated packages.

In [57]:
w1 = model.model.layers[0].self_attn.q_proj.weight
w2 = model.model.layers[1].self_attn.q_proj.weight

tensor([[-0.0047,  0.0056, -0.0028,  ...,  0.1159,  0.1474,  0.0164],
        [ 0.0244,  0.1971,  0.0016,  ...,  0.0790,  0.1064, -0.0911],
        [ 0.0264,  0.0190, -0.0337,  ...,  0.1336,  0.1460, -0.0182],
        ...,
        [-0.0079,  0.0342, -0.1109,  ...,  0.0192,  0.0338, -0.0312],
        [-0.0259,  0.0154,  0.0518,  ...,  0.0804, -0.0475, -0.0343],
        [-0.0254, -0.0167, -0.1096,  ...,  0.0501, -0.0895, -0.0016]],
       grad_fn=<MulBackward0>)

In [3]:
import sys
sys.path.append('..')
from utils.reasoning import make_segment, split_cot
from torch.nn.utils.rnn import pad_sequence

In [4]:
from modeling_rmt.huggingface import RMTConfig, RMTForReasoning

In [5]:
checkpoint_path = "/workspace-SR006.nfs2/bulatov/rmt/runs/gsm8k/SmolLM2-135M/1x1024_mem32_1024_LR1e-04-cot_from_fineweb-ft-64x4-v3/checkpoint-28000/pytorch_model.bin"
mem_size = int(checkpoint_path.split('mem')[1].split('_')[0])

In [7]:
device = 'cuda'
# model_name = "gpt2"
model_name = "HuggingFaceTB/SmolLM2-135M"

tokenizer = AutoTokenizer.from_pretrained(model_name)

# bos = tokenizer.encode('////')
# think = tokenizer.encode('????')
# ans = tokenizer.encode('!!!!')
eos = [tokenizer.eos_token_id]
bos = [tokenizer.bos_token_id]
think = tokenizer.encode("<issue_start>")
ans = tokenizer.encode("<issue_closed>")

In [8]:
config = RMTConfig(num_mem_tokens=mem_size, 
                   think_token_id=think[0],
                   answer_token_id=ans[0],
                   bos_token_id=bos[0],
                   eos_token_id=eos[0]
                   )

rmt = RMTForReasoning(config=config)


# rmt.load_state_dict(torch.load(checkpoint_path + '/pytorch_model.bin'), strict=True)
rmt.load_state_dict(torch.load(checkpoint_path), strict=True)
# rmt.to(device)
print(':)')

Failed to load state, retrying with RMT loader.
Success!
:)

### Load dataset

In [9]:
class Holder:
    def __init__(self):
        pass
args = Holder()
# args.use_cot = False
args.num_mem_tokens = None
args.task_name = 'gsm8k'
# args.task_name = 'multiplication'

In [10]:
id_pad_value = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
bos = [tokenizer.bos_token_id]
think = tokenizer.encode("<issue_start>")
ans = tokenizer.encode("<issue_closed>")
eos = [tokenizer.eos_token_id]
if 'gsm8k' in args.task_name:
    delim = ">> <<"
elif 'multiplication' in args.task_name:
    delim = ' + '
else:
    raise NotImplementedError(f"Unknown task name {args.task_name}")

def collate_fn(batch):
    # first, we segment each sample into task, cot steps and labels
    segments_batch = []
    for sample in batch:
        task, lab, cot = sample['task'], sample['labels'], sample['cot']
        task_tokens = tokenizer.encode(task, add_special_tokens=False)
        labels_tokens = tokenizer.encode(lab, add_special_tokens=False)
        cot_segments = split_cot(cot, by=delim)
        cot_segment_tokens = tokenizer.batch_encode_plus(cot_segments, add_special_tokens=False)['input_ids']

        segments = []
        segments.append(make_segment(bos + task_tokens + think, loss=False))
        for segment in cot_segment_tokens[:-1]:
            segments.append(make_segment(bos + segment + think, loss=True))
        segments.append(make_segment(bos + cot_segment_tokens[-1] + ans, loss=True))

        segments.append(make_segment(bos + labels_tokens + eos, loss=True))
        segments_batch.append(segments)

    # if some samples have less segments than others, we pad them with empty segments
    num_segments = max(len(segments) for segments in segments_batch)
    for segments in segments_batch:
        if len(segments) < num_segments:
            segments.extend([make_segment(eos, loss=False)] * (num_segments - len(segments)))

    # prepare segments for the whole batch
    batch_segments = []
    for i in range(num_segments):
        input_ids = [s[i]['input_ids'] for s in segments_batch]
        attention_mask = [s[i]['attention_mask'] for s in segments_batch]
        labels = [s[i]['labels'] for s in segments_batch]
        labels_mask = [s[i]['labels_mask'] for s in segments_batch]

        input_ids = torch.flip(pad_sequence([torch.flip(x, dims=[0]) for x in input_ids], batch_first=True, padding_value=id_pad_value), dims=[1])
        attention_mask = torch.flip(pad_sequence([torch.flip(x, dims=[0]) for x in attention_mask], batch_first=True, padding_value=0), dims=[1])
        labels = torch.flip(pad_sequence([torch.flip(x, dims=[0]) for x in labels], batch_first=True, padding_value=-100), dims=[1])
        labels_mask = torch.flip(pad_sequence([torch.flip(x, dims=[0]) for x in labels_mask], batch_first=True, padding_value=False), dims=[1])

        batch_segment = {'input_ids': input_ids,
                            'attention_mask': attention_mask,
                            'labels_mask': labels_mask,
                            'labels': labels
                            }
        batch_segments.append(batch_segment)
    full_labels = torch.cat([s['labels'] for s in batch_segments], dim=1)
    return {"segments": batch_segments, 'labels': full_labels}

In [11]:
dataset = 'booydar/gsm8k'
# dataset = 'booydar/multiplication_4x4'
# dataset = f"booydar/{args.task_name}"
train_dataset = datasets.load_dataset(dataset, split='train')
valid_dataset = datasets.load_dataset(dataset, split='valid')

In [12]:
def generate(self, segments, **kwargs):
    memory_state = None

    for seg_num, segment in enumerate(segments):
        cell_out, memory_state = self.memory_cell(input_ids=segment['input_ids'],
                                                    attention_mask=segment['attention_mask'],
                                                    memory_state=memory_state, output_hidden_states=True)

    generated_segments = []
    for seg_num in range(len(segments), self.rmt_config.get("max_n_segments", 32)):
        output_ids, memory_state = generate_segment_(self, memory_state=memory_state, **kwargs)
        # if output_ids[0][-1] == 16993:
        #     output_ids = torch.cat(output_ids, torch.ones(1, 1) * 16993, dim=1)

        generated_segments.append(output_ids)

        if self.all_done(generated_segments):
            break

    return generated_segments

def generate_segment_(self, memory_state, **kwargs):
    input_ids = self.get_bos_tensor(memory_state)
    attention_mask = torch.ones_like(input_ids).bool()

    generated = self.memory_cell.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        memory_state=memory_state,
        stopping_criteria=self.make_custom_stopping_criteria(),
        **kwargs
    )

    # Update memory state from generation
    # fwd_inputs = torch.cat((input_ids, generated), dim=1)[:, :-1]
    # if generated[0][-1] == 16693:
    #     # print('appending ??')
    #     generated = torch.cat((generated, torch.tensor([[think[0]]]).to(device)), dim=1)

    fwd_inputs = torch.cat((input_ids, generated), dim=1)
    # self.seg_fwd_inputs.append(fwd_inputs)
    _, memory_state = self.memory_cell(input_ids=fwd_inputs, memory_state=memory_state)

    return generated, memory_state

### GRPO

In [13]:
import sys
sys.path.append("/workspace-SR006.nfs2/bulatov/rmt/reasoning")

In [14]:
from trl_rmt.trl.trainer.grpo_config import GRPOConfig
from trl_rmt.trl.trainer.grpo_trainer import GRPOTrainer

from datasets import load_dataset

In [15]:
dataset = load_dataset("trl-lib/tldr", split="train")

def reward_num_unique_chars(completions, **kwargs):
    return [len(set(c)) for c in completions]

In [16]:
model_name = "HuggingFaceTB/SmolLM2-135M-Instruct"
config = GRPOConfig(f"{model_name}-GRPO",
                    report_to='tensorboard',
                    per_device_train_batch_size=2,
                    per_device_eval_batch_size=2,
                    num_generations=2
                    )

trainer = GRPOTrainer(
    args=config,
    model=model_name,
    reward_funcs=reward_num_unique_chars,
    train_dataset=dataset,
    # data_collator=collate_fn,
)
trainer.train()

[2025-08-08 13:23:55,317] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /home/jovyan/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.

/workspace-SR006.nfs2/bulatov/envs/rmt/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/workspace-SR006.nfs2/bulatov/envs/rmt/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status

[2025-08-08 13:23:57,441] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False

ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided ['prompt', 'completion']

In [ ]:
dataset = load_dataset("trl-lib/tldr", split="train[:100]")  # smaller subset for testing

# Tokenizer
model_name = "HuggingFaceTB/SmolLM2-135M-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [ ]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="pt")

In [ ]:
dataset[0]

{'prompt': "SUBREDDIT: r/relationships\n\nTITLE: I (f/22) have to figure out if I want to still know these girls or not and would hate to sound insulting\n\nPOST: Not sure if this belongs here but it's worth a try. \n\nBackstory:\nWhen I (f/22) went through my first real breakup 2 years ago because he needed space after a year of dating roand  it effected me more than I thought. It was a horrible time in my life due to living with my mother and finally having the chance to cut her out of my life. I can admit because of it was an emotional wreck and this guy was stable and didn't know how to deal with me. We ended by him avoiding for a month or so after going to a festival with my friends. When I think back I wish he just ended. So after he ended it added my depression I suffered but my friends helped me through it and I got rid of everything from him along with cutting contact. \n\nNow: Its been almost 3 years now and I've gotten better after counselling and mild anti depressants. My mother has been out of my life since then so there's been alot of progress. Being stronger after learning some lessons there been more insight about that time of my life but when I see him or a picture everything comes back. The emotions and memories bring me back down. \n\nHis friends (both girls) are on my facebook because we get along well which is hard to find and I know they'll always have his back. But seeing him in a picture or talking to him at a convention having a conversation is tough. Crying confront of my current boyfriend is something I want to avoid. \n\nSo I've been thinking that I have to cut contact with these girls because it's time to move on because it's healthier. It's best to avoid him as well. But will they be insulted? Will they accept it? Is there going to be awkwardness? I'm not sure if it's the right to do and could use some outside opinions.\n\nTL;DR:",
 'completion': " I still have contact with an old ex's friends but can't stand to see or talk to him. His friends are really nice ,so how do I tell them I possibly want to unfriend them on Facebook because of him?"}

In [ ]:
from datasets import load_dataset
# from trl_rmt import GRPOTrainer

dataset = load_dataset("trl-lib/tldr", split="train")
# dataset = load_dataset("lmms-lab/multimodal-open-r1-8k-verified", split="train")

# Dummy reward function: count the number of unique characters in the completions
def reward_num_unique_chars(completions, **kwargs):
    return [len(set(c)) for c in completions]

In [45]:
model_name = "Qwen/Qwen2.5-0.5B-Instruct"
config = GRPOConfig(f"{model_name}-GRPO",
                    report_to='tensorboard',
                    per_device_train_batch_size=2,
                    per_device_eval_batch_size=2,
                    num_generations=2
                    )

In [ ]:
trainer = GRPOTrainer(
    args=config,
    model=model_name,
    reward_funcs=reward_num_unique_chars,
    train_dataset=dataset,
    # data_collator=collate_fn,
)
trainer.train()

In [ ]:
1/0

### V2

In [25]:
from trl_rmt.trl.trainer.grpo_config import GRPOConfig as RMTGRPOConfig
from trl_rmt.trl.trainer.grpo_trainer import GRPOTrainer as RMTGRPOTrainer

In [26]:
model_name = "HuggingFaceTB/SmolLM2-135M-Instruct"

In [27]:
def reward_num_unique_chars(completions, **kwargs):
    return [len(set(c)) for c in completions]

In [25]:
dataset[0]

{'prompt': "SUBREDDIT: r/relationships\n\nTITLE: I (f/22) have to figure out if I want to still know these girls or not and would hate to sound insulting\n\nPOST: Not sure if this belongs here but it's worth a try. \n\nBackstory:\nWhen I (f/22) went through my first real breakup 2 years ago because he needed space after a year of dating roand  it effected me more than I thought. It was a horrible time in my life due to living with my mother and finally having the chance to cut her out of my life. I can admit because of it was an emotional wreck and this guy was stable and didn't know how to deal with me. We ended by him avoiding for a month or so after going to a festival with my friends. When I think back I wish he just ended. So after he ended it added my depression I suffered but my friends helped me through it and I got rid of everything from him along with cutting contact. \n\nNow: Its been almost 3 years now and I've gotten better after counselling and mild anti depressants. My mother has been out of my life since then so there's been alot of progress. Being stronger after learning some lessons there been more insight about that time of my life but when I see him or a picture everything comes back. The emotions and memories bring me back down. \n\nHis friends (both girls) are on my facebook because we get along well which is hard to find and I know they'll always have his back. But seeing him in a picture or talking to him at a convention having a conversation is tough. Crying confront of my current boyfriend is something I want to avoid. \n\nSo I've been thinking that I have to cut contact with these girls because it's time to move on because it's healthier. It's best to avoid him as well. But will they be insulted? Will they accept it? Is there going to be awkwardness? I'm not sure if it's the right to do and could use some outside opinions.\n\nTL;DR:",
 'completion': " I still have contact with an old ex's friends but can't stand to see or talk to him. His friends are really nice ,so how do I tell them I possibly want to unfriend them on Facebook because of him?"}

In [26]:
import re
def reward_func(completions, ground_truth, **kwargs):
    # Regular expression to capture content inside \boxed{}
    matches = [re.search(r"\\boxed\{(.*?)\}", completion) for completion in completions]
    contents = [match.group(1) if match else "" for match in matches]
    # Reward 1 if the content is the same as the ground truth, 0 otherwise
    return [1.0 if c == gt else 0.0 for c, gt in zip(contents, ground_truth)]

In [27]:

dataset_gt = dataset.map(lambda x: {**x, 'ground_truth': x['completion']})

Map: 100%|██████████| 116722/116722 [00:06<00:00, 18480.58 examples/s]

In [29]:
# model = AutoModelForCausalLM.from_pretrained(model_name)
# tokenizer = AutoTokenizer.from_pretrained(model_name)

# reward_funcs = [reward_num_unique_chars]
# dataset = load_dataset("trl-lib/tldr", split="train[:100]")

In [ ]:
# from modeling_rmt.huggingface import *
# class RMTConfig(PretrainedConfig):
#     model_type = "rmt"

#     def __init__(self,
#                  base_model_name="HuggingFaceTB/SmolLM2-135M",
#                  num_mem_tokens=16,
#                  max_n_segments=10,
#                  think_token_id=None,
#                  answer_token_id=None,
#                  bos_token_id=None,
#                  eos_token_id=None,
#                  **kwargs):
#         super().__init__(**kwargs)
#         self.base_model_name = base_model_name
#         self.num_mem_tokens = num_mem_tokens
#         self.max_n_segments = max_n_segments
#         self.think_token_id = think_token_id
#         self.answer_token_id = answer_token_id
#         self.bos_token_id = bos_token_id
#         self.eos_token_id = eos_token_id
#         self.memory_cell_cls = "MemoryCell"
#         self.recurrent_wrapper_cls = "RecurrentWrapperNoSegmentationGenerate"

#     def get(self, attr: str, default=None):
#         if hasattr(self, attr):
#             return getattr(self, attr)
#         else:
#             return default


# class RMTForReasoning(PreTrainedModel):
#     config_class = RMTConfig

#     def __init__(self, config: RMTConfig, **kwargs):
#         super().__init__(config, **kwargs)
#         from transformers import AutoConfig, AutoModelForCausalLM
#         base_config = AutoConfig.from_pretrained(config.base_model_name)
#         base_model = AutoModelForCausalLM.from_config(base_config)

#         self.rmt_config = config
#         memory_cell = MemoryCell(base_model, num_mem_tokens=config.num_mem_tokens)
#         self.rmt = RecurrentWrapperNoSegmentationGenerate(
#             memory_cell,
#             max_n_segments=config.max_n_segments,
#             think_token_id=config.think_token_id,
#             answer_token_id=config.answer_token_id,
#             bos_token_id=config.bos_token_id,
#             eos_token_id=config.eos_token_id
#         )

#     def forward(self, *args, **kwargs):
#         return self.rmt(*args, **kwargs)

#     def generate(self, *args, **kwargs):
#         self.last_state = {'args': args, "kwargs": kwargs}
#         if 'segments' in kwargs:
#             return self.rmt.generate(*args, **kwargs)
#         else:
#             segment = {"input_ids": kwargs.pop("input_ids"),
#                        "attention_mask": kwargs.pop("attention_mask")}
#             max_new_tokens = kwargs['generation_config'].max_new_tokens
#             gen_outputs = self.rmt.generate(segments=[segment], max_new_tokens=max_new_tokens)
#             self.last_gen_outputs = gen_outputs
#             return torch.cat(gen_outputs, dim=1)

#     def load_state_dict(self, state_dict, strict=True, assign=False):
#         try:
#             return super().load_state_dict(state_dict, strict, assign)
#         except RuntimeError:
#             print("Failed to load state, retrying with RMT loader.")
#             self.rmt.load_state_dict(state_dict, strict=True, assign=assign)
#             print("Success!")

#     @classmethod
#     def from_pretrained(cls, pretrained_model_name_or_path, config=None, *args, **kwargs):
#         from transformers.utils.hub import cached_file, HfHubHTTPError
#         import torch

#         if config is None:
#             config = RMTConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)

#         model = cls(config)

#         state_dict = None
#         try:
#             weights_path = cached_file(pretrained_model_name_or_path, "model.safetensors", **kwargs)
#             from safetensors.torch import load_file
#             state_dict = load_file(weights_path, device="cpu")
#         except (OSError, HfHubHTTPError):
#             try:
#                 weights_path = cached_file(pretrained_model_name_or_path, "pytorch_model.bin", **kwargs)
#                 state_dict = torch.load(weights_path, map_location="cpu")
#             except (OSError, HfHubHTTPError):
#                 print(f"Warning: Could not find weights for {pretrained_model_name_or_path}. "
#                       f"The model is initialized randomly.")

#         if state_dict is not None:
#             model.load_state_dict(state_dict, strict=False)

#         return model

In [30]:
def gsm_to_grpo(sample):
    return {"prompt": sample['task'],
            "ground_truth": sample['labels']}

train_grpo_dataset = train_dataset.map(gsm_to_grpo).remove_columns(["task", "cot", "cot_len", "labels"])
valid_grpo_dataset = valid_dataset.map(gsm_to_grpo).remove_columns(["task", "cot", "cot_len", "labels"])

In [31]:
train_grpo_dataset[0]

{'prompt': 'Jen shared a pack of chocolates among her friends. She gave 20% to Lucy, 30% to Sarah and the remaining were shared equally among four others. If the pack contained 100 chocolates, how many chocolates were each of the four others getting?',
 'ground_truth': '12.5'}

In [32]:
bos[0]

0

In [33]:
config = RMTConfig(num_mem_tokens=mem_size, 
                   think_token_id=think[0],
                   answer_token_id=ans[0],
                   bos_token_id=bos[0],
                   eos_token_id=eos[0]
                   )

rmt = RMTForReasoning(config=config)

In [35]:

training_args = GRPOConfig(f"{model_name}-GRPO",
                    report_to='tensorboard',
                    per_device_train_batch_size=2,
                    per_device_eval_batch_size=2,
                    num_generations=2,
                    logging_steps=1
                    )

trainer = GRPOTrainer(
    # model=model,
    model=rmt,
    reward_funcs=[reward_num_unique_chars, reward_func],
    args=training_args,
    train_dataset=dataset_gt,
    eval_dataset=dataset_gt,
    processing_class=tokenizer,
    # peft_config=get_peft_config(model_args),
)

In [46]:

training_args = GRPOConfig(f"{model_name}-GRPO",
                    report_to='tensorboard',
                    per_device_train_batch_size=2,
                    per_device_eval_batch_size=2,
                    num_generations=2,
                    logging_steps=1
                    )

trainer = GRPOTrainer(
    model=model,
    # model=rmt,
    reward_funcs=[reward_num_unique_chars, reward_func],
    args=training_args,
    train_dataset=train_grpo_dataset,
    eval_dataset=valid_grpo_dataset,
    processing_class=tokenizer,
    # peft_config=get_peft_config(model_args),
)

In [47]:
trainer.train()

ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided ['prompt', 'ground_truth']

In [97]:
rmt.last_state['kwargs']['generation_config'].max_new_tokens

256

### Refactor RMT for adaptive segmentation

In [37]:
id_pad_value = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
bos = [tokenizer.bos_token_id]
think = tokenizer.encode("<issue_start>")
ans = tokenizer.encode("<issue_closed>")
eos = [tokenizer.eos_token_id]
if 'gsm8k' in args.task_name:
    delim = ">> <<"
elif 'multiplication' in args.task_name:
    delim = ' + '
else:
    raise NotImplementedError(f"Unknown task name {args.task_name}")

def collate_fn(batch):
    input_ids = []
    labels_masks = []
    attention_masks = []
    for sample in batch:
        task, lab, cot = sample['task'], sample['labels'], sample['cot']
        task_tokens = tokenizer.encode(task, add_special_tokens=False)
        labels_tokens = tokenizer.encode(lab, add_special_tokens=False)
        cot_segments = split_cot(cot, by=delim)
        cot_segment_tokens = tokenizer.batch_encode_plus(cot_segments, add_special_tokens=False)['input_ids']

        segments = []
        segments += bos + task_tokens + think
        for segment in cot_segment_tokens[:-1]:
            segments += bos + segment + think
        segments += bos + cot_segment_tokens[-1] + ans
        segments += bos + labels_tokens + eos

        segments = torch.tensor(segments)

        labels_mask = torch.ones_like(segments)
        labels_mask[:len(bos + task_tokens + think)] = 0
        attention_mask = torch.ones_like(segments)

        input_ids.append(segments)
        # labels_masks.append(labels_mask)
        attention_masks.append(attention_mask)


    input_ids = pad_sequence(input_ids, batch_first=True, padding_value=id_pad_value)
    attention_mask = pad_sequence(attention_masks, batch_first=True, padding_value=0)
    labels = pad_sequence(input_ids, batch_first=True, padding_value=-100)
    # labels_mask = pad_sequence(labels_masks, batch_first=True, padding_value=False)
    return {'input_ids': input_ids,
            'attention_mask': attention_mask,
            # 'labels_mask': labels_mask,
            'labels': labels
            }

In [38]:
batch = [train_dataset[i] for i in range(4)]
collated = collate_fn(batch)

In [39]:
import torch

def split_by_bos(input_ids: torch.Tensor, bos_id: int, pad_id: int = 0):
    batch_segments = []

    for sample in input_ids:
        # Convert to list and remove padding
        tokens = [tok.item() for tok in sample if tok != pad_id]

        # Find all BOS indices
        bos_indices = [i for i, tok in enumerate(tokens) if tok == bos_id]

        # If no BOS token, treat the whole as one segment
        if not bos_indices:
            batch_segments.append([tokens])
            continue

        # Append a virtual end index to cover last segment
        bos_indices.append(len(tokens))

        # Split into segments between BOS tokens
        segments = []
        for i in range(len(bos_indices) - 1):
            start = bos_indices[i]
            end = bos_indices[i + 1]
            segments.append(tokens[start:end])

        batch_segments.append(segments)

    return batch_segments


def pad_and_segment(self, input_ids):
    bos_id = self.rmt_config.bos_token_id
    pad_id = self.rmt_config.pad_token_id
    mem_size = self.rmt_config.num_mem_tokens
    mem_template = [self.rmt_config.mem_id] * mem_size
    
    segments_batch = split_by_bos(input_ids, bos_id, pad_id)
    segments_batch = [[torch.tensor(mem_template + seg + mem_template) for seg in sample_segments] for sample_segments in segments_batch]

    # if some samples have less segments than others, we extend them with empty segments
    max_segments = max(len(segments) for segments in segments_batch)
    for segments in segments_batch:
        if len(segments) < max_segments:
            segments += [torch.tensor(eos)] * (max_segments - len(segments))

    batch_segments = [[seg[seg_num] for seg in segments_batch] for seg_num in range(max_segments)]

    labels_masks = [[torch.ones_like(samp) for samp in segment] for segment in batch_segments]
    attention_masks = [[torch.ones_like(samp) for samp in segment] for segment in batch_segments]

    read_memory_masks = [[torch.zeros_like(samp) for samp in segment] for segment in batch_segments]
    write_memory_masks = [[torch.zeros_like(samp) for samp in segment] for segment in batch_segments]

    input_segments = []
    for seg_num in range(max_segments):
        for bn, sample in enumerate(batch_segments[seg_num]):
            if seg_num == 0:
                labels_masks[seg_num][bn] *= 0
            read_memory_masks[seg_num][bn][:mem_size] = 1
            write_memory_masks[seg_num][bn][-mem_size:] = 1
            labels_masks[seg_num][bn][:mem_size] = 0
            labels_masks[seg_num][bn][-mem_size:] = 0

        segment = {"input_ids": pad_sequence(batch_segments[seg_num], batch_first=True, padding_value=id_pad_value),
                   "attention_mask": pad_sequence(attention_masks[seg_num], batch_first=True, padding_value=0),
                   "labels": pad_sequence(batch_segments[seg_num], batch_first=True, padding_value=-100),
                   "labels_mask": pad_sequence(labels_masks[seg_num], batch_first=True, padding_value=0),
                   "read_memory_mask": pad_sequence(read_memory_masks[seg_num], batch_first=True, padding_value=0),
                   "write_memory_mask": pad_sequence(write_memory_masks[seg_num], batch_first=True, padding_value=0)
                   }
        input_segments.append(segment)
    return input_segments

In [40]:
self = rmt
self.rmt_config.num_mem_tokens = 4
self.rmt_config.mem_id = 0

In [44]:
input_segments = pad_and_segment(rmt, collated['input_ids'])
segment = input_segments[0]

In [45]:
segment

{'input_ids': tensor([[    0,     0,     0,     0,     1,    58,   264,  3600,   253,  3123,
            282, 47466,  1486,   874,  2428,    30,  2306,  4502,   216,    34,
             32,    21,   288, 19388,    28,   216,    35,    32,    21,   288,
           8165,   284,   260,  6219,   592,  3600,  7582,  1486,  1876,  1449,
             30,  1094,   260,  3123,  7439,   216,    33,    32,    32, 47466,
             28,   638,   800, 47466,   592,   971,   282,   260,  1876,  1449,
           2967,    47,     8,     1,    34,    32,    27,    35,    32,    45,
             37,    32,     8,     1,    33,    32,    32,    29,    37,    32,
             45,    37,    32,     8,     1,    33,    32,    32,    26,    37,
             32,    31,    33,    32,    32,    45,    37,    32,     8,     1,
             37,    32,    31,    36,    45,    33,    34,    30,    37,    10,
              1,    33,    34,    30,    37,     2,     2,     2,     2,     2,
              2,     0,     0,     0,     0],
         [    0,     0,     0,     0,     1,    49, 46782,  1135,   253,  4354,
          19039,   338,  7439,   216,    37,   896,  5574,    30,   378, 19039,
           7439,   216,    34,    32, 13855,    28,  6757,   347,   800, 26445,
            347, 13855,    28,   216,    33,    37,  1711,   347,   800, 18214,
            347, 26445,    28,   284,  6757,   347,   800, 27068,   347, 18214,
             30,  1073,   800,  5574,   359,   281,  2719,   281,   260, 19039,
             47,     8,     1,    34,    26,    34,    32,    45,    36,    32,
              8,     1,    33,    37,    26,    36,    32,    45,    38,    32,
             32,     8,     1,    34,    26,    38,    32,    32,    45,    33,
             34,    32,    32,     8,     1,    34,    32,    27,    36,    32,
             27,    38,    32,    32,    27,    33,    34,    32,    32,    45,
             33,    40,    38,    32,    10,     1,    33,    40,    38,    32,
              2,     0,     0,     0,     0],
         [    0,     0,     0,     0,     1,  4518,  2164,   284, 20391,   359,
           2194,  4903,  4288,   735,    30, 20391,   506, 13592,  2933,  6757,
            347,   986,   347, 44716,   506,   288,  1235,    30, 14964,    28,
            617,   314,  7956,    28, 21768,  1296,  1711,   347,   986,   915,
          10654,   347,   357,  2933, 44716,   288,  1235,   874, 13592,    30,
           1094,   281,  2719,    28,   502,  5344,   216,    35,    38,  2737,
             28,   638,   800,  2737,  1072, 44716,  5344,   335,  2194,   874,
           4903, 28091,    47,     8,     1,    38,    45,    38,    10,     1,
             38,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     0,     0,     0,     0],
         [    0,     0,     0,     0,     1,  3528,   105, 11287,   253, 11697,
          14260,   282,  1885,    40,    32,    32,   564,   384,   553,   288,
           2290,   253,  3024,   282,   216,    39,  8006,  1073,  1083,   314,
            650,  1925, 14260,    47,     8,     1,    40,    32,    32,    26,
             39,    31,    33,    32,    32,    45,    37,    38,     8,     1,
             40,    32,    32,    29,    37,    38,    45,    39,    36,    36,
             10,     1,    39,    36,    36,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     0,     0,     0,     0]]),
 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1]]),
 'labels': tensor([[    0,     0,     0,     0,     1,    58,   264,  3600,   253,  3123,
            282, 47466,  1486,   874,  2428,    30,  2306,  4502,   216,    34,
             32,    21,   288, 19388,    28,   216,    35,    32,    21,   288,
           8165,   284,   260,  6219,   592,  3600,  7582,  1486,  1876,  1449,
             30,  1094,   260,  3123,  7439,   216,    33,    32,    32, 47466,
             28,   638,   800, 47466,   592,   971,   282,   260,  1876,  1449,
           2967,    47,     8,     1,    34,    32,    27,    35,    32,    45,
             37,    32,     8,     1,    33,    32,    32,    29,    37,    32,
             45,    37,    32,     8,     1,    33,    32,    32,    26,    37,
             32,    31,    33,    32,    32,    45,    37,    32,     8,     1,
             37,    32,    31,    36,    45,    33,    34,    30,    37,    10,
              1,    33,    34,    30,    37,     2,     2,     2,     2,     2,
              2,     0,     0,     0,     0],
         [    0,     0,     0,     0,     1,    49, 46782,  1135,   253,  4354,
          19039,   338,  7439,   216,    37,   896,  5574,    30,   378, 19039,
           7439,   216,    34,    32, 13855,    28,  6757,   347,   800, 26445,
            347, 13855,    28,   216,    33,    37,  1711,   347,   800, 18214,
            347, 26445,    28,   284,  6757,   347,   800, 27068,   347, 18214,
             30,  1073,   800,  5574,   359,   281,  2719,   281,   260, 19039,
             47,     8,     1,    34,    26,    34,    32,    45,    36,    32,
              8,     1,    33,    37,    26,    36,    32,    45,    38,    32,
             32,     8,     1,    34,    26,    38,    32,    32,    45,    33,
             34,    32,    32,     8,     1,    34,    32,    27,    36,    32,
             27,    38,    32,    32,    27,    33,    34,    32,    32,    45,
             33,    40,    38,    32,    10,     1,    33,    40,    38,    32,
              2,     0,     0,     0,     0],
         [    0,     0,     0,     0,     1,  4518,  2164,   284, 20391,   359,
           2194,  4903,  4288,   735,    30, 20391,   506, 13592,  2933,  6757,
            347,   986,   347, 44716,   506,   288,  1235,    30, 14964,    28,
            617,   314,  7956,    28, 21768,  1296,  1711,   347,   986,   915,
          10654,   347,   357,  2933, 44716,   288,  1235,   874, 13592,    30,
           1094,   281,  2719,    28,   502,  5344,   216,    35,    38,  2737,
             28,   638,   800,  2737,  1072, 44716,  5344,   335,  2194,   874,
           4903, 28091,    47,     8,     1,    38,    45,    38,    10,     1,
             38,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     0,     0,     0,     0],
         [    0,     0,     0,     0,     1,  3528,   105, 11287,   253, 11697,
          14260,   282,  1885,    40,    32,    32,   564,   384,   553,   288,
           2290,   253,  3024,   282,   216,    39,  8006,  1073,  1083,   314,
            650,  1925, 14260,    47,     8,     1,    40,    32,    32,    26,
             39,    31,    33,    32,    32,    45,    37,    38,     8,     1,
             40,    32,    32,    29,    37,    38,    45,    39,    36,    36,
             10,     1,    39,    36,    36,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     0,     0,     0,     0]]),
 'labels_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0]]),
 'read_memory_mask': tensor([[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0]]),
 'write_memory_mask': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 1, 1, 1, 1]])}

In [301]:
tokenizer.batch_decode(segment['input_ids'])

['<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|im_start|>100-50=50<issue_start><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|>',
 '<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|im_start|>15*40=600<issue_start><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|>',
 '<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|im_start|>6<|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|im_start|>800-56=744<issue_closed><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|>']

In [307]:
for s, m in zip(segment['input_ids'], segment['labels_mask']):
    # print(tokenizer.decode(s[m]))
    # print(s[m])
    print(m)

tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0])
tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [303]:
for s, m in zip(segment['input_ids'], segment['attention_mask']):
    # print(tokenizer.decode(s[m]))
    print(m)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [304]:
for s, m in zip(segment['input_ids'], segment['read_memory_mask']):
    # print(tokenizer.decode(s[m]))
    print(m)

tensor([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [305]:
for s, m in zip(segment['input_ids'], segment['write_memory_mask']):
    # print(tokenizer.decode(s[m]))
    print(m)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

### Adapt RMT code

In [ ]:
def split_by_bos(input_ids: torch.Tensor, bos_id: int, pad_id: int = 0):
    batch_segments = []

    for sample in input_ids:
        # Convert to list and remove padding
        tokens = [tok.item() for tok in sample if tok != pad_id]

        # Find all BOS indices
        bos_indices = [i for i, tok in enumerate(tokens) if tok == bos_id]

        # If no BOS token, treat the whole as one segment
        if not bos_indices:
            batch_segments.append([tokens])
            continue

        # Append a virtual end index to cover last segment
        bos_indices.append(len(tokens))

        # Split into segments between BOS tokens
        segments = []
        for i in range(len(bos_indices) - 1):
            start = bos_indices[i]
            end = bos_indices[i + 1]
            segments.append(tokens[start:end])

        batch_segments.append(segments)

    return batch_segments


import math
import torch
from torch.nn import CrossEntropyLoss

from transformers import StoppingCriteria
from transformers import PreTrainedModel, PretrainedConfig
from transformers.modeling_outputs import CausalLMOutputWithCrossAttentions


class RMTConfig(PretrainedConfig):
    model_type = "rmt"

    def __init__(self,
                 base_model_name="HuggingFaceTB/SmolLM2-135M",
                 num_mem_tokens=16,
                 max_n_segments=10,
                 think_token_id=None,
                 answer_token_id=None,
                 bos_token_id=None,
                 eos_token_id=None,
                 **kwargs):
        super().__init__(**kwargs)
        self.base_model_name = base_model_name
        self.num_mem_tokens = num_mem_tokens
        self.max_n_segments = max_n_segments
        self.think_token_id = think_token_id
        self.answer_token_id = answer_token_id
        self.bos_token_id = bos_token_id
        self.eos_token_id = eos_token_id
        self.memory_cell_cls = "MemoryCell"
        self.recurrent_wrapper_cls = "RecurrentWrapperNoSegmentationGenerate"

    def get(self, attr: str, default=None):
        if hasattr(self, attr):
            return getattr(self, attr)
        else:
            return default


class RMTForReasoning(PreTrainedModel):
    config_class = RMTConfig

    def __init__(self, config: RMTConfig, **kwargs):
        super().__init__(config, **kwargs)
        from transformers import AutoConfig, AutoModelForCausalLM
        base_config = AutoConfig.from_pretrained(config.base_model_name)
        base_model = AutoModelForCausalLM.from_config(base_config)

        self.rmt_config = config
        memory_cell = MemoryCell(base_model, num_mem_tokens=config.num_mem_tokens)
        self.rmt = RecurrentWrapperNoSegmentationGenerate(
            memory_cell,
            max_n_segments=config.max_n_segments,
            think_token_id=config.think_token_id,
            answer_token_id=config.answer_token_id,
            bos_token_id=config.bos_token_id,
            eos_token_id=config.eos_token_id
        )

    def forward(self, *args, **kwargs):
        return self.rmt(*args, **kwargs)

    def generate(self, *args, **kwargs):
        return self.rmt.generate(*args, **kwargs)

    def load_state_dict(self, state_dict, strict=True, assign=False):
        try:
            return super().load_state_dict(state_dict, strict, assign)
        except RuntimeError:
            print("Failed to load state, retrying with RMT loader.")
            self.rmt.load_state_dict(state_dict, strict=True, assign=assign)
            print("Success!")

    @classmethod
    def from_pretrained(cls, pretrained_model_name_or_path, config=None, *args, **kwargs):
        from transformers.utils.hub import cached_file, HfHubHTTPError
        import torch

        if config is None:
            config = RMTConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)

        model = cls(config)

        state_dict = None
        try:
            weights_path = cached_file(pretrained_model_name_or_path, "model.safetensors", **kwargs)
            from safetensors.torch import load_file
            state_dict = load_file(weights_path, device="cpu")
        except (OSError, HfHubHTTPError):
            try:
                weights_path = cached_file(pretrained_model_name_or_path, "pytorch_model.bin", **kwargs)
                state_dict = torch.load(weights_path, map_location="cpu")
            except (OSError, HfHubHTTPError):
                print(f"Warning: Could not find weights for {pretrained_model_name_or_path}. "
                      f"The model is initialized randomly.")

        if state_dict is not None:
            model.load_state_dict(state_dict, strict=False)

        return model


class MemoryCell(torch.nn.Module):
    def __init__(self, base_model, num_mem_tokens):
        super().__init__()
        self.model = base_model
        self.create_memory(num_mem_tokens)

    def create_memory(self, num_mem_tokens):
        self.num_mem_tokens = num_mem_tokens
        embeddings = self.model.get_input_embeddings()
        memory_dim = getattr(self.model.config, 'n_embd', self.model.config.hidden_size)
        memory_weights = torch.randn((num_mem_tokens, memory_dim)) * embeddings.weight.data.std()
        self.register_parameter('memory', torch.nn.Parameter(memory_weights, requires_grad=True))

        self.read_memory_position = range(num_mem_tokens)
        self.write_memory_position = range(-num_mem_tokens, 0)

    def set_memory(self, input_shape):
        memory = self.memory.repeat(input_shape[0], 1, 1)
        return memory

    def forward(self, input_ids, memory_state=None, **kwargs):
        if memory_state is None:
            memory_state = self.set_memory(input_ids.shape)

        seg_kwargs = self.process_input(input_ids, memory_state, write_mem=True, **kwargs)
        out = self.model(**seg_kwargs)
        out, new_memory_state = self.process_output(out, **kwargs)

        return out, new_memory_state

    def generate(self, input_ids, memory_state, attention_mask=None, **generate_kwargs):
        if memory_state is None:
            memory_state = self.set_memory(input_ids.shape)

        seg_kwargs = self.process_input(input_ids, memory_state, attention_mask=attention_mask, write_mem=False)
        out = self.model.generate(inputs_embeds=seg_kwargs['inputs_embeds'],
                                  attention_mask=seg_kwargs['attention_mask'],
                                  **generate_kwargs)
        return out

    def process_input(self, input_ids, memory_state, write_mem, **kwargs):
        seg_kwargs = dict(**kwargs)

        inputs_embeds = kwargs.get('inputs_embeds')
        if inputs_embeds is None:
            inputs_embeds = self.model.get_input_embeddings()(input_ids)

        if self.num_mem_tokens > 0:
            if write_mem:
                inputs_embeds = torch.cat([memory_state, inputs_embeds, memory_state], dim=1)
            else:
                inputs_embeds = torch.cat([memory_state, inputs_embeds], dim=1)

        seg_kwargs['input_ids'] = None
        seg_kwargs['inputs_embeds'] = inputs_embeds
        if kwargs.get('attention_mask') is not None:
            seg_kwargs['attention_mask'] = self.pad_attention_mask(kwargs['attention_mask'], inputs_embeds.shape)
        seg_kwargs['output_hidden_states'] = True
        return seg_kwargs

    def pad_attention_mask(self, attention_mask, shape):
        if self.num_mem_tokens in {0, None}:
            return attention_mask
        else:
            mask = torch.ones(*shape[:2], dtype=torch.int64).to(attention_mask.device)
            mask[:, self.num_mem_tokens: self.num_mem_tokens + attention_mask.shape[1]] = attention_mask
            return mask

    def process_output(self, model_outputs, **kwargs):
        if self.num_mem_tokens not in {0, None}:
            out = CausalLMOutputWithCrossAttentions()
            memory_state = model_outputs.hidden_states[-1][:, -self.num_mem_tokens:]
            out['logits'] = model_outputs.logits[:, self.num_mem_tokens:-self.num_mem_tokens]

            if kwargs.get('output_hidden_states'):
                out['hidden_states'] = [lh[:, self.num_mem_tokens:-self.num_mem_tokens]
                                        for lh in model_outputs.hidden_states]
            if kwargs.get('output_attentions'):
                out['attentions'] = model_outputs['attentions']
        else:
            memory_state = None
            out = model_outputs

        return out, memory_state



class ReasoningRecurrentWrapper(torch.nn.Module):
    def __init__(self, memory_cell, **rmt_kwargs):
        super().__init__()
        self.memory_cell = memory_cell
        self.rmt_config = rmt_kwargs
    
    def forward(self, input_ids, labels, output_attentions=None, output_hidden_states=None):
        memory_state = None

        segments = self.pad_and_segment(input_ids)

        cell_outputs = []
        for seg_num, segment in enumerate(segments):
            cell_out, memory_state = self.memory_cell(input_ids=segment['input_ids'],
                                                      attention_mask=segment['attention_mask'],
                                                      memory_state=memory_state, output_hidden_states=True)
            cell_outputs.append(cell_out)
            self.manage_gradients(memory_state, seg_num)

        out = self.process_outputs(cell_outputs, segments,
                                   output_attentions=output_attentions,
                                   output_hidden_states=output_hidden_states)
        return out

    def generate(self, segments, **kwargs):
        memory_state = None

        for seg_num, segment in enumerate(segments):
            cell_out, memory_state = self.memory_cell(input_ids=segment['input_ids'],
                                                      attention_mask=segment['attention_mask'],
                                                      memory_state=memory_state, output_hidden_states=True)

        generated_segments = []
        for seg_num in range(len(segments), self.rmt_config.get("max_n_segments", 32)):
            output_ids, memory_state = self.generate_segment(memory_state=memory_state, **kwargs)
            generated_segments.append(output_ids)

            if self.all_done(generated_segments):
                break

        return generated_segments

    def generate_segment(self, memory_state, **kwargs):
        input_ids = self.get_bos_tensor(memory_state)
        attention_mask = torch.ones_like(input_ids).bool()

        generated = self.memory_cell.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            memory_state=memory_state,
            eos_token_id=[self.rmt_config['think_token_id'], self.rmt_config['answer_token_id'], self.rmt_config['eos_token_id']]
            **kwargs
        )

        # Update memory state from generation
        fwd_inputs = torch.cat((input_ids, generated), dim=1)[:, :-1]
        _, memory_state = self.memory_cell(input_ids=fwd_inputs, memory_state=memory_state)

        return generated, memory_state

    def get_bos_tensor(self, memory_state):
        bos = self.rmt_config["bos_token_id"]
        bos_tensor = torch.tensor([bos] * memory_state.shape[0]).reshape(-1, 1)
        return bos_tensor.to(memory_state.device)

    def all_done(self, generated_segments):
        eos = self.rmt_config['eos_token_id']
        bs = generated_segments[0].shape[0]
        have_eos = [any([eos in seg[i] for seg in generated_segments]) for i in range(bs)]
        all_done = all(have_eos)
        return all_done

    def pad_and_segment(self, input_ids):
        bos_id = self.rmt_config.bos_token_id
        pad_id = self.rmt_config.pad_token_id
        mem_size = self.rmt_config.num_mem_tokens
        mem_template = [self.rmt_config.mem_id] * mem_size
        
        segments_batch = split_by_bos(input_ids, bos_id, pad_id)
        segments_batch = [[torch.tensor(mem_template + seg + mem_template) for seg in sample_segments] for sample_segments in segments_batch]

        # if some samples have less segments than others, we extend them with empty segments
        max_segments = max(len(segments) for segments in segments_batch)
        for segments in segments_batch:
            if len(segments) < max_segments:
                segments += [torch.tensor(eos)] * (max_segments - len(segments))

        batch_segments = [[seg[seg_num] for seg in segments_batch] for seg_num in range(max_segments)]

        labels_masks = [[torch.ones_like(samp) for samp in segment] for segment in batch_segments]
        attention_masks = [[torch.ones_like(samp) for samp in segment] for segment in batch_segments]

        read_memory_masks = [[torch.zeros_like(samp) for samp in segment] for segment in batch_segments]
        write_memory_masks = [[torch.zeros_like(samp) for samp in segment] for segment in batch_segments]

        input_segments = []
        for seg_num in range(max_segments):
            for bn, sample in enumerate(batch_segments[seg_num]):
                if seg_num == 0:
                    labels_masks[seg_num][bn] *= 0
                read_memory_masks[seg_num][bn][:mem_size] = 1
                write_memory_masks[seg_num][bn][-mem_size:] = 1
                labels_masks[seg_num][bn][:mem_size] = 0
                labels_masks[seg_num][bn][-mem_size:] = 0

            segment = {"input_ids": pad_sequence(batch_segments[seg_num], batch_first=True, padding_value=id_pad_value),
                    "attention_mask": pad_sequence(attention_masks[seg_num], batch_first=True, padding_value=0),
                    "labels": pad_sequence(batch_segments[seg_num], batch_first=True, padding_value=-100),
                    "labels_mask": pad_sequence(labels_masks[seg_num], batch_first=True, padding_value=0),
                    "read_memory_mask": pad_sequence(read_memory_masks[seg_num], batch_first=True, padding_value=0),
                    "write_memory_mask": pad_sequence(write_memory_masks[seg_num], batch_first=True, padding_value=0)
                    }
            input_segments.append(segment)
        return input_segments

        
    def process_outputs(self, cell_outputs, **kwargs):
        raise NotImplementedError
        out = CausalLMOutputWithCrossAttentions()
        full_logits = torch.cat([o.logits for o in cell_outputs], dim=1)
        full_hidden_states = tuple([torch.cat(layer_hs, dim=1)
                                    for layer_hs in zip(*[o.hidden_states for o in cell_outputs])])

        labels = kwargs.get('labels')
        if labels is not None:
            shift_labels = labels[..., 1:].contiguous()
            shift_logits = full_logits[..., :-1, :].contiguous()
            flat_labels = shift_labels.view(-1)
            flat_logits = shift_logits.view(-1, shift_logits.size(-1))

            loss_fct = CrossEntropyLoss()
            labels_mask = kwargs.get('labels_mask')
            if labels_mask is not None:
                shift_mask = labels_mask[..., :-1].contiguous()

                flat_labels = flat_labels[shift_mask.view(-1)]
                flat_logits = flat_logits[shift_mask.view(-1)]

            out['loss'] = loss_fct(flat_logits, flat_labels)
        else:
            out['loss'] = 0

        out['logits'] = full_logits
        segment_keys = ['loss', 'logits']
        if kwargs.get('output_attentions'):
            segment_keys.append('attentions')
        if kwargs.get('output_hidden_states'):
            segment_keys.append('hidden_states')
            out['hidden_states'] = full_hidden_states

        return out

    def manage_gradients(self, memory_state, seg_num):
        k2, max_n_segments = self.rmt_config.get('k2'), self.rmt_config.get('max_n_segments')
        if seg_num == 0 \
            or k2 in {-1, None} \
                or seg_num + k2 > max_n_segments:
            return memory_state

        memory_state = memory_state.detach()
        return memory_state

    def gradient_checkpointing_enable(self, *args, **kwargs):
        self.memory_cell.model.gradient_checkpointing_enable(*args, **kwargs)

# trash

In [14]:

import argparse
import importlib
import os
import sys
from dataclasses import dataclass, field
from typing import Optional

from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoModelForSequenceClassification, AutoTokenizer

from trl import GRPOConfig, GRPOTrainer, ModelConfig, ScriptArguments, TrlParser, get_peft_config
from trl.rewards import think_format_reward

In [15]:
from trl_rmt.trl.trainer.grpo_config import GRPOConfig as RMTGRPOConfig
from trl_rmt.trl.trainer.grpo_trainer import GRPOTrainer as RMTGRPOTrainer

In [16]:
reward_funcs_registry = {
    "think_format_reward": think_format_reward,
}

In [ ]:
model_name = "HuggingFaceTB/SmolLM2-135M-Instruct"

In [18]:

# Dummy reward function: count the number of unique characters in the completions
def reward_num_unique_chars(completions, **kwargs):
    return [len(set(c)) for c in completions]

In [ ]:
training_args = GRPOConfig(f"{model_name}-GRPO",
                    report_to='tensorboard',
                    per_device_train_batch_size=2,
                    per_device_eval_batch_size=2,
                    num_generations=2,
                    logging_steps=1
                    )

In [20]:
# Load a pretrained model
model = AutoModelForCausalLM.from_pretrained(model_name
)
tokenizer = AutoTokenizer.from_pretrained(model_name
)

# Get the reward models and functions
reward_funcs = []
# if script_args.reward_model_name_or_path:
#     reward_model = AutoModelForSequenceClassification.from_pretrained(
#         script_args.reward_model_name_or_path, trust_remote_code=model_args.trust_remote_code, num_labels=1
#     )
#     reward_funcs.append(reward_model)

# if script_args.reward_funcs:
#     for func_name in script_args.reward_funcs:
#         if func_name in reward_funcs_registry:
#             reward_funcs.append(reward_funcs_registry[func_name])
#         elif "." in func_name:
#             module_path, func_name = func_name.rsplit(".", 1)
#             sys.path.insert(0, os.getcwd())
#             module = importlib.import_module(module_path)
#             reward_func = getattr(module, func_name)
#             reward_funcs.append(reward_func)
#         else:
#             raise ValueError(
#                 f"Could not load reward function '{func_name}'. Expected one of "
#                 f"{list(reward_funcs_registry.keys())} or a valid import path."
#             )
reward_funcs.append(reward_num_unique_chars)

# Load the dataset
# dataset = load_dataset(script_args.dataset_name, name=script_args.dataset_config)
dataset = load_dataset("trl-lib/tldr", split="train[:100]")

# Initialize the GRPO trainer
trainer = GRPOTrainer(
    model=model,
    reward_funcs=reward_funcs,
    args=training_args,
    train_dataset=dataset,
    eval_dataset=dataset,
    processing_class=tokenizer,
    # peft_config=get_peft_config(model_args),
)

# Train and push the model to the Hub
trainer.train()

# # Save and push to hub
# trainer.save_model(training_args.output_dir)
# if training_args.push_to_hub:
#     trainer.push_to_hub(dataset_name=script_args.dataset_name)

[2025-08-01 14:25:54,227] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /home/jovyan/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.

/workspace-SR006.nfs2/bulatov/envs/rmt/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/workspace-SR006.nfs2/bulatov/envs/rmt/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status

[2025-08-01 14:25:56,681] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False

KeyboardInterrupt:

In [ ]:


reward_funcs_registry = {
    "think_format_reward": think_format_reward,
}


@dataclass
class GRPOScriptArguments(ScriptArguments):
    """
    Script arguments for the GRPO training script.

    Args:
        reward_model_name_or_path (`str` or `None`, *optional*, defaults to `None`):
            Reward model id of a pretrained model hosted inside a model repo on huggingface.co or local path to a
            directory containing model weights saved using [`~transformers.PreTrainedModel.save_pretrained`].
        reward_funcs (`list[str]` or `None`, *optional*, defaults to `None`):
            Reward functions to use. It can be either one of `"think_format_reward"`; or a dotted import path " (e.g.,
            `'my_lib.rewards.custom_reward'`).
    """

    reward_model_name_or_path: Optional[str] = field(
        default=None,
        metadata={
            "help": "Reward model id of a pretrained model hosted inside a model repo on huggingface.co or "
            "local path to a directory containing model weights saved using `PreTrainedModel.save_pretrained`."
        },
    )
    reward_funcs: Optional[list[str]] = field(
        default=None,
        metadata={
            "help": "Reward functions to use. It can be either one of  'think_format_reward'; or a dotted "
            "import path. (e.g., 'my_lib.rewards.custom_reward')."
        },
    )


def main(script_args, training_args, model_args):
    # Load a pretrained model
    model = AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path, trust_remote_code=model_args.trust_remote_code
    )
    tokenizer = AutoTokenizer.from_pretrained(
        model_args.model_name_or_path, trust_remote_code=model_args.trust_remote_code
    )

    # Get the reward models and functions
    reward_funcs = []
    if script_args.reward_model_name_or_path:
        reward_model = AutoModelForSequenceClassification.from_pretrained(
            script_args.reward_model_name_or_path, trust_remote_code=model_args.trust_remote_code, num_labels=1
        )
        reward_funcs.append(reward_model)

    if script_args.reward_funcs:
        for func_name in script_args.reward_funcs:
            if func_name in reward_funcs_registry:
                reward_funcs.append(reward_funcs_registry[func_name])
            elif "." in func_name:
                module_path, func_name = func_name.rsplit(".", 1)
                sys.path.insert(0, os.getcwd())
                module = importlib.import_module(module_path)
                reward_func = getattr(module, func_name)
                reward_funcs.append(reward_func)
            else:
                raise ValueError(
                    f"Could not load reward function '{func_name}'. Expected one of "
                    f"{list(reward_funcs_registry.keys())} or a valid import path."
                )

    # Load the dataset
    dataset = load_dataset(script_args.dataset_name, name=script_args.dataset_config)

    # Initialize the GRPO trainer
    trainer = GRPOTrainer(
        model=model,
        reward_funcs=reward_funcs,
        args=training_args,
        train_dataset=dataset[script_args.dataset_train_split],
        eval_dataset=dataset[script_args.dataset_test_split] if training_args.eval_strategy != "no" else None,
        processing_class=tokenizer,
        peft_config=get_peft_config(model_args),
    )

    # Train and push the model to the Hub
    trainer.train()

    # Save and push to hub
    trainer.save_model(training_args.output_dir)
    if training_args.push_to_hub:
        trainer.push_to_hub(dataset_name=script_args.dataset_name)


def make_parser(subparsers: argparse._SubParsersAction = None):
    dataclass_types = (GRPOScriptArguments, GRPOConfig, ModelConfig)
    if subparsers is not None:
        parser = subparsers.add_parser("grpo", help="Run the GRPO training script", dataclass_types=dataclass_types)
    else:
        parser = TrlParser(dataclass_types)
    return parser


if __name__ == "__main__":
    parser = make_parser()
    script_args, training_args, model_args = parser.parse_args_and_config()
    main(script_args, training_args, model_args)

### Eval loop

In [ ]:
def evaluate(model, dataset, device='cpu', bs=16, max_new_tokens=25):
    all_preds, all_labels = [], []
    all_preds_cot, all_labels_cot = [], []
    all_preds_ans, all_labels_ans = [], []

    for start_ind in range(0, len(dataset), bs):
        batch = dataset.select(range(start_ind, min(len(dataset), start_ind + bs)))
        collated = collate_fn(batch)
        task = collated['segments'][0]
        task = {k:v.to(device) for k,v in task.items()}

        with torch.no_grad():
            # gen_out = model.generate([task], max_new_tokens=max_new_tokens, pad_token_id=eos[0])
            gen_out = generate(model.rmt, [task], max_new_tokens=max_new_tokens, pad_token_id=eos[0])
        

        preds_full = torch.cat(gen_out, dim=1)
        labels = collated['labels']

        labels_masks = labels > 0
        labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

        for lab_tokens, pred_tokens in zip(labels_full, preds_full):
            lab_tokens = [t.item() for t in lab_tokens if t != bos[0]]
            
            
            ans_start_index_l = max(i for i, x in enumerate(lab_tokens) if x == ans[0])
            if ans[0] in pred_tokens:
                ans_start_index_p = max(i for i, x in enumerate(pred_tokens) if x == ans[0])
            else:
                ans_start_index_p = ans_start_index_l
            # ans_start_index_p = ans_start_index_l

            pred_cot_tokens = pred_tokens[:ans_start_index_p].tolist()
            lab_cot_tokens = lab_tokens[:ans_start_index_l]

            all_preds_cot.append(pred_cot_tokens)
            all_labels_cot.append(lab_cot_tokens)

            all_preds_ans.append(pred_tokens[ans_start_index_p:].tolist()[:-1])
            all_labels_ans.append(lab_tokens[ans_start_index_l:])

            all_preds.append(pred_tokens.tolist())
            all_labels.append(lab_tokens)
    
    cot_correct = [p == l for p, l in zip(all_preds_cot, all_labels_cot)]
    ans_correct = [p == l for p, l in zip(all_preds_ans, all_labels_ans)]
    res = {'accuracy_cot': np.mean(cot_correct).item(), 'accuracy_ans': np.mean(ans_correct).item()}
    data = {"all_preds_cot": all_preds_cot,
            "all_labels_cot": all_labels_cot,
            "all_preds_ans": all_preds_ans,
            "all_labels_ans": all_labels_ans,
            "all_preds": all_preds,
            "all_labels": all_labels}
    return res, data

In [ ]:
# # def eval_checkpoint(cpt_path, device='cuda'):
# all_results = []
# for checkpoint_path in checkpoints[1:]:
#     # model_name = "gpt2"
#     device='cuda'
#     model_name = "HuggingFaceTB/SmolLM2-135M"
#     mem_size = int(checkpoint_path.split('mem')[1].split('_')[0])

#     # model = AutoModelForCausalLM.from_pretrained(model_name)
#     tokenizer = AutoTokenizer.from_pretrained(model_name)

#     config = RMTConfig(num_mem_tokens=mem_size, 
#                    think_token_id=think[0],
#                    answer_token_id=ans[0],
#                    bos_token_id=bos[0],
#                    eos_token_id=eos[0]
#                    )
#     rmt = RMT(config)
#     rmt.load_state_dict(torch.load(checkpoint_path + "/pytorch_model.bin"), strict=True)
#     rmt.to(device)
#     print(':)')


#     bs = 1
#     # res, data = evaluate(rmt, valid_dataset, bs=bs, device=device)
#     res, data = evaluate(rmt, valid_dataset.select(range(32)), bs=bs, device=device)
#     # res
#     model_name = checkpoint_path.split("gsm8k")[1]
#     all_results.append({'model_name': model_name, 'data': data, **res})
#     print(model_name, res)
#     # 1/0

In [ ]:
# res, data = evaluate(rmt, valid_dataset.select(range(32)), bs=bs, device=device)
# res

In [ ]:
config.get('test')

In [ ]:
# with open('gsm_predicts/v3.json', 'w') as f:
#     json.dump(all_results, f)

In [ ]:
res

{'accuracy_cot': 0.09375, 'accuracy_ans': 0.25}

In [ ]:
for res_d in all_results:
    print(res_d['model_name'], res_d['accuracy_cot'], res_d['accuracy_ans'])

In [ ]:
correct_ans_inds = [i for i, (p, l) in enumerate(zip(data['all_preds_ans'], data['all_labels_ans'])) if p == l]

In [ ]:
v2_correct_inds = [2, 3, 5, 16, 24, 27, 29, 34, 42, 44, 49, 51, 57, 66, 68, 71, 78, 86, 94, 96, 100, 104, 106, 108, 110, 112, 116, 120, 123, 130, 138, 145, 147, 148, 151, 152, 156, 158, 159, 166, 173, 175, 184, 187, 188, 189, 190, 191, 195, 200, 211, 213, 214, 221, 234, 236, 241, 245, 249, 255, 256, 257, 258, 259, 264, 265, 267, 268, 271, 273, 275, 285, 297, 299, 300, 302, 307, 310, 316, 331, 334, 336, 341, 342, 345, 348, 353, 354, 356, 359, 365, 367, 370, 377, 391, 401, 406, 409, 414, 417, 419, 424, 432, 433, 434, 438, 441, 446, 452, 453, 460, 469, 472, 473, 476, 477, 479, 480, 484, 488, 489, 490, 491, 495, 498]

In [ ]:
sample_ind = 5

print("Prediction COT:")
print(tokenizer.decode(data['all_preds_cot'][sample_ind]))
print("\nLabel COT:")
print(tokenizer.decode(data['all_labels_cot'][sample_ind]))
print("\nPrediction Answer:")
print(tokenizer.decode(data['all_preds_ans'][sample_ind]))
print("\nLabel Answer:")
print(tokenizer.decode(data['all_labels_ans'][sample_ind]))
print("\nLabel Full:")
print(tokenizer.decode(data['all_labels'][sample_ind]))
print("\nPrediction Full:")
print(tokenizer.decode(data['all_preds'][sample_ind]))

Prediction COT:
100/2=50<issue_start>50*(3/5)=30<issue_start>100-50-30=20

Label COT:
1/2*100=50<issue_start>3/5*50=30<issue_start>50-30=20

Prediction Answer:
<issue_closed>20

Label Answer:
<issue_closed>20

Label Full:
1/2*100=50<issue_start>3/5*50=30<issue_start>50-30=20<issue_closed>20

Prediction Full:
100/2=50<issue_start>50*(3/5)=30<issue_start>100-50-30=20<issue_closed>20<|endoftext|>

In [ ]:
correct_ans_inds

[2, 5, 12, 16, 19, 23, 24, 29]

In [ ]:
# for sample_ind in range(1, 100, 1):
# for sample_ind in range(len(data['all_labels'])):
# for sample_ind in correct_ans_inds:
for sample_ind in v2_correct_inds:

    print('\nT: ', tokenizer.decode(data['all_labels'][sample_ind]))
    print('P: ', tokenizer.decode(data['all_preds'][sample_ind]))

T:  30/100*2000=600<issue_start>2000-600=1400<issue_closed>1400
P:  2000*30/100=600<issue_start>2000-600=1400<issue_closed>1400<|endoftext|>

T:  21/7=3<issue_start>5*3=15<issue_closed>15
P:  21/7=3.142857142857143<issue_start>3.142857142857143*5=15.0015.00/7=2.14<issue_closed>2.14<|endoftext|>

T:  1/2*100=50<issue_start>3/5*50=30<issue_start>50-30=20<issue_closed>20
P:  100/2=50<issue_start>50*(3/5)=30<issue_start>100-50-30=20<issue_closed>20<|endoftext|>

T:  10+15=25<issue_start>2*10=20<issue_start>20+25=45<issue_closed>45
P:  10*2=20<issue_start>10+20+15=45<issue_closed>45<|endoftext|>

T:  30000-10000=20000<issue_start>20000*0.40=8000<issue_start>20000-8000=12000<issue_closed>12000
P:  30000-10000=20000<issue_start>20000*0.40=8000<issue_start>20000-8000=12000<issue_closed>12000<|endoftext|>

T:  7+14=21<issue_start>21+10=31<issue_start>2*11=22<issue_start>31+22=53<issue_closed>53
P:  11+10+14+7=42<issue_start>42+7=59<issue_closed>59<|endoftext|>

T:  220*1=220<issue_start>70*2=140<issue_start>220+140=360<issue_closed>360
P:  220*1=220<issue_start>220*1=220<issue_start>70*2=140<issue_start>220+140=360<issue_closed>360<|endoftext|>

IndexError: list index out of range

In [ ]:
for sample_ind in range(1, 100, 1):
# for sample_ind in range(len(data)):
    print('\nT: ', tokenizer.decode(data['all_labels'][sample_ind]))
    print('P: ', tokenizer.decode(data['all_preds'][sample_ind]))

T:  1.5*2=3<issue_start>3+2.5=5.5<issue_start>1.5+3+5.5=10<issue_closed>10
P:  1.5+2.5+1.5+1.5+1.5+1.5+11.5+1.5+1.5+1.5+1.5+1.5+11.5+1.5+1.5+1.5+1.5+1.5+11+1.5+1.5+1.5+1.5+1.5+1.51.5+1.5+1.5+1.5+1.5+1.5+11.5+1.5+1.5+1.5+1.5+1.5+11.5+1.5+1.5+1.5+1.5+1.5+11.5+1.5+1.5+1.5+1.5+1.5+11.5+1.5+1.5+1.5+1.5+1.5+1

T:  30/100*2000=600<issue_start>2000-600=1400<issue_closed>1400
P:  2000*30/100=600<issue_start>2000-600=1400<issue_closed>1400<|endoftext|>

T:  21/7=3<issue_start>5*3=15<issue_closed>15
P:  21/7=3.142857142857143<issue_start>3.142857142857143*5=15.0015.00/7=2.14<issue_closed>2.14<|endoftext|>

T:  200*3=600<issue_start>600*.4=240<issue_closed>240
P:  200/3=66.66666666666667<issue_start>40/100*66.67=26.67<issue_start>66.67-26.67=40.04<issue_closed>40.04<|endoftext|>

T:  1/2*100=50<issue_start>3/5*50=30<issue_start>50-30=20<issue_closed>20
P:  100/2=50<issue_start>50*(3/5)=30<issue_start>100-50-30=20<issue_closed>20<|endoftext|>

T:  40/2=20<issue_start>20/2=10<issue_closed>10
P:  40/2=20<issue_start>20*2=40<issue_closed>40<|endoftext|>

T:  12*2=24<issue_start>4*1=4<issue_start>3*4=12<issue_start>24+4+12=40<issue_start>12+4+4=20<issue_start>40/20=2<issue_closed>2
P:  12*2+4*1+4*3+12*1=136<issue_start>136/13=10.38461538461538410.384615384615384+0.25=1136/13=10.30<issue_closed>10.30<|endoftext|>

T:  2*2.25=4.50<issue_start>2*4=8.00<issue_start>2*2.50=5.00<issue_start>4.50+8.00+.50+5.00+3.50+3.50=25.00<issue_closed>25
P:  2.2+2.5+3.5+2+2.5+3.5=15.15.*2=30.00<issue_start>30+15+3.50=48.50<issue_closed>48.50<|endoftext|>

T:  32=32<issue_start>8=8<issue_closed>25
P:  33/3=11.333333333333334<issue_start>11.333333333333334-1=10.310.3-3=7.3<issue_closed>7.3<|endoftext|>

T:  14/2=7<issue_start>15/3=5<issue_start>2*5=10<issue_start>14-10=4<issue_closed>4
P:  14+15+2+3=34<issue_start>34/15=2.1333333333333332<issue_start>34-2.1333333333333333=31.31-34=-13<issue_closed>-13<|endoftext|>

T:  98-43=55<issue_start>55+23=78<issue_start>73=73<issue_start>73+7=80<issue_closed>80
P:  98+43+34+23=200<issue_start>200-7=193<issue_closed>193<|endoftext|>

T:  12*10=120<issue_start>130-120=10<issue_closed>10
P:  12*10=120<issue_start>130-120=10<issue_closed>10<|endoftext|>

T:  80-20=60<issue_start>60/2=30<issue_start>30*3=90<issue_start>90-10=80<issue_closed>80
P:  80-20-20-10=30<issue_start>30/3=10<issue_start>10+30+80+10=130<issue_closed>130<|endoftext|>

T:  27-7=20<issue_start>103-27-20=56<issue_start>56/2=28<issue_closed>28
P:  27-7=20<issue_start>103-27-20-20=37<issue_start>37/4=9.25<issue_closed>9.25<|endoftext|>

T:  102-85=17<issue_closed>20
P:  (85/120)*100=71.25<issue_closed>71.25<|endoftext|>

T:  10+15=25<issue_start>2*10=20<issue_start>20+25=45<issue_closed>45
P:  10*2=20<issue_start>10+20+15=45<issue_closed>45<|endoftext|>

T:  109-5=104<issue_start>104*2=208<issue_start>109*2=218<issue_start>208+218=426<issue_start>500-426=74<issue_closed>74
P:  109*2=218<issue_start>218-500=-238<issue_closed>-238<|endoftext|>

T:  3*10=30<issue_start>90*3=270<issue_start>30*4=120<issue_start>120+270=390<issue_closed>390
P:  30/60=0.5<issue_start>10/60=0.166666666666666660.167*4=6.68<issue_start>6.68+0.67+0.5=7.25<issue_closed>7.25<|endoftext|>

T:  8*7=56<issue_start>56-2=54<issue_closed>54
P:  8*7=56<issue_start>56-2=54<issue_closed>54<|endoftext|>

T:  8*16=128.00<issue_start>128*5=640.00<issue_start>2*13.50=27.00<issue_start>27*5=135.00<issue_start>640+135=775.00<issue_closed>775
P:  16+13.5+8+2=39.5<issue_start>39.5*5=192.5<issue_closed>192.5<|endoftext|>

T:  3+2=5<issue_start>2+2=4<issue_start>5*4=20<issue_start>80/20=4<issue_closed>4
P:  80/2=40<issue_start>40/2=20<issue_closed>20<|endoftext|>

T:  4*20=80<issue_start>400/80=5<issue_closed>5
P:  400/20=20<issue_closed>20<|endoftext|>

T:  2+1+3=6<issue_start>6*8=48<issue_start>48/16=3<issue_closed>3
P:  16*2/3=10.66666666666666611*2=22<issue_start>22/8=2.75<issue_closed>3<|endoftext|>

T:  30000-10000=20000<issue_start>20000*0.40=8000<issue_start>20000-8000=12000<issue_closed>12000
P:  30000-10000=20000<issue_start>20000*0.40=8000<issue_start>20000-8000=12000<issue_closed>12000<|endoftext|>

T:  800*0.4=320<issue_closed>320
P:  400*0.40=160.00<issue_closed>160<|endoftext|>

T:  5*6=30<issue_start>5*7=35<issue_start>100-35-30=35<issue_start>35/5=7<issue_closed>7
P:  100/5=20<issue_start>20/5=4<issue_closed>4<|endoftext|>

T:  7+14=21<issue_start>21+10=31<issue_start>2*11=22<issue_start>31+22=53<issue_closed>53
P:  11+10+14+7=42<issue_start>42+7=59<issue_closed>59<|endoftext|>

T:  1/2*28=14<issue_start>14+37=51<issue_start>51-2=49<issue_start>49+1=50<issue_closed>50
P:  37+28+31+2+1=98<issue_closed>98<|endoftext|>

T:  220*1=220<issue_start>70*2=140<issue_start>220+140=360<issue_closed>360
P:  220*1=220<issue_start>220*1=220<issue_start>70*2=140<issue_start>220+140=360<issue_closed>360<|endoftext|>

T:  22/2=11<issue_start>2*13=26<issue_start>22+13+11+26=72<issue_closed>72
P:  22/2=11<issue_start>22+13+11+13+13=68<issue_closed>68<|endoftext|>

T:  84*2/3=56<issue_start>84+56=140<issue_start>140+10=150<issue_start>150*8=1200<issue_closed>1200
P:  84/3=28.00<issue_start>28+84+8+10=140.00<issue_start>140/8=17.50<issue_closed>17.50<|endoftext|>

T:  90/5=18<issue_start>18-5-2=11<issue_start>11*5=55<issue_closed>55
P:  5*90/5=300<issue_start>300-90-200=100<issue_closed>100<|endoftext|>

T:  10*5=50<issue_start>6*128=768<issue_start>768/50=15.36<issue_closed>15
P:  128/10=12.8<issue_start>12.8/6=2.133333333333333512.21+2.13=14.34<issue_closed>14.34<|endoftext|>

T:  100*2=200<issue_start>50*3=150<issue_start>200+150=350<issue_start>500-350=150<issue_closed>150
P:  100*2=200<issue_start>500-200-300=100<issue_closed>100<|endoftext|>

T:  16/2=8<issue_start>8*4=32<issue_start>16+32+8=56<issue_closed>56
P:  16/1.5=10.66666666666666611*4=44<issue_closed>44<|endoftext|>

T:  60=60<issue_start>60/3=20<issue_start>60+20=80<issue_closed>80
P:  30*3=90<issue_start>30+90+30+30+90=300<issue_closed>300<|endoftext|>

T:  45+123=168<issue_start>168/14=12<issue_closed>12
P:  144/14=10.33333333333333410.333333333333334+132=1414+14=28<issue_closed>28<|endoftext|>

T:  20/4=5<issue_start>60-5=55<issue_closed>55
P:  60/4=15<issue_start>15-20+15+15+15=60<issue_closed>60<|endoftext|>

T:  10-7=3<issue_start>3*5=15<issue_closed>15
P:  10*5=50<issue_start>7*5=35<issue_start>50-35=15<issue_closed>15<|endoftext|>

T:  5*1=5<issue_start>3*2=6<issue_start>2*3=6<issue_start>5+3+2=10<issue_start>10/5=2<issue_start>5+6+6=17<issue_start>17-2=15<issue_closed>15
P:  5+3+2+3+1=15.00<issue_start>15/5=3.00<issue_start>5*3=15.00<issue_start>15-15=0.00<issue_closed>0<|endoftext|>

T:  500/50=10<issue_start>20*10=200<issue_start>10*.2=2<issue_start>1000+200+2=1202<issue_start>20*500=10000<issue_start>10000-1202=8798<issue_closed>8798
P:  500/50=10<issue_start>1000/50=200<issue_start>1000/20=50<issue_start>1000/20=50<issue_start>200+50+50=300<issue_closed>300<|endoftext|>

T:  25+15+40=80<issue_start>150-80=70<issue_closed>70
P:  150-25-40=105<issue_start>105-105/3=71.66666666666671.67=71.67<issue_closed>71.67<|endoftext|>

T:  36*125*.01=45<issue_start>45*200*.01=90<issue_closed>90
P:  36/1.25=28.8888888888888928.89*100=2889<issue_closed>2889<|endoftext|>

T:  4000/50=80<issue_start>80/10=8<issue_closed>8
P:  4000/50=80<issue_start>80/10=8<issue_closed>8<|endoftext|>

T:  20=20<issue_closed>146
P:  239/11=21.52105260477577421.52*4=85.32<issue_closed>85.32<|endoftext|>

T:  4*2=8<issue_start>26-8=18<issue_start>18/3=6<issue_closed>6
P:  26/4=6.5025025025025025<issue_closed>6.5025025025025022<|endoftext|>

T:  60*0.5=30<issue_start>120-30=90<issue_start>1.5-0.5=1<issue_closed>90
P:  120/60=2.083333333333333530*2.0833333333333333=62.62/3=20.67<issue_closed>20.67<|endoftext|>

T:  165/11=15<issue_start>20-15=5<issue_start>5*11=55<issue_start>72-55=17<issue_closed>17
P:  11*160/60=30.50<issue_start>30.50-165+72=103.50<issue_closed>103.50<|endoftext|>

T:  8-6=2<issue_start>8*2=16<issue_start>16-2=14<issue_closed>14
P:  8*2=16<issue_start>16+6=22<issue_start>22-8=14<issue_closed>14<|endoftext|>

T:  6*0.5=3<issue_start>4*0.5=2<issue_start>3+2=5<issue_closed>5
P:  40/60=0.6666666666666666<issue_start>0.6666666666666666*30=20<issue_start>20+100+30+20=250<issue_closed>250<|endoftext|>

T:  30+25+35=90<issue_start>90/3=30<issue_closed>30
P:  30+25+35+35=115<issue_start>115/3=38.333333333333336<issue_closed>38.33<|endoftext|>

T:  2*4000=8000<issue_start>4000+8000=12000<issue_closed>12000
P:  2*4000=8000<issue_start>8000+4000=12000<issue_closed>12000<|endoftext|>

T:  5600*7*.01*2=784<issue_start>5600+784=6384<issue_closed>6384
P:  5600*7/100=392<issue_start>5600+392*7/100=639.4<issue_closed>639.4<|endoftext|>

T:  2*5=10<issue_start>10+3=13<issue_closed>13
P:  3+2+3+4+5+6+7+8+9+10+11=55*5=25<issue_closed>25<|endoftext|>

T:  8*2=16<issue_start>30*16=480<issue_closed>480
P:  8*60=480<issue_start>480/30=16<issue_closed>16<|endoftext|>

T:  20-5=15<issue_start>15*300=4500<issue_start>300-50=250<issue_start>250*2=500<issue_start>4500+500+2000=7000<issue_start>7000-4000=3000<issue_closed>3000
P:  300+300+500+300+200=1500<issue_start>4000-1500-3000=500<issue_closed>500<|endoftext|>

T:  4*2=8<issue_start>8+2=10<issue_closed>10
P:  2+4=6<issue_start>2+6=8<issue_closed>8<|endoftext|>

T:  45*3=135<issue_start>135*2=270<issue_start>135+270+45=450<issue_closed>450
P:  45*3+2*2+45*2=130<issue_closed>130<|endoftext|>

T:  5*60=300<issue_start>4*50=200<issue_start>200+45=245<issue_start>300-245=55<issue_closed>55
P:  45+4+50+60+60=235<issue_start>235/60=3.916666666666667<issue_closed>3.92<|endoftext|>

T:  25-2=23<issue_start>23-4=19<issue_start>25-19=6<issue_closed>6
P:  25-2=23<issue_start>23-4=19<issue_closed>19<|endoftext|>

T:  3*10=30<issue_start>10+12=22<issue_start>30-22=8<issue_closed>8
P:  10/3=3.3333333333333335<issue_start>10+12+3.33=25.33<issue_closed>25.33<|endoftext|>

T:  800*.5=400<issue_start>800+400=1200<issue_start>1200/1000=1.2<issue_start>12*.25=3<issue_start>12+3=15<issue_start>1.2*50=60<issue_start>900=900<issue_start>900/100=9<issue_closed>9
P:  800*50/100=4000<issue_start>800+4000+4000=9800<issue_start>9800/50=196<issue_start>196*0.12=23.04<issue_closed>23.04<|endoftext|>

T:  2025-20=2005<issue_closed>2000
P:  2025-2025/2=1406.67<issue_start>1406.67-3=1403.33<issue_closed>1403.33<|endoftext|>

T:  9+7=16<issue_start>11*16=176<issue_start>1*3=3<issue_start>3+176=179<issue_closed>179
P:  9+7+3+11+1=33<issue_closed>33<|endoftext|>

T:  50*20=1000<issue_start>1000*10=10000<issue_start>10000/200=50<issue_closed>50
P:  200/20=10<issue_start>10/10=1<issue_start>50*1=50<issue_closed>50<|endoftext|>

T:  2*.01*2000=40<issue_start>2000+40=2040<issue_closed>2040
P:  2000*2/100=40<issue_start>2000+40=2040<issue_closed>2040<|endoftext|>

T:  8*4=32<issue_start>32/16=2<issue_start>600/2=300<issue_closed>300
P:  600/4=150<issue_start>150/16=9.375<issue_closed>10<|endoftext|>

T:  50*500=25000<issue_closed>5000
P:  50*500=25000<issue_start>25000*0.20=5000<issue_closed>5000<|endoftext|>

T:  5*6=30<issue_start>30*3=90<issue_start>90*12=1080<issue_closed>1080
P:  12*6=72<issue_start>3*5=15<issue_start>72+15=87<issue_closed>87<|endoftext|>

T:  8*18=144.00<issue_start>10-8=2<issue_start>18*.5=9.00<issue_start>18+9=27.00<issue_start>144*5=720.00<issue_start>27*2=54.00<issue_start>720+270=990.00<issue_closed>990
P:  18+10+10*1/2=24<issue_start>24*5=120.00<issue_closed>120<|endoftext|>

T:  20/2=10<issue_start>300/10=30<issue_closed>30
P:  20/2=10<issue_start>300/10=30<issue_closed>30<|endoftext|>

T:  50+40=90<issue_start>10+20=30<issue_start>90-30=60<issue_closed>60
P:  10+40+20+10=80<issue_start>80/10=8.00<issue_closed>8<|endoftext|>

T:  30+10=40<issue_start>90+10=100<issue_start>40/100=.4<issue_start>.4*100=40<issue_closed>40
P:  90*2/3=600/3=333.33<issue_start>333.33*10/100=33.33<issue_start>333.33+10*0.10=343.33<issue_closed>343.33<|endoftext|>

T:  30+40=70<issue_start>70+90=160<issue_closed>160
P:  90/4=22.5<issue_start>22.5-40+90+90=122.5<issue_closed>122.5<|endoftext|>

T:  20-4=16<issue_start>2*16=32<issue_start>32*5=160<issue_start>160/4=40<issue_closed>40
P:  1/4*1/4=0.5033333333333330.5033333333333333*5=2.532.53*100=253.00<issue_closed>253<|endoftext|>

T:  11*4=44<issue_start>44+2=46<issue_start>11+2=13<issue_start>46+13=59<issue_closed>59
P:  4*11=44<issue_start>44+11+2=57<issue_closed>57<|endoftext|>

T:  97=97<issue_closed>97
P:  300/3=100<issue_start>100/3=33.333333333333336<issue_closed>33.33<|endoftext|>

T:  (180/3)*2=120<issue_start>180-120=60<issue_closed>60
P:  180*2/3=120<issue_start>180-120-120=0<issue_closed>0<|endoftext|>

T:  3*3=9<issue_start>9*5=45<issue_closed>45
P:  3*5=15<issue_start>15+3+5+5+15=40.00<issue_closed>40<|endoftext|>

T:  810/3=270<issue_start>270/3=90<issue_start>90/3=30<issue_closed>30
P:  810/3=270.66666666666666<issue_start>8810+270+70=9940<issue_closed>9940<|endoftext|>

T:  16+10=26<issue_start>3*16=48<issue_start>48-24=24<issue_start>26+24=50<issue_closed>50
P:  16+10+3+10=39<issue_closed>39<|endoftext|>

T:  50*2=100<issue_start>100*2.4=240<issue_start>240-10=230<issue_start>50*.6=30<issue_start>100+230+30=360<issue_closed>360
P:  50*20/100=10.00<issue_start>50+10+10+10=80.00<issue_start>80-80*0.60=64.00<issue_closed>64<|endoftext|>

T:  140/7=20<issue_closed>20
P:  28/5=5.6<issue_start>5.6*7=39.2<issue_closed>39.2<|endoftext|>

T:  50*2=100<issue_start>20/2=10<issue_closed>180
P:  20/2=10<issue_start>50/20=2.50<issue_start>10+2.50=12.50<issue_closed>13<|endoftext|>

T:  10*2=20<issue_start>5*5=25<issue_start>25*2=50<issue_closed>50
P:  10*2+5*5+5*2=30<issue_start>30/10=3<issue_start>3*2=6<issue_closed>6<|endoftext|>

T:  20/10=2<issue_start>20/1=20<issue_start>20-2=18<issue_closed>18
P:  10/10=1<issue_start>20/10=2<issue_start>2-1=1<issue_closed>1<|endoftext|>

T:  50+9+121=180<issue_start>1500-180=1320<issue_start>1320/6=220<issue_closed>220
P:  50+9+121+12=231<issue_start>1500/231=6.222222222222222.6222222222222223+0.62222.6222222222222223=2.62222.6222+0.5=2.1222<issue_start>2.1222/0.5=4.244<issue_closed>4.244<|endoftext|>

T:  60-10=50<issue_start>50/2=25<issue_start>25+5=30<issue_closed>30
P:  60-10=50<issue_start>50/2+5=32.5<issue_closed>32.5<|endoftext|>

T:  <issue_closed>9
P:  99/10=9.999999999999999<issue_start>9.99*5+9.99*5=619.99<issue_closed>620<|endoftext|>

T:  12*5=60<issue_start>150*60=9000.00<issue_closed>9000
P:  12*150.00=1800.00<issue_closed>1800<|endoftext|>

T:  9*10=90<issue_start>90*12=1080<issue_start>1080/18=60<issue_closed>60
P:  9*10=90<issue_start>90/18=5.555555555555555<issue_closed>5.56<|endoftext|>

T:  100-10-60=30<issue_start>100*720/60=1200<issue_start>1200*30/100=360<issue_closed>360
P:  720*10/100=72.00<issue_start>720*60/100=432.00<issue_start>720-72-432=140.00<issue_closed>140<|endoftext|>

T:  2*4=8<issue_start>4/2=2<issue_start>24-4-8-2=10<issue_closed>10
P:  24/2=12<issue_start>12-4=10<issue_start>10/2=5<issue_start>10-5=5<issue_closed>5<|endoftext|>

T:  25+35=60<issue_start>100-60=40<issue_closed>40
P:  25+35=60<issue_start>100-60=40<issue_closed>40<|endoftext|>

T:  24/2=12<issue_start>8+12=20<issue_start>20/2=10<issue_start>24+10=34<issue_closed>34
P:  24/2+8=11.66666666666666611.67/2=5.88<issue_closed>5.88<|endoftext|>

T:  60/5=12<issue_start>12-3=9<issue_closed>9
P:  60*4/5=48<issue_start>60-48-3=19<issue_closed>19<|endoftext|>

T:  500/5=100<issue_start>100/4=25<issue_closed>25
P:  500*20/100=100<issue_start>500*4/100=20<issue_start>100+20+100+500=720<issue_closed>720<|endoftext|>

T:  12/6=2<issue_start>20/2=10<issue_start>10+6=16<issue_closed>16
P:  6/12=0.50<issue_start>0.50*20=10<issue_closed>10<|endoftext|>

T:  2*4=8<issue_start>2*1=2<issue_start>8+6+2=16<issue_start>16*10=160<issue_closed>160
P:  2+1+1+1+1+1+1+1+1+1+1+1=88*10=80<issue_closed>80<|endoftext|>

### Debug

In [ ]:
# dataset = train_dataset
dataset = valid_dataset

In [ ]:
model_ = rmt

In [ ]:
max_new_tokens = 25
bs = 1
start = 3

In [ ]:
batch = dataset.select(range(start, start+bs))
collated = collate_fn(batch)
task = collated['segments'][0]
task = {k:v.to(device) for k,v in task.items()}

with torch.no_grad():
    gen_out = model_.generate([task], max_new_tokens=max_new_tokens, pad_token_id=eos[0])

In [ ]:
# def forward(self, segments, labels, output_attentions=None, output_hidden_states=None):
#     memory_state = None

#     cell_outputs = []
#     for seg_num, segment in enumerate(segments):
#         cell_out, memory_state = self.memory_cell(input_ids=segment['input_ids'],
#                                                     attention_mask=segment['attention_mask'],
#                                                     memory_state=memory_state, output_hidden_states=True)
#         cell_outputs.append(cell_out)
#         self.manage_gradients(memory_state, seg_num)

#     out = self.process_outputs(cell_outputs, segments,
#                                 output_attentions=output_attentions,
#                                 output_hidden_states=output_hidden_states)
#     return out

In [ ]:
collated['segments'] = [{k:v.to(device) for k, v in seg.items()} for seg in collated['segments']]
collated['labels'] = collated['labels'].to(device)

# fwd_out = model_(**collated)
segments = collated['segments']
output_hidden_states = False
output_attentions = False
self = rmt

memory_state = None
memory_states = []

cell_outputs = []
for seg_num, segment in enumerate(segments):
    cell_out, memory_state = self.memory_cell(input_ids=segment['input_ids'],
                                                attention_mask=segment['attention_mask'],
                                                memory_state=memory_state, output_hidden_states=True)
    cell_outputs.append(cell_out)
    self.manage_gradients(memory_state, seg_num)
    memory_states.append(memory_state)

fwd_out = self.process_outputs(cell_outputs, segments,
                            output_attentions=output_attentions,
                            output_hidden_states=output_hidden_states)

preds_fwd = fwd_out.logits.argmax(dim=-1)

full_preds_fwd = []

for p, t in zip(preds_fwd, task['input_ids']):
    task_tokens = [tok.item() for tok in t if tok > 0]
    full_preds_fwd.append(p[len(task_tokens):])

tokenizer.batch_decode(full_preds_fwd)

['521*7=3<issue_closed>15*3=15<issue_closed><issue_closed>15<|endoftext|>1']

In [ ]:
memory_state

tensor([[[-7.1382e-02,  8.1761e-02,  1.0229e-01,  ...,  3.0178e-01,
          -5.0662e-02,  3.1473e-02],
         [ 1.1274e-01, -4.4682e-02,  2.0416e-02,  ...,  1.0955e-01,
           5.7196e-01, -6.4823e-02],
         [-3.0943e-02,  7.8583e-02,  1.0884e-01,  ...,  4.5640e-01,
           5.6274e-02,  3.3129e-03],
         ...,
         [-7.5698e-01, -5.2093e-01,  1.0162e-04,  ...,  6.9938e-01,
           4.7667e-01,  5.4527e-02],
         [-6.8000e-01, -3.9553e-01,  2.4089e-02,  ...,  5.9665e-01,
           5.2332e-01, -2.2472e-01],
         [-7.2552e-01, -3.9916e-01, -3.9264e-02,  ...,  6.0408e-01,
           4.0407e-01, -2.7571e-01]]], device='cuda:0',
       grad_fn=<SliceBackward0>)

In [ ]:
memory_states[0]

tensor([[[-5.1112e-02, -7.7902e-03,  8.6779e-02,  ...,  2.8961e-01,
          -3.6079e-02,  1.0435e-01],
         [ 1.2509e-01, -2.0510e-01,  3.4592e-02,  ..., -1.1187e-01,
           2.4742e-01,  1.0097e+00],
         [-3.2938e-01,  6.0714e-01,  3.8961e-02,  ...,  1.0700e+00,
           4.8255e-01,  2.8357e-01],
         ...,
         [ 9.3913e-01, -3.0696e-02, -1.5729e-01,  ..., -1.6233e-01,
           1.1517e+00, -5.0143e-01],
         [-1.7025e-01,  6.1923e-01, -1.7112e-01,  ...,  1.4929e+00,
           9.8287e-01, -4.2009e-01],
         [-3.2819e-01,  5.1283e-01,  5.5208e-02,  ...,  1.2529e+00,
           1.6250e+00, -9.2957e-04]]], device='cuda:0',
       grad_fn=<SliceBackward0>)

In [ ]:
segment['input_ids']

tensor([[ 0, 33, 40, 38, 32,  0]], device='cuda:0')

In [ ]:
cell_outputs[0].logits

tensor([[[  4.1672, -17.0026, -16.9751,  ..., -17.7124, -10.9809, -18.5471],
         [  7.6989, -17.0104, -16.9591,  ..., -16.8026, -12.3327, -19.7615],
         [  3.7027, -19.3586, -19.3312,  ..., -19.4084, -13.4305, -18.2999],
         ...,
         [  5.2719, -18.1334, -18.0590,  ..., -15.7985, -12.0029, -19.6547],
         [  5.6402, -15.9584, -15.8832,  ..., -15.7049, -11.7316, -18.8170],
         [  3.1084, -13.6640, -13.5532,  ..., -12.0062,  -9.1997, -21.0001]]],
       device='cuda:0', grad_fn=<SliceBackward0>)

In [ ]:
cell_out.logits

tensor([[[  4.1672, -17.0026, -16.9751,  ..., -17.7124, -10.9809, -18.5471],
         [  7.6989, -17.0104, -16.9591,  ..., -16.8026, -12.3327, -19.7615],
         [  3.7027, -19.3586, -19.3312,  ..., -19.4084, -13.4305, -18.2999],
         ...,
         [  5.2719, -18.1334, -18.0590,  ..., -15.7985, -12.0029, -19.6547],
         [  5.6402, -15.9584, -15.8832,  ..., -15.7049, -11.7316, -18.8170],
         [  3.1084, -13.6640, -13.5532,  ..., -12.0062,  -9.1997, -21.0001]]],
       device='cuda:0', grad_fn=<SliceBackward0>)

In [ ]:
self = rmt
segments = [task]
kwargs = {'max_new_tokens': 25}
# self.seg_fwd_inputs = []

memory_state = None

for seg_num, segment in enumerate(segments):
    cell_out, memory_state = self.memory_cell(input_ids=segment['input_ids'],
                                                attention_mask=segment['attention_mask'],
                                                memory_state=memory_state, output_hidden_states=True)
# 1/0

generated_segments = []
for seg_num in range(len(segments), self.rmt_config.get("max_n_segments", 32)):
    output_ids, memory_state = generate_segment_(rmt, memory_state=memory_state, **kwargs)
    # if output_ids[0][-1] == 16993:
    #     output_ids = torch.cat(output_ids, torch.ones(1, 1) * 16993, dim=1)
    generated_segments.append(output_ids)

    if self.all_done(generated_segments):
        break

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

gen

In [ ]:
generated_segments

[tensor([[34, 33, 26, 39, 45, 33, 36, 39, 10]], device='cuda:0'),
 tensor([[33, 36, 39,  0]], device='cuda:0')]

In [ ]:
tokenizer.batch_decode([s[0] for s in generated_segments])

['21*7=147<issue_closed>', '147<|endoftext|>']

fwd

In [ ]:
# seg_outputs = [o.logits.argmax(dim=-1) for o in model_.last_cell_outputs]
seg_outputs = [o.logits.argmax(dim=-1) for o in cell_outputs]
seg_outputs

[tensor([[   34,     0, 22414,    34,    35,    32,    34,    34,    35,    27,
              0,    37,    39,    35,    39,    39,   372,    35,    33,    33,
             39,    34,    34,    33,    32,    33,   323, 10902,    37]],
        device='cuda:0'),
 tensor([[34, 33, 26, 39, 45, 35, 10, 33]], device='cuda:0'),
 tensor([[37, 26, 35, 45, 33, 37, 10, 10]], device='cuda:0'),
 tensor([[33, 37,  0, 33]], device='cuda:0')]

In [ ]:
for seg in seg_outputs:
    print(tokenizer.batch_decode(seg[:, :-1]))

['2<|endoftext|> unlimited230223+<|endoftext|>57377 M311722101ow sleeping']
['21*7=3<issue_closed>']
['5*3=15<issue_closed>']
['15<|endoftext|>']

lab

In [ ]:
for seg in collated['segments']:
    print(tokenizer.batch_decode(seg['input_ids']))

['<|endoftext|>A set of 7 spoons costs $21. If each spoon would be sold separately, how much would 5 spoons cost?<issue_start>']
['<|endoftext|>21/7=3<issue_start>']
['<|endoftext|>5*3=15<issue_closed>']
['<|endoftext|>15<|endoftext|>']

In [ ]:
self.seg_fwd_inputs

[]

In [ ]:
fwd_out.loss

tensor(0.1973, device='cuda:0', grad_fn=<DivBackward0>)

In [ ]:
gen_out

[tensor([[   34,    32,    27,    35,    32,    27,    35,    32,    45,    38,
             32, 16693]], device='cuda:0'),
 tensor([[   33,    32,    32,    29,    38,    32,    45,    36,    32, 16693]],
        device='cuda:0'),
 tensor([[   36,    32,    31,    36,    45,    33,    32, 36689]],
        device='cuda:0'),
 tensor([[   33,    32,    32,    29,    38,    32,    29,    33,    32,    45,
             34,    32, 16693]], device='cuda:0'),
 tensor([[   34,    32,    31,    36,    45,    37, 36689]], device='cuda:0'),
 tensor([[   37,    31,    36,    45,    33,    30,    34,    37, 36689]],
        device='cuda:0'),
 tensor([[   33,    32,    27,    37,    27,    33,    30,    34,    37,    45,
             33,    38,    30,    34,    37, 36689]], device='cuda:0'),
 tensor([[   33,    38,    30,    34,    37,    31,    36,    45,    36,    30,
             32,    38,    34,    37, 36689]], device='cuda:0'),
 tensor([[   36,    30,    32,    38,    34,    37,    31,    36,    45,    33,
             30,    32,    40,    39,    37, 36689]], device='cuda:0')]

In [ ]:
tokenizer.batch_decode([o[0] for o in gen_out])

['20+30+30=60??',
 '100-60=40??',
 '40/4=10!!!!',
 '100-60-10=20??',
 '20/4=5!!!!',
 '5/4=1.25!!!!',
 '10+5+1.25=16.25!!!!',
 '16.25/4=4.0625!!!!',
 '4.0625/4=1.0875!!!!']

In [ ]:
tokenizer.encode('!!!!')

[36689]

In [ ]:
for seg in collated['segments']:
    print(tokenizer.batch_decode(seg['input_ids']))

['////Michael needs 60 minutes to do his homework. His dad promised to buy him a video game if he can finish his homework in 75% of the time. How many minutes should he spend on his homework to get his reward?????']
['////60*75/100=45!!!!']
['////45<|endoftext|>']

In [ ]:

all_preds, all_labels = [], []
all_preds_cot, all_labels_cot = [], []
all_preds_ans, all_labels_ans = [], []

for start_ind in range(0, 10, 1):
    batch = dataset.select(range(start_ind, min(len(dataset), start_ind + bs)))
    collated = collate_fn(batch)
    task = collated['segments'][0]
    task = {k:v.to(device) for k,v in task.items()}

    with torch.no_grad():
        gen_out = model_.generate([task], max_new_tokens=max_new_tokens, pad_token_id=eos[0])
    

    preds_full = torch.cat(gen_out, dim=1)
    labels = collated['labels']

    labels_masks = labels > 0
    labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

    for lab_tokens, pred_tokens in zip(labels_full, preds_full):
        lab_tokens = [t.item() for t in lab_tokens if t != bos[0]]
        
        
        ans_start_index_l = max(i for i, x in enumerate(lab_tokens) if x == ans[0])
        if ans[0] in pred_tokens:
            ans_start_index_p = max(i for i, x in enumerate(pred_tokens) if x == ans[0])
        else:
            ans_start_index_p = ans_start_index_l
        ans_start_index_p = ans_start_index_l

        pred_cot_tokens = pred_tokens[:ans_start_index_p].tolist()
        lab_cot_tokens = lab_tokens[:ans_start_index_l]

        all_preds_cot.append(pred_cot_tokens)
        all_labels_cot.append(lab_cot_tokens)

        all_preds_ans.append(pred_tokens[ans_start_index_p:].tolist())
        all_labels_ans.append(lab_tokens[ans_start_index_l:])

        all_preds.append(pred_tokens.tolist())
        all_labels.append(lab_tokens)

cot_correct = [p == l for p, l in zip(all_preds_cot, all_labels_cot)]
ans_correct = [p == l for p, l in zip(all_preds_ans, all_labels_ans)]
res = {'accuracy_cot': np.mean(cot_correct), 'accuracy_ans': np.mean(ans_correct)}
data = {"all_preds_cot": all_preds_cot,
        "all_labels_cot": all_labels_cot,
        "all_preds_ans": all_preds_ans,
        "all_labels_ans": all_labels_ans,
        "all_preds": all_preds,
        "all_labels": all_labels}

### Evaluate

In [ ]:
def evaluate(model, dataset, device='cpu', bs=16, max_new_tokens=25):
    all_preds, all_labels = [], []
    all_preds_cot, all_labels_cot = [], []
    all_preds_ans, all_labels_ans = [], []

    for start_ind in range(0, len(dataset), bs):
        batch = dataset.select(range(start_ind, min(len(dataset), start_ind + bs)))
        collated = collate_fn(batch)
        task = collated['segments'][0]
        task = {k:v.to(device) for k,v in task.items()}

        with torch.no_grad():
            # gen_out = model.generate([task], max_new_tokens=max_new_tokens, pad_token_id=eos[0])
            gen_out = generate(model, [task], max_new_tokens=max_new_tokens, pad_token_id=eos[0])
        

        preds_full = torch.cat(gen_out, dim=1)
        labels = collated['labels']

        labels_masks = labels > 0
        labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

        for lab_tokens, pred_tokens in zip(labels_full, preds_full):
            lab_tokens = [t.item() for t in lab_tokens if t != bos[0]]
            
            
            ans_start_index_l = max(i for i, x in enumerate(lab_tokens) if x == ans[0])
            if ans[0] in pred_tokens:
                ans_start_index_p = max(i for i, x in enumerate(pred_tokens) if x == ans[0])
            else:
                ans_start_index_p = ans_start_index_l
            # ans_start_index_p = ans_start_index_l

            pred_cot_tokens = pred_tokens[:ans_start_index_p].tolist()
            lab_cot_tokens = lab_tokens[:ans_start_index_l]

            all_preds_cot.append(pred_cot_tokens)
            all_labels_cot.append(lab_cot_tokens)

            all_preds_ans.append(pred_tokens[ans_start_index_p:].tolist()[1:-1])
            all_labels_ans.append(lab_tokens[ans_start_index_l:][1:])

            all_preds.append(pred_tokens.tolist())
            all_labels.append(lab_tokens)
    
    cot_correct = [p == l for p, l in zip(all_preds_cot, all_labels_cot)]
    ans_correct = [p == l for p, l in zip(all_preds_ans, all_labels_ans)]
    res = {'accuracy_cot': np.mean(cot_correct).item(), 'accuracy_ans': np.mean(ans_correct).item()}
    data = {"all_preds_cot": all_preds_cot,
            "all_labels_cot": all_labels_cot,
            "all_preds_ans": all_preds_ans,
            "all_labels_ans": all_labels_ans,
            "all_preds": all_preds,
            "all_labels": all_labels}
    return res, data

In [ ]:
bs = 1
# res, data = evaluate(rmt, valid_dataset.select(range(128)), bs=1, device=device)
res, data = evaluate(rmt, valid_dataset, bs=bs, device=device)
res

{'accuracy_cot': np.float64(0.126), 'accuracy_ans': np.float64(0.0)}

In [ ]:
bs = 1
res, data = evaluate(rmt, valid_dataset.select(range(128)), bs=16, device=device)
# res, data = evaluate(rmt, valid_dataset, bs=bs, device=device)
res

{'accuracy_cot': np.float64(0.015625), 'accuracy_ans': np.float64(0.0)}

In [ ]:
bs = 1
res, data = evaluate(rmt, valid_dataset.select(range(10)), bs=1, device=device)
# res, data = evaluate(rmt, valid_dataset, bs=bs, device=device)
res

{'accuracy_cot': np.float64(0.0), 'accuracy_ans': np.float64(0.0)}

In [ ]:
bs = 1
res, data = evaluate(rmt, valid_dataset, bs=bs, device=device)
res

{'accuracy_cot': np.float64(0.126), 'accuracy_ans': np.float64(0.0)}

In [ ]:
# ans_correct = [[p_ for p_ in p if p_ not in {bos, ans, eos}] == [l_ for l for p, l in zip(data['all_preds_ans'], data['all_labels_ans'])]
ans_correct = [p[1:-1] == l[1:] for p, l in zip(data['all_preds_ans'], data['all_labels_ans'])]
np.mean(ans_correct)

np.float64(0.164)

### interpret

In [ ]:
i = 2

In [ ]:
tokenizer.decode(data['all_preds_cot'][i])

'2000*30/100=600????2000-600=1400'

In [ ]:
tokenizer.decode(data['all_labels_cot'][i])

'30/100*2000=600????2000-600=1400'

In [ ]:
tokenizer.decode(data['all_preds_ans'][i])

'!!!!1400<|endoftext|>'

In [ ]:
tokenizer.decode(data['all_labels_ans'][i])

'!!!!1400'

In [ ]:
tokenizer.decode(data['all_preds'][i])

'630/90=7????800/40=20????20-7=13!!!!13<|endoftext|>'

In [ ]:
tokenizer.decode(data['all_labels'][i])

'630/90=7????800/40=20????20-7=13!!!!13'

In [ ]:
sample_ind = 1

print("Prediction COT:")
print(tokenizer.decode(data['all_preds_cot'][sample_ind]))
print("\nLabel COT:")
print(tokenizer.decode(data['all_labels_cot'][sample_ind]))
print("\nPrediction Answer:")
print(tokenizer.decode(data['all_preds_ans'][sample_ind][1:-1]))
print("\nLabel Answer:")
print(tokenizer.decode(data['all_labels_ans'][sample_ind][1:]))
print("\nLabel Full:")
print(tokenizer.decode(data['all_labels'][sample_ind]))
print("\nPrediction Full:")
print(tokenizer.decode(data['all_preds'][sample_ind]))

Prediction COT:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=9!!!!

Label COT:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=10

Prediction Answer:


Label Answer:
10

Label Full:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=10!!!!10

Prediction Full:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=9!!!!9<|endoftext|>

In [ ]:
sample_ind = 1

for sample_ind in range(10):

    print("Prediction COT:")
    print(tokenizer.decode(data['all_preds_cot'][sample_ind]))
    print("\nLabel COT:")
    print(tokenizer.decode(data['all_labels_cot'][sample_ind]))
    print("\nPrediction Answer:")
    print(tokenizer.decode(data['all_preds_ans'][sample_ind][1:-1]))
    print("\nLabel Answer:")
    print(tokenizer.decode(data['all_labels_ans'][sample_ind][1:]))
    print("\nPrediction Full:")
    print(tokenizer.decode(data['all_preds'][sample_ind]))
    print("\nLabel Full:")
    print(tokenizer.decode(data['all_labels'][sample_ind]))
    print('-' * 100)
    print()

Prediction COT:
12*.5=6????6-4=2????2-2=0????0*365=$0????100-0=100

Label COT:
4-2=2????2/.5=4????12/4=3????100*3=300

Prediction Answer:
100

Label Answer:
300

Prediction Full:
12*.5=6????6-4=2????2-2=0????0*365=$0????100-0=100!!!!100<|endoftext|>

Label Full:
4-2=2????2/.5=4????12/4=3????100*3=300!!!!300
----------------------------------------------------------------------------------------------------

Prediction COT:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=9

Label COT:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=10

Prediction Answer:
9

Label Answer:
10

Prediction Full:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=9!!!!9<|endoftext|>

Label Full:
1.5*2=3????3+2.5=5.5????1.5+3+5.5=10!!!!10
----------------------------------------------------------------------------------------------------

Prediction COT:
2000*30/100=600????2000-600=1400

Label COT:
30/100*2000=600????2000-600=1400

Prediction Answer:
1400

Label Answer:
1400

Prediction Full:
2000*30/100=600????2000-600=1400!!!!1400<|endoftext|>

Label Full:
30/100*2000=600????2000-600=1400!!!!1400
----------------------------------------------------------------------------------------------------

Prediction COT:
21/7=3????3*5=15

Label COT:
21/7=3????5*3=15

Prediction Answer:
15

Label Answer:
15

Prediction Full:
21/7=3????3*5=15!!!!15<|endoftext|>

Label Full:
21/7=3????5*3=15!!!!15
----------------------------------------------------------------------------------------------------

Prediction COT:
200*3=600????600*40*.01=240????600+240=840

Label COT:
200*3=600????600*.4=240

Prediction Answer:
840

Label Answer:
240

Prediction Full:
200*3=600????600*40*.01=240????600+240=840!!!!840<|endoftext|>

Label Full:
200*3=600????600*.4=240!!!!240
----------------------------------------------------------------------------------------------------

Prediction COT:
100/2=50????50/3/5=10????50-10=40

Label COT:
1/2*100=50????3/5*50=30????50-30=20

Prediction Answer:
40

Label Answer:
20

Prediction Full:
100/2=50????50/3/5=10????50-10=40!!!!40<|endoftext|>

Label Full:
1/2*100=50????3/5*50=30????50-30=20!!!!20
----------------------------------------------------------------------------------------------------

Prediction COT:
40/3=13.33????13.33*2=26.66

Label COT:
40/2=20????20/2=10

Prediction Answer:
26.66

Label Answer:
10

Prediction Full:
40/3=13.33????13.33*2=26.66!!!!26.66<|endoftext|>

Label Full:
40/2=20????20/2=10!!!!10
----------------------------------------------------------------------------------------------------

Prediction COT:
12+4+4=20????20/3=6.67

Label COT:
12*2=24????4*1=4????3*4=12????24+4+12=40????12+4+4=20????40/20=2

Prediction Answer:
6.67

Label Answer:
2

Prediction Full:
12+4+4=20????20/3=6.67!!!!6.67<|endoftext|>

Label Full:
12*2=24????4*1=4????3*4=12????24+4+12=40????12+4+4=20????40/20=2!!!!2
----------------------------------------------------------------------------------------------------

Prediction COT:
2.25*2=4.50????3.50*2=7????2*3.50=7.00????4.5+7+7+3.5=20.00????20.00+4.50+1+1=26.50

Label COT:
2*2.25=4.50????2*4=8.00????2*2.50=5.00????4.50+8.00+.50+5.00+3.50+3.50=25.00

Prediction Answer:
26.50

Label Answer:
25

Prediction Full:
2.25*2=4.50????3.50*2=7????2*3.50=7.00????4.5+7+7+3.5=20.00????20.00+4.50+1+1=26.50!!!!26.50<|endoftext|>

Label Full:
2*2.25=4.50????2*4=8.00????2*2.50=5.00????4.50+8.00+.50+5.00+3.50+3.50=25.00!!!!25
----------------------------------------------------------------------------------------------------

Prediction COT:
33/4=8.25

Label COT:
32=32????8=8

Prediction Answer:
8.25

Label Answer:
25

Prediction Full:
33/4=8.25!!!!8.25<|endoftext|>

Label Full:
32=32????8=8!!!!25
----------------------------------------------------------------------------------------------------

In [ ]:
for sample_ind in range(1, 100, 1):
# for sample_ind in range(len(data)):
    print('\nT: ', tokenizer.decode(data['all_labels'][sample_ind]))
    print('P: ', tokenizer.decode(data['all_preds'][sample_ind]))

T:  1.5*2=3????3+2.5=5.5????1.5+3+5.5=10!!!!10
P:  1.5*2=3????3+2.5=5.5????1.5+3+5.5=9!!!!9<|endoftext|>

T:  30/100*2000=600????2000-600=1400!!!!1400
P:  2000*30/100=600????2000-600=1400!!!!1400<|endoftext|>

T:  21/7=3????5*3=15!!!!15
P:  21/7=3????3*5=15!!!!15<|endoftext|>

T:  200*3=600????600*.4=240!!!!240
P:  200*3=600????600*40*.01=240????600+240=840!!!!840<|endoftext|>

T:  1/2*100=50????3/5*50=30????50-30=20!!!!20
P:  100/2=50????50/3/5=10????50-10=40!!!!40<|endoftext|>

T:  40/2=20????20/2=10!!!!10
P:  40/3=13.33????13.33*2=26.66!!!!26.66<|endoftext|>

T:  12*2=24????4*1=4????3*4=12????24+4+12=40????12+4+4=20????40/20=2!!!!2
P:  12+4+4=20????20/3=6.67!!!!6.67<|endoftext|>

T:  2*2.25=4.50????2*4=8.00????2*2.50=5.00????4.50+8.00+.50+5.00+3.50+3.50=25.00!!!!25
P:  2.25*2=4.50????3.50*2=7????2*3.50=7.00????4.5+7+7+3.5=20.00????20.00+4.50+1+1=26.50!!!!26.50<|endoftext|>

T:  32=32????8=8!!!!25
P:  33/4=8.25!!!!8.25<|endoftext|>

T:  14/2=7????15/3=5????2*5=10????14-10=4!!!!4
P:  2+3=5????14-5=9????15-5=10????9+10=19!!!!19<|endoftext|>

T:  98-43=55????55+23=78????73=73????73+7=80!!!!80
P:  98-43=55????55-23=32????32+7=39!!!!39<|endoftext|>

T:  12*10=120????130-120=10!!!!10
P:  12*10=120????130-120=10!!!!10<|endoftext|>

T:  80-20=60????60/2=30????30*3=90????90-10=80!!!!80
P:  80-20=60????60/2=30????30*3=90????90+10=100!!!!100<|endoftext|>

T:  27-7=20????103-27-20=56????56/2=28!!!!28
P:  27-7=20????27+20=47????103-47=56????56/2=28!!!!28<|endoftext|>

T:  102-85=17!!!!20
P:  85-102=73????73-85=-6!!!!-6<|endoftext|>

T:  10+15=25????2*10=20????20+25=45!!!!45
P:  15-10=5????2*15=30????30+5=35!!!!35<|endoftext|>

T:  109-5=104????104*2=208????109*2=218????208+218=426????500-426=74!!!!74
P:  109*2=218????218-5=213????213+10=223????500-223=277!!!!277<|endoftext|>

T:  3*10=30????90*3=270????30*4=120????120+270=390!!!!390
P:  3*20=60????4*60=240????30*1=30????240+30=270!!!!270<|endoftext|>

T:  8*7=56????56-2=54!!!!54
P:  8*7=56????56-2=54!!!!54<|endoftext|>

T:  8*16=128.00????128*5=640.00????2*13.50=27.00????27*5=135.00????640+135=775.00!!!!775
P:  16+2=18????18*8=144????144*5.35=755.2!!!!755.2<|endoftext|>

T:  3+2=5????2+2=4????5*4=20????80/20=4!!!!4
P:  2+3+2+2=9????80/9=8.57????8.57-2=6.57!!!!6.57<|endoftext|>

T:  4*20=80????400/80=5!!!!5
P:  400/20=20!!!!20<|endoftext|>

T:  2+1+3=6????6*8=48????48/16=3!!!!3
P:  16/8=2????2+1+3=6????16-6=10????10/3=3.33!!!!4<|endoftext|>

T:  30000-10000=20000????20000*0.40=8000????20000-8000=12000!!!!12000
P:  30000-10000=20000????20000*0.4=8000!!!!8000<|endoftext|>

T:  800*0.4=320!!!!320
P:  400*0.4=160!!!!160<|endoftext|>

T:  5*6=30????5*7=35????100-35-30=35????35/5=7!!!!7
P:  5*5=25????5*6=30????25+30=55????100-55=45????45/7=6.43!!!!6<|endoftext|>

T:  7+14=21????21+10=31????2*11=22????31+22=53!!!!53
P:  2*11=22????22+10+10+14=56????56+7=63!!!!63<|endoftext|>

T:  1/2*28=14????14+37=51????51-2=49????49+1=50!!!!50
P:  37+28+31=96????96/2=48????48-2=46????96-46=50!!!!50<|endoftext|>

T:  220*1=220????70*2=140????220+140=360!!!!360
P:  220*1=220????70*2=140????220+140=360!!!!360<|endoftext|>

T:  22/2=11????2*13=26????22+13+11+26=72!!!!72
P:  22+13=35????35/2=17.5????17.5*2=35????35*2=70????35+35+70=140!!!!140<|endoftext|>

T:  84*2/3=56????84+56=140????140+10=150????150*8=1200!!!!1200
P:  84*2/3=56????84+56=140????140*8=1120????10*8=80????80*8=640????1120+640=1760!!!!1760<|endoftext|>

T:  90/5=18????18-5-2=11????11*5=55!!!!55
P:  5*5=25????25-90=-65!!!!-65<|endoftext|>

T:  10*5=50????6*128=768????768/50=15.36!!!!15
P:  128/10=12.8????12.8/5=2.56!!!!2.56<|endoftext|>

T:  100*2=200????50*3=150????200+150=350????500-350=150!!!!150
P:  2*100=200????3*50=150????200+150=350????500-350=150!!!!150<|endoftext|>

T:  16/2=8????8*4=32????16+32+8=56!!!!56
P:  16/2=8????8*4=32????32+8+16=56!!!!56<|endoftext|>

T:  60=60????60/3=20????60+20=80!!!!80
P:  30*3=90????90/3=30????30+90+30=150!!!!150<|endoftext|>

T:  45+123=168????168/14=12!!!!12
P:  45+123=168????168/14=12.71!!!!12<|endoftext|>

T:  20/4=5????60-5=55!!!!55
P:  60-20=40????40/4=10!!!!10<|endoftext|>

T:  10-7=3????3*5=15!!!!15
P:  10*5=50????7*5=35????50+35=85!!!!85<|endoftext|>

T:  5*1=5????3*2=6????2*3=6????5+3+2=10????10/5=2????5+6+6=17????17-2=15!!!!15
P:  5*1=5????3*2=6????2*3=6????5+6+6=17????17/5=3.4????17-3=14!!!!14<|endoftext|>

T:  500/50=10????20*10=200????10*.2=2????1000+200+2=1202????20*500=10000????10000-1202=8798!!!!8798
P:  500*20=10000????500*2=1000????10000+1000=11000????1000*20=20000????10000+20000=30000????11000-30000=-45000!!!!-45000<|endoftext|>

T:  25+15+40=80????150-80=70!!!!70
P:  25+15=40????40+40=80????150-80=70!!!!70<|endoftext|>

T:  36*125*.01=45????45*200*.01=90!!!!90
P:  36*125/100=43.00????43+36=79????79*20/100=15.8!!!!15.8<|endoftext|>

T:  4000/50=80????80/10=8!!!!8
P:  50*10=500????4000/500=8!!!!8<|endoftext|>

T:  20=20!!!!146
P:  239/3=79.666666666666664????79.666666666666664-7=62.662.666666666666664*4=27.627.666666666666664-79.66627.67+27.67=55.34!!!!55.34<|endoftext|>

T:  4*2=8????26-8=18????18/3=6!!!!6
P:  26-4=22????22/2=11!!!!11<|endoftext|>

T:  60*0.5=30????120-30=90????1.5-0.5=1!!!!90
P:  120/60=2????2*60=120????120-30=90????90/30=3!!!!3<|endoftext|>

T:  165/11=15????20-15=5????5*11=55????72-55=17!!!!17
P:  20*11=220????220-72=148????148-165=-2!!!!-2<|endoftext|>

T:  8-6=2????8*2=16????16-2=14!!!!14
P:  8+6=14????2*8=16????16-6=10????10-8=2!!!!2<|endoftext|>

T:  6*0.5=3????4*0.5=2????3+2=5!!!!5
P:  4*30=120????6*60=360????120+360=480!!!!480<|endoftext|>

T:  30+25+35=90????90/3=30!!!!30
P:  30+25+35=90????90/3=30!!!!30<|endoftext|>

T:  2*4000=8000????4000+8000=12000!!!!12000
P:  4000/3=1333.33????1333.33*2=2666.66!!!!2667<|endoftext|>

T:  5600*7*.01*2=784????5600+784=6384!!!!6384
P:  5600*7/100=392????5600+392=6092!!!!6092<|endoftext|>

T:  2*5=10????10+3=13!!!!13
P:  3+2=5????5+2=7????7+2=9????9+2=11????3+5+7+9+11=35!!!!35<|endoftext|>

T:  8*2=16????30*16=480!!!!480
P:  30*60=1800????1800*8=14400!!!!14400<|endoftext|>

T:  20-5=15????15*300=4500????300-50=250????250*2=500????4500+500+2000=7000????7000-4000=3000!!!!3000
P:  300*20=6000????300+2*50=550????550*5=2750????6000+2750=8750????8750-6000=2750????2750+2000=4750????4750-4000=750!!!!750<|endoftext|>

T:  4*2=8????8+2=10!!!!10
P:  4*2=8????2+8=10!!!!10<|endoftext|>

T:  45*3=135????135*2=270????135+270+45=450!!!!450
P:  45*3=135????45*3=135????45*2=90????135+135+90=370!!!!370<|endoftext|>

T:  5*60=300????4*50=200????200+45=245????300-245=55!!!!55
P:  4*60=240????240-45=195!!!!195<|endoftext|>

T:  25-2=23????23-4=19????25-19=6!!!!6
P:  25-2=23????23-4=19!!!!19<|endoftext|>

T:  3*10=30????10+12=22????30-22=8!!!!8
P:  12/3=4????4*3=12????12+10=22!!!!22<|endoftext|>

T:  800*.5=400????800+400=1200????1200/1000=1.2????12*.25=3????12+3=15????1.2*50=60????900=900????900/100=9!!!!9
P:  800*0.25=200????800+200=1000????1000/50=20????20*0.12=2.4!!!!2.4<|endoftext|>

T:  2025-20=2005!!!!2000
P:  2025-3=2022????2022-2=2000????2000/2=1000????1000+3=1003!!!!1003<|endoftext|>

T:  9+7=16????11*16=176????1*3=3????3+176=179!!!!179
P:  9*11=99????7*1=7????3*1=3????99+7+3=100!!!!100<|endoftext|>

T:  50*20=1000????1000*10=10000????10000/200=50!!!!50
P:  200*20=4000????50*10=500????4000/500=8????8+4000/10=4080!!!!4080<|endoftext|>

T:  2*.01*2000=40????2000+40=2040!!!!2040
P:  2000*2/100=40????2000+40=2040!!!!2040<|endoftext|>

T:  8*4=32????32/16=2????600/2=300!!!!300
P:  600/4=150????150/8=18.75!!!!19<|endoftext|>

T:  50*500=25000!!!!5000
P:  50*500=25000????25000*0.2=5000!!!!5000<|endoftext|>

T:  5*6=30????30*3=90????90*12=1080!!!!1080
P:  12*6=72????3*6=18????5*6=30????72+18+30=120!!!!120<|endoftext|>

T:  8*18=144.00????10-8=2????18*.5=9.00????18+9=27.00????144*5=720.00????27*2=54.00????720+270=990.00!!!!990
P:  18*8=144????144*5=720????720*1/2=360????720+360=1080!!!!1080<|endoftext|>

T:  20/2=10????300/10=30!!!!30
P:  20/2=10????300/10=30!!!!30<|endoftext|>

T:  50+40=90????10+20=30????90-30=60!!!!60
P:  50+40=90????90-10=80????80/20=4!!!!4<|endoftext|>

T:  30+10=40????90+10=100????40/100=.4????.4*100=40!!!!40
P:  90*2/3=60????90-60=30????30+10=40????40*10=400????400*10/100=40????40*10/100=4!!!!4<|endoftext|>

T:  30+40=70????70+90=160!!!!160
P:  90/4=22.5????22.5-40=-8.5????-8.5*3=-27.5!!!!-27.5<|endoftext|>

T:  20-4=16????2*16=32????32*5=160????160/4=40!!!!40
P:  20*2=40????40*5=200????200*2=400????400*2=800????800*2=1600????1600*2=3200!!!!3200<|endoftext|>

T:  11*4=44????44+2=46????11+2=13????46+13=59!!!!59
P:  11+2=13????13+11=24????4*13=52????52+24=76!!!!76<|endoftext|>

T:  97=97!!!!97
P:  300/3=100????100*2=200!!!!200<|endoftext|>

T:  (180/3)*2=120????180-120=60!!!!60
P:  180*2/3=120????180-120=60!!!!60<|endoftext|>

T:  3*3=9????9*5=45!!!!45
P:  3*5=15????15+3=18????18*5=90!!!!90<|endoftext|>

T:  810/3=270????270/3=90????90/3=30!!!!30
P:  810/3=270????270/3=90????90/3=30????30/3=10????10/3=3.33!!!!3<|endoftext|>

T:  16+10=26????3*16=48????48-24=24????26+24=50!!!!50
P:  16+10=26????26+10=36????36/3=12????36+12=48????48/2=24????48+24=72!!!!72<|endoftext|>

T:  50*2=100????100*2.4=240????240-10=230????50*.6=30????100+230+30=360!!!!360
P:  50*2=100????20/100*100=20????20*2=40????100+40=140????140*2=280????280*60/100=168????280-168=112????112+140=252!!!!252<|endoftext|>

T:  140/7=20!!!!20
P:  28/5=5.6????5.6*7=37.2!!!!37.2<|endoftext|>

T:  50*2=100????20/2=10!!!!180
P:  20/2=10????20+10=30????50-20-30=0????0/2=0!!!!0<|endoftext|>

T:  10*2=20????5*5=25????25*2=50!!!!50
P:  2*10=20????5*5=25????20+25=45????45*2=90!!!!90<|endoftext|>

T:  20/10=2????20/1=20????20-2=18!!!!18
P:  10/1=10????20/10=2!!!!2<|endoftext|>

T:  50+9+121=180????1500-180=1320????1320/6=220!!!!220
P:  50+9+121=186????186*6=1162????1500-1162=338????338/6=56!!!!56<|endoftext|>

T:  60-10=50????50/2=25????25+5=30!!!!30
P:  60-10=50????50/2=25????25-5=20!!!!20<|endoftext|>

T:  !!!!9
P:  99/5=19.8????19.8*10=198????198+9=207!!!!207<|endoftext|>

T:  12*5=60????150*60=9000.00!!!!9000
P:  12*5=60????60*150=9000!!!!9000<|endoftext|>

T:  9*10=90????90*12=1080????1080/18=60!!!!60
P:  9*10=90????90/18=5!!!!5<|endoftext|>

T:  100-10-60=30????100*720/60=1200????1200*30/100=360!!!!360
P:  720*0.10=72????720*0.60=432????720-72-432=300!!!!300<|endoftext|>

T:  2*4=8????4/2=2????24-4-8-2=10!!!!10
P:  24-4=20????2*4=8????20-8=12????12/2=6????12-6=6!!!!6<|endoftext|>

T:  25+35=60????100-60=40!!!!40
P:  25+35=60????100-60=40!!!!40<|endoftext|>

T:  24/2=12????8+12=20????20/2=10????24+10=34!!!!34
P:  24/2=12????12+8=20????20/2=10????20+10=30!!!!30<|endoftext|>

T:  60/5=12????12-3=9!!!!9
P:  60*4/5=48????60-48=12????12*1/5=2.4????12-2.4=9.6????9.6-3=6.6!!!!6.6<|endoftext|>

T:  500/5=100????100/4=25!!!!25
P:  500*20*.01=100????500*4*.01=20????100+20=120!!!!120<|endoftext|>

T:  12/6=2????20/2=10????10+6=16!!!!16
P:  6*12=72????20*6=120????72+120=192!!!!192<|endoftext|>

T:  2*4=8????2*1=2????8+6+2=16????16*10=160!!!!160
P:  2*12=24????2*2=4????2*4=8????24+4+8=36!!!!36<|endoftext|>

In [ ]:
for all_pred, all_label in zip(data['all_preds'], data['all_labels']):
    break
# preds_full = data['all_preds']

In [ ]:
all_pred_text = tokenizer.decode(all_pred)
all_pred_text = all_pred_text[all_pred_text.index(eos)]

TypeError: must be str, not list

In [ ]:
all_pred_text

'12*.5=6????6-4=2????2-2=0????0*365=$0????100-0=100!!!!100<|endoftext|>'

In [ ]:

for lab_tokens, pred_tokens in zip(labels_full, preds_full):
    lab_tokens = [t.item() for t in lab_tokens if t != bos[0]]
    
    
    ans_start_index_l = max(i for i, x in enumerate(lab_tokens) if x == ans[0])
    if ans[0] in pred_tokens:
        ans_start_index_p = max(i for i, x in enumerate(pred_tokens) if x == ans[0])
    else:
        ans_start_index_p = ans_start_index_l
    ans_start_index_p = ans_start_index_l

    pred_cot_tokens = pred_tokens[:ans_start_index_p].tolist()
    lab_cot_tokens = lab_tokens[:ans_start_index_l]

    all_preds_cot.append(pred_cot_tokens)
    all_labels_cot.append(lab_cot_tokens)

    all_preds_ans.append(pred_tokens[ans_start_index_p:].tolist())
    all_labels_ans.append(lab_tokens[ans_start_index_l:])

    all_preds.append(pred_tokens.tolist())
    all_labels.append(lab_tokens)

In [ ]:
rmt.to(device)

RMTForReasoning(
  (rmt): RecurrentWrapperNoSegmentationGenerate(
    (memory_cell): MemoryCell(
      (model): LlamaForCausalLM(
        (model): LlamaModel(
          (embed_tokens): Embedding(49152, 576)
          (layers): ModuleList(
            (0-29): 30 x LlamaDecoderLayer(
              (self_attn): LlamaAttention(
                (q_proj): Linear(in_features=576, out_features=576, bias=False)
                (k_proj): Linear(in_features=576, out_features=192, bias=False)
                (v_proj): Linear(in_features=576, out_features=192, bias=False)
                (o_proj): Linear(in_features=576, out_features=576, bias=False)
              )
              (mlp): LlamaMLP(
                (gate_proj): Linear(in_features=576, out_features=1536, bias=False)
                (up_proj): Linear(in_features=576, out_features=1536, bias=False)
                (down_proj): Linear(in_features=1536, out_features=576, bias=False)
                (act_fn): SiLU()
              )
              (input_layernorm): LlamaRMSNorm((576,), eps=1e-05)
              (post_attention_layernorm): LlamaRMSNorm((576,), eps=1e-05)
            )
          )
          (norm): LlamaRMSNorm((576,), eps=1e-05)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (lm_head): Linear(in_features=576, out_features=49152, bias=False)
      )
    )
  )
)

In [ ]:
batch = [valid_dataset[i] for i in range(32)]
collated = collate_fn(batch)

collated['labels'] = collated['labels'].to(device)
segments = collated['segments']
for i, seg in enumerate(collated['segments']):
    collated['segments'][i] = {k:v.to(device) for k,v in seg.items()}

In [ ]:
rmt.to(torch.bfloat16)

RMTForReasoning(
  (rmt): RecurrentWrapperNoSegmentationGenerate(
    (memory_cell): MemoryCell(
      (model): LlamaForCausalLM(
        (model): LlamaModel(
          (embed_tokens): Embedding(49152, 576)
          (layers): ModuleList(
            (0-29): 30 x LlamaDecoderLayer(
              (self_attn): LlamaAttention(
                (q_proj): Linear(in_features=576, out_features=576, bias=False)
                (k_proj): Linear(in_features=576, out_features=192, bias=False)
                (v_proj): Linear(in_features=576, out_features=192, bias=False)
                (o_proj): Linear(in_features=576, out_features=576, bias=False)
              )
              (mlp): LlamaMLP(
                (gate_proj): Linear(in_features=576, out_features=1536, bias=False)
                (up_proj): Linear(in_features=576, out_features=1536, bias=False)
                (down_proj): Linear(in_features=1536, out_features=576, bias=False)
                (act_fn): SiLU()
              )
              (input_layernorm): LlamaRMSNorm((576,), eps=1e-05)
              (post_attention_layernorm): LlamaRMSNorm((576,), eps=1e-05)
            )
          )
          (norm): LlamaRMSNorm((576,), eps=1e-05)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (lm_head): Linear(in_features=576, out_features=49152, bias=False)
      )
    )
  )
)

In [ ]:
out = rmt(**collated)

OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 79.21 GiB of which 9.19 MiB is free. Process 50711 has 62.65 GiB memory in use. Including non-PyTorch memory, this process has 16.54 GiB memory in use. Of the allocated memory 14.98 GiB is allocated by PyTorch, and 913.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [ ]:
out = rmt(**collated)

In [ ]:
out.loss

tensor(0.3387, device='cuda:0', grad_fn=<DivBackward0>)

In [ ]:
collated['segments'][0]

{'input_ids': tensor([[ 9705,  7554,  6630,  ..., 50256, 50256, 50256],
         [ 9705,    39, 25761,  ..., 50256, 50256, 50256],
         [ 9705,    51, 16956,  ..., 50256, 50256, 50256],
         ...,
         [ 9705,  2437,   881,  ..., 50256, 50256, 50256],
         [ 9705, 33349,   342,  ..., 50256, 50256, 50256],
         [ 9705,    33,  6058,  ..., 50256, 50256, 50256]], device='cuda:0'),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0'),
 'labels_mask': tensor([[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]], device='cuda:0'),
 'labels': tensor([[-100, -100, -100,  ..., -100, -100, -100],
         [-100, -100, -100,  ..., -100, -100, -100],
         [-100, -100, -100,  ..., -100, -100, -100],
         ...,
         [-100, -100, -100,  ..., -100, -100, -100],
         [-100, -100, -100,  ..., -100, -100, -100],
         [-100, -100, -100,  ..., -100, -100, -100]], device='cuda:0')}

In [ ]:
task = collated['segments'][0]
task = {k:v.to(device) for k,v in task.items()}

with torch.no_grad():
    gen_out = rmt.generate([task], max_new_tokens=50, pad_token_id=eos[0])

In [ ]:
len(gen_out)

9

In [ ]:
batch_ind = 0

In [ ]:
i = 0
tokenizer.batch_decode(gen_out[i])[:5]

['2*.5=1????', '1.5*2=', '2000*30/100=', '21/7=3????', '200*3=600????']

In [ ]:
res

{'accuracy_cot': 1.0, 'accuracy_ans': 0.9921875}

In [ ]:

bs = 16
dataset = valid_dataset

all_preds_cot, all_labels_cot = [], []
all_preds_ans, all_labels_ans = [], []

# for start_ind in range(0, 64, bs):
for start_ind in range(0, len(dataset), bs):
    batch = dataset.select(range(start_ind, min(len(dataset), start_ind + bs)))
    collated = collate_fn(batch)
    task = collated['segments'][0]
    task = {k:v.to(device) for k,v in task.items()}

    with torch.no_grad():
        gen_out = rmt.generate([task], max_new_tokens=25, pad_token_id=eos[0])
    

    preds_full = torch.cat(gen_out, dim=1)
    labels = collated['labels']

    labels_masks = labels > 0
    labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

    special_tokens = {ans[0], bos[0]}
    acc_cot, acc_ans = [], []
    for lab_tokens, pred_tokens in zip(labels_full, preds_full):
        lab_tokens = [t.item() for t in lab_tokens if t != bos[0]]
        
        ans_start_index = max(i for i, x in enumerate(lab_tokens) if x == ans[0])

        pred_cot_tokens = pred_tokens[:ans_start_index].tolist()
        lab_cot_tokens = lab_tokens[:ans_start_index]

        all_preds_cot.append(pred_cot_tokens)
        all_labels_cot.append(lab_cot_tokens)

        all_preds_ans.append(pred_tokens[ans_start_index:].tolist())
        all_labels_ans.append(lab_tokens[ans_start_index:])

IndexError: Index 1007 out of range for dataset of size 1000.

In [ ]:
cot_correct = [p == l for p, l in zip(all_preds_cot, all_labels_cot)]
ans_correct = [p == l for p, l in zip(all_preds_ans, all_labels_ans)]
print( {'accuracy_cot': np.mean(cot_correct), 'accuracy_ans': np.mean(ans_correct)})

{'accuracy_cot': 1.0, 'accuracy_ans': 0.998991935483871}

{'accuracy_cot': 1.0, 'accuracy_ans': 1.0}

In [ ]:
all_preds_cot[0] == all_labels_cot[0]

True

In [ ]:
len(all_labels_cot)

64

In [ ]:
acc_cot.append(all(cot_correct))

pred_ans_tokens = pred_tokens[ans_start_index:].tolist()
lab_ans_tokens = lab_tokens[ans_start_index:]

ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens) if l not in special_tokens]
acc_ans.append(all(ans_correct))

In [ ]:
torch.cat(gen_out, dim=1).shape

torch.Size([16, 56])

In [ ]:
collated['labels']

tensor([[ -100,  -100,  -100,  ...,   657,   352, 50256],
        [ -100,  -100,  -100,  ...,   807,   513, 50256],
        [ -100,  -100,  -100,  ...,   767,   718, 50256],
        ...,
        [ -100,  -100,  -100,  ...,   807,   657, 50256],
        [ -100,  -100,  -100,  ...,   642,   352, 50256],
        [ -100,  -100,  -100,  ...,   604,   807, 50256]])

In [ ]:
preds_full = torch.cat(gen_out, dim=1)#[:, 1:]
labels = collated['labels']#[:, 1:]

labels_masks = labels > 0
# preds_full = [p[m] for p, m in zip(preds, labels_masks)]
labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

special_tokens = {ans[0], bos[0]}
acc_cot, acc_ans = [], []
for lab_tokens, pred_tokens in zip(labels_full, preds_full):
    lab_tokens = [t for t in lab_tokens if t != bos[0]]
    
    ans_start_index = max(i for i, x in enumerate(lab_tokens) if x == ans[0])

    pred_cot_tokens = pred_tokens[:ans_start_index].tolist()
    lab_cot_tokens = lab_tokens[:ans_start_index]

    cot_correct = [p == l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l not in special_tokens]
    acc_cot.append(all(cot_correct))

    pred_ans_tokens = pred_tokens[ans_start_index:].tolist()
    lab_ans_tokens = lab_tokens[ans_start_index:]

    ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens) if l not in special_tokens]
    acc_ans.append(all(ans_correct))

print( {'accuracy_cot': np.mean(acc_cot), 'accuracy_ans': np.mean(acc_ans)})

{'accuracy_cot': 1.0, 'accuracy_ans': 1.0}

In [ ]:
tokenizer.decode(pred_cot_tokens)

'6 1 2 8 1????0 8 4 6 4 5 ( 6 9 6 4 6 5 )????0 0 6 1 2 8 1 ( 6 9 2 6 8 3 2 )????0 0 0 2 7 9 1 8'

In [ ]:
tokenizer.decode(lab_cot_tokens)

'6 1 2 8 1????0 8 4 6 4 5 ( 6 9 6 4 6 5 )????0 0 6 1 2 8 1 ( 6 9 2 6 8 3 2 )????0 0 0 2 7 9 1 8'

In [ ]:
tokenizer.batch_decode(preds_full)

['6',
 ' 1',
 ' 2',
 ' 8',
 ' 1',
 '????',
 '0',
 ' 8',
 ' 4',
 ' 6',
 ' 4',
 ' 5',
 ' (',
 ' 6',
 ' 9',
 ' 6',
 ' 4',
 ' 6',
 ' 5',
 ' )',
 '????',
 '0',
 ' 0',
 ' 6',
 ' 1',
 ' 2',
 ' 8',
 ' 1',
 ' (',
 ' 6',
 ' 9',
 ' 2',
 ' 6',
 ' 8',
 ' 3',
 ' 2',
 ' )',
 '????',
 '0',
 ' 0',
 ' 0',
 ' 2',
 ' 7',
 ' 9',
 ' 1',
 ' 8',
 '!!!!',
 '6',
 ' 9',
 ' 2']

In [ ]:

tokenizer.batch_decode(labels_full)

['////5 5 5 6 1????////0 0 6 4 9 0 ( 5 5 1 1 1 1 )????////0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????////0 0 0 0 6 4 9 0!!!!////5 5 6 0 8 2 0 1<|endoftext|>',
 '////6 7 1 1 3????////0 4 8 7 0 2 ( 6 1 0 9 3 2 )????////0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )????////0 0 0 2 7 3 6 3!!!!////6 1 4 9 8 6 8 3<|endoftext|>',
 '////8 0 0 5 7????////0 4 8 3 4 8 ( 8 4 8 8 1 9 )????////0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 )????////0 0 0 2 3 6 5 6!!!!////8 4 4 8 8 4 7 6<|endoftext|>',
 '////9 0 9 2 1????////0 2 1 2 7 1 ( 9 2 0 5 8 1 )????////0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 )????////0 0 0 5 1 5 1 2!!!!////9 2 8 1 8 2 4 2<|endoftext|>',
 '////0 4 6 8 5????////0 0 5 6 6 3 ( 0 4 1 5 2 4 )????////0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 )????////0 0 0 0 5 6 6 3!!!!////0 4 1 3 7 4 1 4<|endoftext|>',
 '////2 5 2 4 2????////0 9 8 1 8 1 ( 2 4 1 6 0 2 )????////0 0 4 0 5 8 4 ( 2 4 5 6 5 0 5 )????////0 0 0 1 4 4 2 4!!!!////2 4 5 7 9 4 7 4<|endoftext|>',
 '////8 4 7 9 0????////0 6 6 8 3 4 ( 8 0 4 8 4 4 )????////0 0 4 7 8 4 0 ( 8 0 8 5 3 9 0 )????////0 0 0 4 4 2 9 2!!!!////8 0 8 9 7 1 0 3<|endoftext|>',
 '////0 0 0 0 0????////0 0 6 4 8 0 ( 0 0 6 4 8 0 )????////0 0 2 9 6 1 0 ( 0 0 8 3 5 2 0 )????////0 0 0 8 2 2 5 1!!!!////0 0 8 1 8 4 5 1<|endoftext|>',
 '////5 5 5 2 2????////0 6 6 0 7 2 ( 5 1 2 3 9 2 )????////0 0 0 0 0 0 0 ( 5 1 2 3 9 2 0 )????////0 0 0 5 5 5 2 2!!!!////5 1 2 8 4 8 2 2<|endoftext|>',
 '////0 0 0 0 0????////0 7 3 9 5 3 ( 0 7 3 9 5 3 )????////0 0 9 7 9 1 1 ( 0 7 2 7 5 5 1 )????////0 0 0 9 7 9 1 1!!!!////0 7 2 6 3 5 3 1<|endoftext|>',
 '////5 6 8 3 0????////0 0 6 4 5 1 ( 5 6 4 8 5 1 )????////0 0 5 8 7 4 3 ( 5 6 9 6 3 6 3 )????////0 0 0 5 5 0 7 2!!!!////5 6 9 1 9 6 0 3<|endoftext|>',
 '////4 8 1 4 5????////0 5 6 8 3 3 ( 4 3 8 2 9 3 )????////0 0 5 6 8 3 3 ( 4 3 3 9 7 7 3 )????////0 0 0 6 4 5 3 1!!!!////4 3 3 5 2 3 7 1<|endoftext|>',
 '////4 4 8 9 0????////0 9 4 1 2 2 ( 4 3 3 1 3 2 )????////0 0 8 8 6 9 1 ( 4 3 1 0 0 2 2 )????////0 0 0 2 2 9 4 0!!!!////4 3 1 2 2 1 7 0<|endoftext|>',
 '////6 5 6 7 3????////0 2 3 9 3 4 ( 6 7 9 6 7 4 )????////0 0 2 5 5 2 1 ( 6 7 1 2 3 7 1 )????////0 0 0 6 7 2 6 0!!!!////6 7 1 8 0 0 8 0<|endoftext|>',
 '////0 2 3 1 1????////0 0 0 3 8 2 ( 0 2 3 4 9 2 )????////0 0 0 6 9 3 3 ( 0 2 3 0 9 6 3 )????////0 0 0 0 2 3 1 1!!!!////0 2 3 0 1 0 5 1<|endoftext|>',
 '////6 1 2 8 1????////0 8 4 6 4 5 ( 6 9 6 4 6 5 )????////0 0 6 1 2 8 1 ( 6 9 2 6 8 3 2 )????////0 0 0 2 7 9 1 8!!!!////6 9 2 8 5 3 4 8<|endoftext|>']

In [ ]:

def compute_accuracy(eval_pred):
    preds = eval_pred.predictions.argmax(axis=-1)[:, :-1]
    labels = eval_pred.label_ids[:, 1:]

    labels_masks = labels > 0
    preds_full = [p[m] for p, m in zip(preds, labels_masks)]
    labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

    special_tokens = {ans[0], bos[0]}
    acc_cot, acc_ans = [], []
    for lab_tokens, pred_tokens in zip(labels_full, preds_full):
        ans_start_index = max(i for i, x in enumerate(lab_tokens) if x == ans[0])

        pred_cot_tokens = pred_tokens[:ans_start_index].tolist()
        lab_cot_tokens = lab_tokens[:ans_start_index].tolist()

        cot_correct = [p == l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l not in special_tokens]
        acc_cot.append(all(cot_correct))

        pred_ans_tokens = pred_tokens[ans_start_index:].tolist()
        lab_ans_tokens = lab_tokens[ans_start_index:].tolist()

        ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens) if l not in special_tokens]
        acc_ans.append(all(ans_correct))

    return {'accuracy_cot': np.mean(acc_cot), 'accuracy_ans': np.mean(acc_ans)}

In [ ]:

# collated = collate_fn([sample for sample in valid_dataset.select(range(128))])
collated = collate_fn([sample for sample in train_dataset.select(range(16))])

In [ ]:
segments = collated['segments']

In [ ]:
# tokenizer.batch_decode(segments[1]['input_ids'])

In [ ]:
for i in range(len(segments)):
    print(segments[i]['input_ids'].shape, segments[i]['labels'].shape)

torch.Size([16, 11]) torch.Size([16, 11])
torch.Size([16, 7]) torch.Size([16, 7])
torch.Size([16, 16]) torch.Size([16, 16])
torch.Size([16, 18]) torch.Size([16, 18])
torch.Size([16, 10]) torch.Size([16, 10])
torch.Size([16, 10]) torch.Size([16, 10])

In [ ]:
# out = rmt(**collated)
self = rmt
segments = collated['segments']

memory_state = None

cell_outputs = []
for seg_num, segment in enumerate(segments):
    cell_out, memory_state = self.memory_cell(input_ids=segment['input_ids'],
                                                attention_mask=segment['attention_mask'],
                                                # labels=segment['input_ids'],

                                                memory_state=memory_state, 
                                                output_hidden_states=True)
    cell_outputs.append(cell_out)
    self.manage_gradients(memory_state, seg_num)

# out = self.process_outputs(cell_outputs, segments,
#                             output_attentions=output_attentions,
#                             output_hidden_states=output_hidden_states)

In [ ]:
out = dict()
from torch.nn import CrossEntropyLoss
self = rmt
kwargs = {}

proxy_out = {}
for seg_num, segment in enumerate(segments):
    cell_out = cell_outputs[seg_num]

    full_logits = cell_out.logits

    labels = segment.get('labels')
    if labels is not None:
        shift_labels = labels[..., 1:].contiguous()
        shift_logits = full_logits[..., :-1, :].contiguous()
        flat_labels = shift_labels.view(-1)
        flat_logits = shift_logits.view(-1, shift_logits.size(-1))

        loss_fct = CrossEntropyLoss()
        labels_mask = segment.get('labels_mask')
        if labels_mask is not None:
            shift_mask = labels_mask[..., :-1].contiguous()

            flat_labels = flat_labels[shift_mask.view(-1)]
            flat_logits = flat_logits[shift_mask.view(-1)]

            if labels_mask.sum() == 0:
                loss_value = 0
            else:
                loss_value = loss_fct(flat_logits, flat_labels)

        proxy_out[f'loss_{seg_num}'] = loss_value
    else:
        proxy_out[f'loss_{seg_num}'] = 0

    segment_keys = ['loss']
    if kwargs.get('output_attentions'):
        segment_keys.append('attentions')
    if kwargs.get('output_hidden_states'):
        segment_keys.append('hidden_states')

    for key, value in cell_out.items():
        if any([sk in key for sk in segment_keys]):
            proxy_out[f'{key}_{seg_num}'] = value

num_segments = len(segments)
out['loss'] = sum([proxy_out[f'loss_{seg_num}'] for seg_num in range(num_segments)]) / num_segments
out['logits'] = torch.cat([cell_out.logits for cell_out in cell_outputs], dim=1)

In [ ]:
for k, v in proxy_out.items():
    print(k, v.item() if isinstance(v, torch.Tensor) else v)

loss_0 0
loss_1 9.379081166116521e-05
loss_2 0.0001396716688759625
loss_3 0.00016610838065389544
loss_4 0.0001877214090200141
loss_5 0.00045566188055090606

In [ ]:
valid_dataset[0]

{'task': '5 6 3 2 * 7 4 3 4',
 'labels': '5 5 6 0 8 2 0 1',
 'cot': '5 5 5 6 1 + 0 0 6 4 9 0 ( 5 5 1 1 1 1 ) + 0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 ) + 0 0 0 0 6 4 9 0'}

In [ ]:

def compute_accuracy(eval_pred):
    preds = eval_pred.predictions.argmax(axis=-1)[:, :-1]
    labels = eval_pred.label_ids[:, 1:]

    labels_masks = labels > 0
    preds_full = [p[m] for p, m in zip(preds, labels_masks)]
    labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

    special_tokens = {ans[0], bos[0]}
    acc_cot, acc_ans = [], []
    for lab_tokens, pred_tokens in zip(labels_full, preds_full):
        ans_start_index = max(i for i, x in enumerate(lab_tokens) if x == ans[0])

        pred_cot_tokens = pred_tokens[:ans_start_index].tolist()
        lab_cot_tokens = lab_tokens[:ans_start_index].tolist()

        cot_correct = [p == l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l not in special_tokens]
        acc_cot.append(all(cot_correct))

        pred_ans_tokens = pred_tokens[ans_start_index:].tolist()
        lab_ans_tokens = lab_tokens[ans_start_index:].tolist()

        ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens) if l not in special_tokens]
        acc_ans.append(all(ans_correct))

    return {'accuracy_cot': np.mean(acc_cot), 'accuracy_ans': np.mean(acc_ans)}

In [ ]:
special_tokens = {ans[0], bos[0]}

In [ ]:
tokenizer.decode([p for p, l in zip(pred_ans_tokens, lab_ans_tokens) if l not in special_tokens])

NameError: name 'pred_ans_tokens' is not defined

In [ ]:
tokenizer.decode([l for p, l in zip(pred_ans_tokens, lab_ans_tokens) if l not in special_tokens])

'9 1 0 3 0 8 6 0<|endoftext|>'

In [ ]:
tokenizer.decode([l for p, l in zip(pred_ans_tokens, lab_ans_tokens)])

'!!!!////9 1 0 3 0 8 6 0<|endoftext|>'

In [ ]:
tokenizer.decode([p for p, l in zip(pred_ans_tokens, lab_ans_tokens)])

'!!!! 69 1 0 3 2 8 6 0<|endoftext|>'

In [ ]:
eval_pred = Holder()

eval_pred.predictions = out['logits']
eval_pred.label_ids = collated['labels']

In [ ]:
acc = compute_accuracy(eval_pred)
print(acc)

{'accuracy_cot': 1.0, 'accuracy_ans': 1.0}

In [ ]:
preds = eval_pred.predictions.argmax(axis=-1)[:, :-1]
labels = eval_pred.label_ids[:, 1:]

labels_masks = labels > 0
preds_full = [p[m] for p, m in zip(preds, labels_masks)]
labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

acc_cot, acc_ans = [], []
correct_samples = []
for lab_tokens, pred_tokens in zip(labels_full, preds_full):
    ans_start_index = max(i for i, x in enumerate(lab_tokens) if x == ans[0])

    pred_cot_tokens = pred_tokens[:ans_start_index].tolist()
    lab_cot_tokens = lab_tokens[:ans_start_index].tolist()

    cot_correct = [p == l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l != bos[0]]
    acc_cot.append(all(cot_correct))

    pred_ans_tokens = pred_tokens[ans_start_index:].tolist()
    lab_ans_tokens = lab_tokens[ans_start_index:].tolist()

    # ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens)]
    ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens) if l not in special_tokens]
    acc_ans.append(all(ans_correct))
    if all(ans_correct):
        correct_samples.append(lab_tokens)
    # break

In [ ]:
tokenizer.batch_decode(correct_samples)

['////1 9 7 9 1????////0 0 0 0 0 0 ( 1 9 7 9 1 0 )????////0 0 9 9 1 2 0 ( 1 9 6 9 3 2 0 )????////0 0 0 3 9 3 5 1!!!!////1 9 6 2 3 6 5 1<|endoftext|>',
 '////4 7 3 4 0????////0 2 2 1 3 1 ( 4 9 5 5 3 1 )????////0 0 8 4 7 8 0 ( 4 9 3 0 1 0 1 )????////0 0 0 8 4 7 8 0!!!!////4 9 3 8 5 7 9 0<|endoftext|>',
 '////0 0 2 6 2????////0 0 5 5 6 0 ( 0 0 7 1 9 0 )????////0 0 0 0 2 6 2 ( 0 0 7 1 1 7 2 )????////0 0 0 0 0 2 6 2!!!!////0 0 7 1 1 9 8 2<|endoftext|>',
 '////9 3 1 1 4????////0 2 4 1 9 0 ( 9 5 5 2 3 1 )????////0 0 3 1 7 3 1 ( 9 5 8 3 0 5 1 )????////0 0 0 5 5 8 2 2!!!!////9 5 8 8 5 3 4 2<|endoftext|>',
 '////5 4 9 7 4????////0 2 1 7 6 7 ( 5 6 0 5 1 8 )????////0 0 6 5 3 8 3 ( 5 6 6 0 5 6 4 )????////0 0 0 2 1 7 6 7!!!!////5 6 6 2 6 3 1 8<|endoftext|>',
 '////8 4 6 3 5????////0 2 1 4 3 1 ( 8 6 7 7 8 1 )????////0 0 8 1 1 0 2 ( 8 6 5 9 9 1 2 )????////0 0 0 4 5 3 0 6!!!!////8 6 5 3 5 5 2 6<|endoftext|>',
 '////6 1 2 9 0????////0 0 2 5 1 1 ( 6 1 4 4 2 1 )????////0 0 0 0 0 0 0 ( 6 1 4 4 2 1 0 )????////0 0 0 6 1 2 9 0!!!!////6 1 4 0 4 3 9 0<|endoftext|>',
 '////0 0 0 0 0????////0 8 1 5 6 0 ( 0 8 1 5 6 0 )????////0 0 2 7 0 6 2 ( 0 8 3 2 7 6 2 )????////0 0 0 7 7 7 9 0!!!!////0 8 3 9 4 4 2 1<|endoftext|>']

In [ ]:
tokenizer.batch_decode(labels_full[:5])

['////5 5 5 6 1????////0 0 6 4 9 0 ( 5 5 1 1 1 1 )????////0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????////0 0 0 0 6 4 9 0!!!!////5 5 6 0 8 2 0 1<|endoftext|>',
 '////6 7 1 1 3????////0 4 8 7 0 2 ( 6 1 0 9 3 2 )????////0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )????////0 0 0 2 7 3 6 3!!!!////6 1 4 9 8 6 8 3<|endoftext|>',
 '////8 0 0 5 7????////0 4 8 3 4 8 ( 8 4 8 8 1 9 )????////0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 )????////0 0 0 2 3 6 5 6!!!!////8 4 4 8 8 4 7 6<|endoftext|>',
 '////9 0 9 2 1????////0 2 1 2 7 1 ( 9 2 0 5 8 1 )????////0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 )????////0 0 0 5 1 5 1 2!!!!////9 2 8 1 8 2 4 2<|endoftext|>',
 '////0 4 6 8 5????////0 0 5 6 6 3 ( 0 4 1 5 2 4 )????////0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 )????////0 0 0 0 5 6 6 3!!!!////0 4 1 3 7 4 1 4<|endoftext|>']

In [ ]:
tokenizer.batch_decode(preds_full[:5])

[' ty5 5 5 6 1????????0 0 6 4 9 0 ( 5 5 1 1 1 1 )????????0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????????0 0 0 0 6 4 9 0!!!! 05 5 6 0 1 2 0 1<|endoftext|>',
 ' deposit6 7 1 1 3????????0 4 8 7 0 2 ( 6 1 0 9 3 2 )????????0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )????????0 0 0 2 7 3 6 3!!!! 26 1 4 9 5 6 8 3<|endoftext|>',
 ' Bild8 0 0 5 7????????0 4 8 3 4 8 ( 8 4 8 8 1 9 )????????0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 )????????0 0 0 2 3 6 5 6!!!! 28 4 4 8 5 4 7 6<|endoftext|>',
 ' Hein9 0 9 2 1????????0 2 1 2 7 1 ( 9 2 0 5 8 1 )????????0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 )????????0 0 0 5 1 5 1 2!!!! 59 2 8 1 3 2 4 2<|endoftext|>',
 ' fragrance0 4 6 8 5????????0 0 5 6 6 3 ( 0 4 1 5 2 4 )????????0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 )????????0 0 0 0 5 6 6 3!!!! 00 4 1 3 9 4 1 4<|endoftext|>']

In [ ]:
tokenizer.decode(labels_full[0])

'////5 5 5 6 1????////0 0 6 4 9 0 ( 5 5 1 1 1 1 )????////0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????////0 0 0 0 6 4 9 0!!!!////5 5 6 0 8 2 0 1<|endoftext|>'

In [ ]:
tokenizer.decode(lab_tokens)

'////9 9 0 9 0????////0 2 3 1 2 1 ( 9 1 4 0 3 1 )????////0 0 6 6 0 6 0 ( 9 1 0 7 3 7 0 )????////0 0 0 6 6 0 6 0!!!!////9 1 0 3 0 8 6 0<|endoftext|>'

In [ ]:
tokenizer.decode(ans[0])

'!!!!'

In [ ]:
ans_start_index

50

In [ ]:
tokenizer.batch_decode(preds_full[:5])

[' ty5 5 5 6 1????????0 0 6 4 9 0 ( 5 5 1 1 1 1 )????????0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????????0 0 0 0 6 4 9 0!!!! 05 5 6 0 1 2 0 1<|endoftext|>',
 ' deposit6 7 1 1 3????????0 4 8 7 0 2 ( 6 1 0 9 3 2 )????????0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )????????0 0 0 2 7 3 6 3!!!! 26 1 4 9 5 6 8 3<|endoftext|>',
 ' Bild8 0 0 5 7????????0 4 8 3 4 8 ( 8 4 8 8 1 9 )????????0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 )????????0 0 0 2 3 6 5 6!!!! 28 4 4 8 5 4 7 6<|endoftext|>',
 ' Hein9 0 9 2 1????????0 2 1 2 7 1 ( 9 2 0 5 8 1 )????????0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 )????????0 0 0 5 1 5 1 2!!!! 59 2 8 1 3 2 4 2<|endoftext|>',
 ' fragrance0 4 6 8 5????????0 0 5 6 6 3 ( 0 4 1 5 2 4 )????????0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 )????????0 0 0 0 5 6 6 3!!!! 00 4 1 3 9 4 1 4<|endoftext|>']

In [ ]:
tokenizer.batch_decode(labels_full[:5])

['////5 5 5 6 1????////0 0 6 4 9 0 ( 5 5 1 1 1 1 )????////0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????////0 0 0 0 6 4 9 0!!!!////5 5 6 0 8 2 0 1<|endoftext|>',
 '////6 7 1 1 3????////0 4 8 7 0 2 ( 6 1 0 9 3 2 )????////0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )????////0 0 0 2 7 3 6 3!!!!////6 1 4 9 8 6 8 3<|endoftext|>',
 '////8 0 0 5 7????////0 4 8 3 4 8 ( 8 4 8 8 1 9 )????////0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 )????////0 0 0 2 3 6 5 6!!!!////8 4 4 8 8 4 7 6<|endoftext|>',
 '////9 0 9 2 1????////0 2 1 2 7 1 ( 9 2 0 5 8 1 )????////0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 )????////0 0 0 5 1 5 1 2!!!!////9 2 8 1 8 2 4 2<|endoftext|>',
 '////0 4 6 8 5????////0 0 5 6 6 3 ( 0 4 1 5 2 4 )????////0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 )????////0 0 0 0 5 6 6 3!!!!////0 4 1 3 7 4 1 4<|endoftext|>']

In [ ]:
tokenizer.batch_decode([s[-9:] for s in preds_full[:5]])

['5 5 6 0 1 2 0 1<|endoftext|>',
 '6 1 4 9 5 6 8 3<|endoftext|>',
 '8 4 4 8 5 4 7 6<|endoftext|>',
 '9 2 8 1 3 2 4 2<|endoftext|>',
 '0 4 1 3 9 4 1 4<|endoftext|>']

In [ ]:
tokenizer.batch_decode([s[-9:] for s in labels_full[:5]])

['5 5 6 0 8 2 0 1<|endoftext|>',
 '6 1 4 9 8 6 8 3<|endoftext|>',
 '8 4 4 8 8 4 7 6<|endoftext|>',
 '9 2 8 1 8 2 4 2<|endoftext|>',
 '0 4 1 3 7 4 1 4<|endoftext|>']

In [ ]:
tokenizer.decode([p for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l != bos[0]])

'9 9 0 9 0????0 2 3 1 2 1 ( 9 1 4 0 3 1 )????0 0 6 6 0 6 0 ( 9 1 0 7 3 7 0 )????0 0 0 6 6 0 6 0'

In [ ]:
tokenizer.decode([l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l != bos[0]])

'9 9 0 9 0????0 2 3 1 2 1 ( 9 1 4 0 3 1 )????0 0 6 6 0 6 0 ( 9 1 0 7 3 7 0 )????0 0 0 6 6 0 6 0'

In [ ]:
cot_correct

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [ ]:
# np.mean([value.item() if isinstance(value, torch.Tensor) else value  for value in proxy_out.values()])

In [ ]:
cell_outputs[0].keys()

odict_keys(['logits', 'hidden_states'])

In [ ]:
si = 1

In [ ]:
# inputs
for seg in segments[:]:
    print(tokenizer.decode(seg['input_ids'][si]))

////6 9 1 5 * 6 4 4 7????
////6 7 1 1 3????
////0 4 8 7 0 2 ( 6 1 0 9 3 2 )????
////0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )????
////0 0 0 2 7 3 6 3!!!!
////6 1 4 9 8 6 8 3<|endoftext|>

In [ ]:
# predictions
[tokenizer.decode(o.logits.argmax(dim=-1)[si]) for o in cell_outputs]

['robees buttons 2 4 5- 2 dunk wellnesspard',
 '6 7 1 1 3????????',
 '0 4 8 7 0 2 ( 6 1 0 9 3 2 )???? 9',
 '0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )???? 7',
 '0 0 0 2 7 3 6 3!!!!!!!!',
 '6 1 4 9 1 6 8 3<|endoftext|><|endoftext|>']

In [ ]:
def compute_accuracy(eval_pred):
    preds = eval_pred.predictions.argmax(axis=-1)[:, :-1]
    labels = eval_pred.label_ids[:, 1:]

    labels_masks = labels > 0
    preds_full = [p[m] for p, m in zip(preds, labels_masks)]
    labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

    special_tokens = {ans[0], bos[0]}
    acc_cot, acc_ans = [], []
    for lab_tokens, pred_tokens in zip(labels_full, preds_full):
        ans_start_index = max(i for i, x in enumerate(lab_tokens) if x == ans[0])

        pred_cot_tokens = pred_tokens[:ans_start_index].tolist()
        lab_cot_tokens = lab_tokens[:ans_start_index].tolist()

        cot_correct = [p == l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l not in special_tokens]
        acc_cot.append(all(cot_correct))

        pred_ans_tokens = pred_tokens[ans_start_index:].tolist()
        lab_ans_tokens = lab_tokens[ans_start_index:].tolist()

        ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens)]
        acc_ans.append(all(ans_correct))

    return {'accuracy_cot': np.mean(acc_cot), 'accuracy_ans': np.mean(acc_ans)}

tensor([[ -100,  -100,  -100,  ...,   657,   352, 50256],
        [ -100,  -100,  -100,  ...,   807,   513, 50256],
        [ -100,  -100,  -100,  ...,   767,   718, 50256],
        ...,
        [ -100,  -100,  -100,  ...,   807,   657, 50256],
        [ -100,  -100,  -100,  ...,   642,   352, 50256],
        [ -100,  -100,  -100,  ...,   604,   807, 50256]])

In [ ]:
preds = out['logits'].argmax(axis=-1)[:, :-1]
labels = collated['labels'][:, 1:]
labels_masks = labels > 0

In [ ]:
preds_full = [p[m] for p, m in zip(preds, labels_masks)]
labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

print(len(preds_full), len(labels_full))

preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

16 16

In [ ]:
think

[9805]

In [ ]:
preds_full[0]

AttributeError: 'Tensor' object has no attribute 'find'

In [ ]:
def get_ans(tensor):
    tokens = tensor.tolist()
    
    try:
        start_index = max(i for i, x in enumerate(tokens) if x == ans[0])
    except ValueError:
        return []
    
    tokens = tokens[start_index + 1:]
    
    if tokens and tokens[0] == bos[0]:
        tokens = tokens[1:]
    
    return torch.tensor(tokens)

def get_cot(tensor)

In [ ]:
tokens = labels_full[0].tolist()

ans_start_index = max(i for i, x in enumerate(tokens) if x == ans[0])

In [ ]:
lab_tokens = labels_full[0]
pred_tokens = preds_full[0]

special_tokens = {ans[0], bos[0]}
pred_cot_tokens = pred_tokens[:ans_start_index].tolist()
lab_cot_tokens = lab_tokens[:ans_start_index].tolist()

cot_correct = [p == l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l not in special_tokens]

pred_ans_tokens = pred_tokens[ans_start_index:].tolist()
lab_ans_tokens = lab_tokens[ans_start_index:].tolist()

ans_correct = [p == l for p, l in zip(pred_ans_tokens, lab_ans_tokens)]

In [ ]:
np.mean(cot_correct)

1.0

In [ ]:
np.mean(ans_correct)

0.8181818181818182

In [ ]:
tokenizer.decode(pred_tokens)

' 45 5 5 6 1????????0 0 6 4 9 0 ( 5 5 1 1 1 1 )????????0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )???? 00 0 0 0 6 4 9 0!!!!!!!!5 5 6 0 7 2 0 1<|endoftext|>'

In [ ]:
# preds
tokenizer.decode([p for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l not in special_tokens])

'5 5 5 6 1????0 0 6 4 9 0 ( 5 5 1 1 1 1 )????0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????0 0 0 0 6 4 9 0'

In [ ]:
# labels
tokenizer.decode([l for p, l in zip(pred_cot_tokens, lab_cot_tokens) if l not in special_tokens])

'5 5 5 6 1????0 0 6 4 9 0 ( 5 5 1 1 1 1 )????0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????0 0 0 0 6 4 9 0'

In [ ]:
[l for l in lab_cot_tokens if l not in special_tokens]

[9805, 9805, 9805]

In [ ]:
think[0]

9805

In [ ]:
pred_cot_tokens.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
len(cot_correct)

47

In [ ]:
# tokens

In [ ]:
len(get_ans(preds_full[0])), len(get_ans(labels_full[0])),

(9, 9)

In [ ]:
tokenizer.decode(get_ans(preds_full[0]))

'5 5 6 0 7 2 0 1<|endoftext|>'

In [ ]:
tokenizer.decode(get_ans(labels_full[0]))

'5 5 6 0 8 2 0 1<|endoftext|>'

In [ ]:
def get_ans(text):
    splits = text.split(ans_text)
    splits = list(filter(len, splits))
    ans = splits[-1].strip()
    if ans.startswith(ans_text):
        ans = ans[len(ans_text):]
    if ans.startswith(bos_text):
        ans = ans[len(bos_text):]
    return ans

In [ ]:
get_ans(preds_full_text[0]), get_ans(labels_full_text[0])

('5 5 6 0 7 2 0 1<|endoftext|>', '5 5 6 0 8 2 0 1<|endoftext|>')

In [ ]:
preds_full_text[0].split(ans_text)

[' 45 5 5 6 1????????0 0 6 4 9 0 ( 5 5 1 1 1 1 )????????0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )???? 00 0 0 0 6 4 9 0',
 '',
 '5 5 6 0 7 2 0 1<|endoftext|>']

In [ ]:
labels_full_text[0].split(ans_text)

['////5 5 5 6 1????////0 0 6 4 9 0 ( 5 5 1 1 1 1 )????////0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????////0 0 0 0 6 4 9 0',
 '////5 5 6 0 8 2 0 1<|endoftext|>']

In [ ]:
preds_full_text

[' 45 5 5 6 1????????0 0 6 4 9 0 ( 5 5 1 1 1 1 )????????0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )???? 00 0 0 0 6 4 9 0!!!!!!!!5 5 6 0 7 2 0 1<|endoftext|>',
 'pard6 7 1 1 3????????0 4 8 7 0 2 ( 6 1 0 9 3 2 )???? 90 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )???? 70 0 0 2 7 3 6 3!!!!!!!!6 1 4 9 1 6 8 3<|endoftext|>',
 ' Doe8 0 0 5 7????????0 4 8 3 4 8 ( 8 4 8 8 1 9 )????????0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 )???? 60 0 0 2 3 6 5 6!!!!!!!!8 4 4 8 1 4 7 6<|endoftext|>',
 ' Gentleman9 0 9 2 1????????0 2 1 2 7 1 ( 9 2 0 5 8 1 )???? 50 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 )???? 60 0 0 5 1 5 1 2!!!!!!!!9 2 8 1 0 2 4 2<|endoftext|>',
 ' drum0 4 6 8 5????????0 0 5 6 6 3 ( 0 4 1 5 2 4 )???? 50 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 )???? 30 0 0 0 5 6 6 3!!!!!!!!0 4 1 3 9 4 1 4<|endoftext|>',
 ' 42 5 2 4 2????????0 9 8 1 8 1 ( 2 4 1 6 0 2 )???? 60 0 4 0 5 8 4 ( 2 4 5 6 5 0 5 )???? 60 0 0 1 4 4 2 4!!!!!!!!2 4 5 7 1 4 7 4<|endoftext|>',
 'hovah8 4 7 9 0????????0 6 6 8 3 4 ( 8 0 4 8 4 4 )???? 80 0 4 7 8 4 0 ( 8 0 8 5 3 9 0 )???? 50 0 0 4 4 2 9 2!!!!!!!!8 0 8 9 9 1 0 3<|endoftext|>',
 ' ass0 0 0 0 0????????0 0 6 4 8 0 ( 0 0 6 4 8 0 )????????0 0 2 9 6 1 0 ( 0 0 8 3 5 2 0 )???? 30 0 0 8 2 2 5 1!!!!!!!!0 0 8 1 0 4 5 1<|endoftext|>',
 ' grilled5 5 5 2 2????????0 6 6 0 7 2 ( 5 1 2 3 9 2 )???? 30 0 0 0 0 0 0 ( 5 1 2 3 9 2 0 )???? 30 0 0 5 5 5 2 2!!!! 55 1 2 8 3 8 2 2<|endoftext|>',
 ' tam0 0 0 0 0????????0 7 3 9 5 3 ( 0 7 3 9 5 3 )????90 0 9 7 9 1 1 ( 0 7 2 7 5 5 1 )???? 70 0 0 9 7 9 1 1!!!!!!!!0 7 2 6 3 5 3 1<|endoftext|>',
 ' 35 6 8 3 0????????0 0 6 4 5 1 ( 5 6 4 8 5 1 )???? 80 0 5 8 7 4 3 ( 5 6 9 6 3 6 3 )???? 60 0 0 5 5 0 7 2!!!!!!!!5 6 9 1 0 6 0 3<|endoftext|>',
 ' 84 8 1 4 5????????0 5 6 8 3 3 ( 4 3 8 2 9 3 )???? 20 0 5 6 8 3 3 ( 4 3 3 9 7 7 3 )???? 90 0 0 6 4 5 3 1!!!!!!!!4 3 3 5 0 3 7 1<|endoftext|>',
 'eal4 4 8 9 0????????0 9 4 1 2 2 ( 4 3 3 1 3 2 )???? 10 0 8 8 6 9 1 ( 4 3 1 0 0 2 2 )???? 00 0 0 2 2 9 4 0!!!!!!!!4 3 1 2 1 1 7 0<|endoftext|>',
 ' 66 5 6 7 3????????0 2 3 9 3 4 ( 6 7 9 6 7 4 )????????0 0 2 5 5 2 1 ( 6 7 1 2 3 7 1 )???? 20 0 0 6 7 2 6 0!!!!!!!!6 7 1 8 1 0 8 0<|endoftext|>',
 ' Grammy0 2 3 1 1????????0 0 0 3 8 2 ( 0 2 3 4 9 2 )???? 40 0 0 6 9 3 3 ( 0 2 3 0 9 6 3 )???? 00 0 0 0 2 3 1 1!!!!!!!!0 2 3 0 0 0 5 1<|endoftext|>',
 'kid6 1 2 8 1????????0 8 4 6 4 5 ( 6 9 6 4 6 5 )????40 0 6 1 2 8 1 ( 6 9 2 6 8 3 2 )???? 60 0 0 2 7 9 1 8!!!!!!!!6 9 2 8 2 3 4 8<|endoftext|>']

In [ ]:
labels_full_text

['////5 5 5 6 1????////0 0 6 4 9 0 ( 5 5 1 1 1 1 )????////0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 )????////0 0 0 0 6 4 9 0!!!!////5 5 6 0 8 2 0 1<|endoftext|>',
 '////6 7 1 1 3????////0 4 8 7 0 2 ( 6 1 0 9 3 2 )????////0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 )????////0 0 0 2 7 3 6 3!!!!////6 1 4 9 8 6 8 3<|endoftext|>',
 '////8 0 0 5 7????////0 4 8 3 4 8 ( 8 4 8 8 1 9 )????////0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 )????////0 0 0 2 3 6 5 6!!!!////8 4 4 8 8 4 7 6<|endoftext|>',
 '////9 0 9 2 1????////0 2 1 2 7 1 ( 9 2 0 5 8 1 )????////0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 )????////0 0 0 5 1 5 1 2!!!!////9 2 8 1 8 2 4 2<|endoftext|>',
 '////0 4 6 8 5????////0 0 5 6 6 3 ( 0 4 1 5 2 4 )????////0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 )????////0 0 0 0 5 6 6 3!!!!////0 4 1 3 7 4 1 4<|endoftext|>',
 '////2 5 2 4 2????////0 9 8 1 8 1 ( 2 4 1 6 0 2 )????////0 0 4 0 5 8 4 ( 2 4 5 6 5 0 5 )????////0 0 0 1 4 4 2 4!!!!////2 4 5 7 9 4 7 4<|endoftext|>',
 '////8 4 7 9 0????////0 6 6 8 3 4 ( 8 0 4 8 4 4 )????////0 0 4 7 8 4 0 ( 8 0 8 5 3 9 0 )????////0 0 0 4 4 2 9 2!!!!////8 0 8 9 7 1 0 3<|endoftext|>',
 '////0 0 0 0 0????////0 0 6 4 8 0 ( 0 0 6 4 8 0 )????////0 0 2 9 6 1 0 ( 0 0 8 3 5 2 0 )????////0 0 0 8 2 2 5 1!!!!////0 0 8 1 8 4 5 1<|endoftext|>',
 '////5 5 5 2 2????////0 6 6 0 7 2 ( 5 1 2 3 9 2 )????////0 0 0 0 0 0 0 ( 5 1 2 3 9 2 0 )????////0 0 0 5 5 5 2 2!!!!////5 1 2 8 4 8 2 2<|endoftext|>',
 '////0 0 0 0 0????////0 7 3 9 5 3 ( 0 7 3 9 5 3 )????////0 0 9 7 9 1 1 ( 0 7 2 7 5 5 1 )????////0 0 0 9 7 9 1 1!!!!////0 7 2 6 3 5 3 1<|endoftext|>',
 '////5 6 8 3 0????////0 0 6 4 5 1 ( 5 6 4 8 5 1 )????////0 0 5 8 7 4 3 ( 5 6 9 6 3 6 3 )????////0 0 0 5 5 0 7 2!!!!////5 6 9 1 9 6 0 3<|endoftext|>',
 '////4 8 1 4 5????////0 5 6 8 3 3 ( 4 3 8 2 9 3 )????////0 0 5 6 8 3 3 ( 4 3 3 9 7 7 3 )????////0 0 0 6 4 5 3 1!!!!////4 3 3 5 2 3 7 1<|endoftext|>',
 '////4 4 8 9 0????////0 9 4 1 2 2 ( 4 3 3 1 3 2 )????////0 0 8 8 6 9 1 ( 4 3 1 0 0 2 2 )????////0 0 0 2 2 9 4 0!!!!////4 3 1 2 2 1 7 0<|endoftext|>',
 '////6 5 6 7 3????////0 2 3 9 3 4 ( 6 7 9 6 7 4 )????////0 0 2 5 5 2 1 ( 6 7 1 2 3 7 1 )????////0 0 0 6 7 2 6 0!!!!////6 7 1 8 0 0 8 0<|endoftext|>',
 '////0 2 3 1 1????////0 0 0 3 8 2 ( 0 2 3 4 9 2 )????////0 0 0 6 9 3 3 ( 0 2 3 0 9 6 3 )????////0 0 0 0 2 3 1 1!!!!////0 2 3 0 1 0 5 1<|endoftext|>',
 '////6 1 2 8 1????////0 8 4 6 4 5 ( 6 9 6 4 6 5 )????////0 0 6 1 2 8 1 ( 6 9 2 6 8 3 2 )????////0 0 0 2 7 9 1 8!!!!////6 9 2 8 5 3 4 8<|endoftext|>']

In [ ]:

preds_cot = [extract_cot(p) for p in preds_full_text]
preds_ans = [extract_answer(p) for p in preds_full_text]

labels_cot = [extract_cot(lab) for lab in labels_full_text]
labels_ans = [extract_answer(lab) for lab in labels_full_text]

acc_cot = np.mean([c == p for c, p in zip(preds_cot, labels_cot)])
acc_ans = np.mean([c == lab for c, lab in zip(preds_ans, labels_ans)])

In [ ]:
preds.shape, labels.shape

(torch.Size([16, 72]), torch.Size([1, 72]))

In [ ]:
preds

tensor([[25481,  1666, 13129,  ...,   352, 50256, 50256],
        [25481,   274, 12163,  ...,   513, 50256, 50256],
        [25481,   274,   513,  ...,   718, 50256, 50256],
        ...,
        [25481,   274,   513,  ...,   657, 50256, 50256],
        [25481,   657,   513,  ...,   352, 50256, 50256],
        [25481,    67,   352,  ...,   807, 50256, 50256]])

In [ ]:
# tokenizer.decode([segment['labels'][0][0] for segment in segments[1:]])

In [ ]:
# import pandas as pd
# res_df = pd.DataFrame(columns=['cpt_path', 'cot', 'acc_cot', 'acc_ans'])

In [ ]:
[o.loss for o in cell_outputs]

[None, None, None, None, None, None]

In [ ]:

model.generation_config.pad_token_id = tokenizer.pad_token_id
gen_outputs = [model.generate(inp.reshape(1, -1).to(device), 
                            pad_token_id=tokenizer.eos_token_id,
                            attention_mask=torch.ones_like(inp.reshape(1, -1)).to(device),
                            max_new_tokens=50)[0] for inp in collated['input_ids_generate']]

if args.use_cot:
    gen_outputs = [model.generate(inp.reshape(1, -1).to(device), 
                                    pad_token_id=tokenizer.eos_token_id,
                                    attention_mask=torch.ones_like(inp.reshape(1, -1)).to(device))[0].cpu() for inp in gen_outputs]

labels = collated['labels']
labels_masks = labels > 0

preds_full = [out[len(inp):] for inp, out in zip(collated['input_ids_generate'], gen_outputs)]
# preds_full = [out[len(inp):] for inp, out in zip(collated['input_ids_generate'], gen_outputs_m2)]
labels_full = [lab[m][1:] for lab, m in zip(labels, labels_masks)]

print(len(preds_full), len(labels_full))

preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

preds_cot = [extract_cot(p) for p in preds_full_text]
preds_ans = [extract_answer(p) for p in preds_full_text]

labels_cot = [extract_cot(lab) for lab in labels_full_text]
labels_ans = [extract_answer(lab) for lab in labels_full_text]

acc_cot = np.mean([c == p for c, p in zip(preds_cot, labels_cot)])
acc_ans = np.mean([c == lab for c, lab in zip(preds_ans, labels_ans)])

data = {"inputs": collated['input_ids_generate'],
        "preds_full_text": preds_full_text, "labels_full_text": labels_full_text,
        "preds_cot": preds_cot, "labels_cot": labels_cot,
        "preds_ans": preds_ans, "labels_ans": labels_ans}

print(f"Accuracy COT: {acc_cot}")
print(f"Accuracy Answer: {acc_ans}")

In [ ]:
args.use_cot = False

checkpoints = [
    "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR3e-04/checkpoint-16500/pytorch_model.bin",
    "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR1e-03/checkpoint-24500/pytorch_model.bin",
]

for cpt_path in checkpoints:
    print(cpt_path)
    acc_cot, acc_ans = evaluate_model_on_dataset(cpt_path, valid_dataset)
    res_df.loc[len(res_df)] = [cpt_path.split('/')[-3], args.use_cot, 0, acc_cot]

/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR3e-04/checkpoint-16500/pytorch_model.bin
500 500
Accuracy COT: 0.172
Accuracy Answer: 1.0
/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR1e-03/checkpoint-24500/pytorch_model.bin
500 500
Accuracy COT: 0.148
Accuracy Answer: 1.0

In [ ]:
res_df

                       cpt_path    cot  acc_cot  acc_ans
0  SEGM_1x1024_1024_LR1e-03-cot   True    0.172    0.450
1  SEGM_1x1024_1024_LR3e-04-cot   True    0.156    0.392
2      SEGM_1x1024_1024_LR3e-04  False    0.000    0.172
3      SEGM_1x1024_1024_LR1e-03  False    0.000    0.148

In [ ]:
# model.load_state_dict(torch.load(checkpoint_path), strict=False)
model.generation_config.pad_token_id = tokenizer.pad_token_id
model.to(device)
    
collated = collate_fn([sample for sample in valid_dataset])
model.generation_config.pad_token_id = tokenizer.pad_token_id
gen_outputs = [model.generate(inp.reshape(1, -1).to(device), 
                            pad_token_id=tokenizer.eos_token_id,
                            attention_mask=torch.ones_like(inp.reshape(1, -1)).to(device),
                            max_new_tokens=50)[0] for inp in collated['input_ids_generate']]

gen_outputs_m2 = [model.generate(inp.reshape(1, -1).to(device), 
                                    pad_token_id=tokenizer.eos_token_id,
                                    attention_mask=torch.ones_like(inp.reshape(1, -1)).to(device))[0].cpu() for inp in gen_outputs]

labels = collated['labels']
labels_masks = labels > 0

preds_full = [out[len(inp):] for inp, out in zip(collated['input_ids_generate'], gen_outputs_m2)]
labels_full = [lab[m][1:] for lab, m in zip(labels, labels_masks)]

print(len(preds_full), len(labels_full))

preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

preds_cot = [extract_cot(p) for p in preds_full_text]
preds_ans = [extract_answer(p) for p in preds_full_text]

labels_cot = [extract_cot(lab) for lab in labels_full_text]
labels_ans = [extract_answer(lab) for lab in labels_full_text]

acc_cot = np.mean([c == p for c, p in zip(preds_cot, labels_cot)])
acc_ans = np.mean([c == lab for c, lab in zip(preds_ans, labels_ans)])

print(f"Accuracy COT: {acc_cot}")
print(f"Accuracy Answer: {acc_ans}")

500 500
Accuracy COT: 0.148
Accuracy Answer: 1.0

In [ ]:
def extract_cot(text):
        try:
                return text[:text.index(ans_text)]
        except ValueError:
                return ''

def extract_answer(text):
        try:
                return text.split(ans_text)[1]
        except IndexError:
                return ''

In [ ]:
preds_full_text

['600<|endoftext|><|endoftext|>',
 '7.5<|endoftext|><|endoftext|>',
 '1400<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '240<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '160<|endoftext|><|endoftext|>',
 '1.5<|endoftext|><|endoftext|>',
 '21.75<|endoftext|><|endoftext|>',
 '21.5<|endoftext|><|endoftext|>',
 '14<|endoftext|><|endoftext|>',
 '88<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '130<|endoftext|><|endoftext|>',
 '16.67<|endoftext|><|endoftext|>',
 '33.33<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '-4<|endoftext|><|endoftext|>',
 '90<|endoftext|><|endoftext|>',
 '46<|endoftext|><|endoftext|>',
 '715<|endoftext|><|endoftext|>',
 '5<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '1<|endoftext|><|endoftext|>',
 '12000<|endoftext|><|endoftext|>',
 '160<|endoftext|><|endoftext|>',
 '5<|endoftext|><|endoftext|>',
 '45<|endoftext|><|endoftext|>',
 '74<|endoftext|><|endoftext|>',
 '460<|endoftext|><|endoftext|>',
 '52<|endoftext|><|endoftext|>',
 '98<|endoftext|><|endoftext|>',
 '35<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '550<|endoftext|><|endoftext|>',
 '64<|endoftext|><|endoftext|>',
 '240<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '65<|endoftext|><|endoftext|>',
 '16<|endoftext|><|endoftext|>',
 '1240<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '135<|endoftext|><|endoftext|>',
 '2<|endoftext|><|endoftext|>',
 '65<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '35<|endoftext|><|endoftext|>',
 '12000<|endoftext|><|endoftext|>',
 '2056<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '480<|endoftext|><|endoftext|>',
 '-3000<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '135<|endoftext|><|endoftext|>',
 '55<|endoftext|><|endoftext|>',
 '19<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '3.6<|endoftext|><|endoftext|>',
 '19<|endoftext|><|endoftext|>',
 '130<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '2120<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '10000<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '1350<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '2<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '66<|endoftext|><|endoftext|>',
 '57<|endoftext|><|endoftext|>',
 '60<|endoftext|><|endoftext|>',
 '60<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '54<|endoftext|><|endoftext|>',
 '312<|endoftext|><|endoftext|>',
 '0.4<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '70<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '16<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '18000<|endoftext|><|endoftext|>',
 '60<|endoftext|><|endoftext|>',
 '720<|endoftext|><|endoftext|>',
 '32<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '16<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '100<|endoftext|><|endoftext|>',
 '70<|endoftext|><|endoftext|>',
 '1040<|endoftext|><|endoftext|>',
 '5.5<|endoftext|><|endoftext|>',
 '145<|endoftext|><|endoftext|>',
 '2<|endoftext|><|endoftext|>',
 '16<|endoftext|><|endoftext|>',
 '55<|endoftext|><|endoftext|>',
 '216<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '90<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '336<|endoftext|><|endoftext|>',
 '825<|endoftext|><|endoftext|>',
 '360<|endoftext|><|endoftext|>',
 '1500<|endoftext|><|endoftext|>',
 '120<|endoftext|><|endoftext|>',
 '22<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '1200<|endoftext|><|endoftext|>',
 '78<|endoftext|><|endoftext|>',
 '61.2<|endoftext|><|endoftext|>',
 '0<|endoftext|><|endoftext|>',
 '6.25<|endoftext|><|endoftext|>',
 '24<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '24<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '440<|endoftext|><|endoftext|>',
 '130<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '195<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '-500<|endoftext|><|endoftext|>',
 '1300<|endoftext|><|endoftext|>',
 '200<|endoftext|><|endoftext|>',
 '13<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '150<|endoftext|><|endoftext|>',
 '1.5<|endoftext|><|endoftext|>',
 '17<|endoftext|><|endoftext|>',
 '46.4<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '31<|endoftext|><|endoftext|>',
 '11<|endoftext|><|endoftext|>',
 '90<|endoftext|><|endoftext|>',
 '55<|endoftext|><|endoftext|>',
 '40<|endoftext|><|endoftext|>',
 '35<|endoftext|><|endoftext|>',
 '119.5<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '198<|endoftext|><|endoftext|>',
 '144<|endoftext|><|endoftext|>',
 '600<|endoftext|><|endoftext|>',
 '1<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '900<|endoftext|><|endoftext|>',
 '1800<|endoftext|><|endoftext|>',
 '63<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '14<|endoftext|><|endoftext|>',
 '38<|endoftext|><|endoftext|>',
 '14<|endoftext|><|endoftext|>',
 '100<|endoftext|><|endoftext|>',
 '23<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '190<|endoftext|><|endoftext|>',
 '3360<|endoftext|><|endoftext|>',
 '15300<|endoftext|><|endoftext|>',
 '2.1<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '1920<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '320<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '585<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '48<|endoftext|><|endoftext|>',
 '41<|endoftext|><|endoftext|>',
 '7200<|endoftext|><|endoftext|>',
 '43<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '61.25<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '72<|endoftext|><|endoftext|>',
 '3.33<|endoftext|><|endoftext|>',
 '34<|endoftext|><|endoftext|>',
 '5.5<|endoftext|><|endoftext|>',
 '60<|endoftext|><|endoftext|>',
 '2000<|endoftext|><|endoftext|>',
 '780<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '150<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '54<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '1600<|endoftext|><|endoftext|>',
 '120<|endoftext|><|endoftext|>',
 '14<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '16<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '22000<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '480<|endoftext|><|endoftext|>',
 '21<|endoftext|><|endoftext|>',
 '1<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '26.67<|endoftext|><|endoftext|>',
 '4200<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '46.67<|endoftext|><|endoftext|>',
 '-20<|endoftext|><|endoftext|>',
 '24<|endoftext|><|endoftext|>',
 '14<|endoftext|><|endoftext|>',
 '22<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '72<|endoftext|><|endoftext|>',
 '19<|endoftext|><|endoftext|>',
 '53<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '21<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '70<|endoftext|><|endoftext|>',
 '180<|endoftext|><|endoftext|>',
 '86<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '27<|endoftext|><|endoftext|>',
 '32<|endoftext|><|endoftext|>',
 '82<|endoftext|><|endoftext|>',
 '12.5<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '1260<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '144<|endoftext|><|endoftext|>',
 '13<|endoftext|><|endoftext|>',
 '58<|endoftext|><|endoftext|>',
 '-80<|endoftext|><|endoftext|>',
 '-1<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '21<|endoftext|><|endoftext|>',
 '46<|endoftext|><|endoftext|>',
 '1895<|endoftext|><|endoftext|>',
 '135<|endoftext|><|endoftext|>',
 '32<|endoftext|><|endoftext|>',
 '5<|endoftext|><|endoftext|>',
 '1350<|endoftext|><|endoftext|>',
 '200<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '22<|endoftext|><|endoftext|>',
 '180<|endoftext|><|endoftext|>',
 '29<|endoftext|><|endoftext|>',
 '4500<|endoftext|><|endoftext|>',
 '120<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '10.5<|endoftext|><|endoftext|>',
 '11<|endoftext|><|endoftext|>',
 '21<|endoftext|><|endoftext|>',
 '2600<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '385<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '1.33<|endoftext|><|endoftext|>',
 '28<|endoftext|><|endoftext|>',
 '21<|endoftext|><|endoftext|>',
 '78<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '46.4<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '14000<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '7<|endoftext|><|endoftext|>',
 '260<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '34<|endoftext|><|endoftext|>',
 '84<|endoftext|><|endoftext|>',
 '750<|endoftext|><|endoftext|>',
 '16<|endoftext|><|endoftext|>',
 '225<|endoftext|><|endoftext|>',
 '260<|endoftext|><|endoftext|>',
 '54<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '49<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '60<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '3240<|endoftext|><|endoftext|>',
 '54<|endoftext|><|endoftext|>',
 '5<|endoftext|><|endoftext|>',
 '62.5<|endoftext|><|endoftext|>',
 '1000<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '32<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '14<|endoftext|><|endoftext|>',
 '66.67<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '-7<|endoftext|><|endoftext|>',
 '171<|endoftext|><|endoftext|>',
 '93<|endoftext|><|endoftext|>',
 '3000<|endoftext|><|endoftext|>',
 '306<|endoftext|><|endoftext|>',
 '4000<|endoftext|><|endoftext|>',
 '1450<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '142.86<|endoftext|><|endoftext|>',
 '326<|endoftext|><|endoftext|>',
 '400<|endoftext|><|endoftext|>',
 '17.5<|endoftext|><|endoftext|>',
 '7.5<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '120<|endoftext|><|endoftext|>',
 '-5<|endoftext|><|endoftext|>',
 '36<|endoftext|><|endoftext|>',
 '1200<|endoftext|><|endoftext|>',
 '2200<|endoftext|><|endoftext|>',
 '19<|endoftext|><|endoftext|>',
 '90<|endoftext|><|endoftext|>',
 '21<|endoftext|><|endoftext|>',
 '288<|endoftext|><|endoftext|>',
 '3600<|endoftext|><|endoftext|>',
 '28<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '60<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '71<|endoftext|><|endoftext|>',
 '700<|endoftext|><|endoftext|>',
 '200<|endoftext|><|endoftext|>',
 '31250<|endoftext|><|endoftext|>',
 '125<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '44<|endoftext|><|endoftext|>',
 '3.5<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '130<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '1456<|endoftext|><|endoftext|>',
 '2900<|endoftext|><|endoftext|>',
 '175<|endoftext|><|endoftext|>',
 '36<|endoftext|><|endoftext|>',
 '1040<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '600<|endoftext|><|endoftext|>',
 '-4.5<|endoftext|><|endoftext|>',
 '-4<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '1.5<|endoftext|><|endoftext|>',
 '1268<|endoftext|><|endoftext|>',
 '125<|endoftext|><|endoftext|>',
 '42<|endoftext|><|endoftext|>',
 '83<|endoftext|><|endoftext|>',
 '44<|endoftext|><|endoftext|>',
 '600<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '49<|endoftext|><|endoftext|>',
 '2.67<|endoftext|><|endoftext|>',
 '54<|endoftext|><|endoftext|>',
 '80<|endoftext|><|endoftext|>',
 '5.83<|endoftext|><|endoftext|>',
 '17<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '52<|endoftext|><|endoftext|>',
 '750<|endoftext|><|endoftext|>',
 '15<|endoftext|><|endoftext|>',
 '16<|endoftext|><|endoftext|>',
 '330<|endoftext|><|endoftext|>',
 '18000<|endoftext|><|endoftext|>',
 '2000<|endoftext|><|endoftext|>',
 '-150<|endoftext|><|endoftext|>',
 '46.67<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '82<|endoftext|><|endoftext|>',
 '-38400<|endoftext|><|endoftext|>',
 '45<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '23<|endoftext|><|endoftext|>',
 '90<|endoftext|><|endoftext|>',
 '2<|endoftext|><|endoftext|>',
 '5<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '505<|endoftext|><|endoftext|>',
 '143<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '35<|endoftext|><|endoftext|>',
 '660<|endoftext|><|endoftext|>',
 '98<|endoftext|><|endoftext|>',
 '32<|endoftext|><|endoftext|>',
 '-200<|endoftext|><|endoftext|>',
 '50<|endoftext|><|endoftext|>',
 '13<|endoftext|><|endoftext|>',
 '2<|endoftext|><|endoftext|>',
 '22<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '27<|endoftext|><|endoftext|>',
 '4.5<|endoftext|><|endoftext|>',
 '225<|endoftext|><|endoftext|>',
 '91<|endoftext|><|endoftext|>',
 '3.5<|endoftext|><|endoftext|>',
 '14<|endoftext|><|endoftext|>',
 '133.34<|endoftext|><|endoftext|>',
 '94.50<|endoftext|><|endoftext|>',
 '700<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '64<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '75<|endoftext|><|endoftext|>',
 '96<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '10<|endoftext|><|endoftext|>',
 '35<|endoftext|><|endoftext|>',
 '150<|endoftext|><|endoftext|>',
 '40<|endoftext|><|endoftext|>',
 '7<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '27<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '19<|endoftext|><|endoftext|>',
 '450<|endoftext|><|endoftext|>',
 '180<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '320<|endoftext|><|endoftext|>',
 '58<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '27<|endoftext|><|endoftext|>',
 '180<|endoftext|><|endoftext|>',
 '1440<|endoftext|><|endoftext|>',
 '300<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '90<|endoftext|><|endoftext|>',
 '2<|endoftext|><|endoftext|>',
 '35<|endoftext|><|endoftext|>',
 '5<|endoftext|><|endoftext|>',
 '19200<|endoftext|><|endoftext|>',
 '-5<|endoftext|><|endoftext|>',
 '-18<|endoftext|><|endoftext|>',
 '203<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '440<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '96<|endoftext|><|endoftext|>',
 '500<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '21<|endoftext|><|endoftext|>',
 '56<|endoftext|><|endoftext|>',
 '2000<|endoftext|><|endoftext|>',
 '25<|endoftext|><|endoftext|>',
 '4.33<|endoftext|><|endoftext|>',
 '-1489<|endoftext|><|endoftext|>',
 '100<|endoftext|><|endoftext|>',
 '9<|endoftext|><|endoftext|>',
 '2<|endoftext|><|endoftext|>',
 '8<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '90<|endoftext|><|endoftext|>',
 '30<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '1260<|endoftext|><|endoftext|>',
 '5<|endoftext|><|endoftext|>',
 '48<|endoftext|><|endoftext|>',
 '36<|endoftext|><|endoftext|>',
 '2.92<|endoftext|><|endoftext|>',
 '5.5<|endoftext|><|endoftext|>',
 '56<|endoftext|><|endoftext|>',
 '6<|endoftext|><|endoftext|>',
 '18<|endoftext|><|endoftext|>',
 '203<|endoftext|><|endoftext|>',
 '45<|endoftext|><|endoftext|>',
 '12<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '113<|endoftext|><|endoftext|>',
 '4<|endoftext|><|endoftext|>',
 '22<|endoftext|><|endoftext|>',
 '20<|endoftext|><|endoftext|>',
 '24<|endoftext|><|endoftext|>',
 '3<|endoftext|><|endoftext|>']

In [ ]:
preds_cot[:10]

['600', '7.5', '1400', '15', '240', '20', '160', '1.5', '21.75', '21.5']

In [ ]:
labels_cot[:10]

['300', '10', '1400', '15', '240', '20', '10', '2', '25', '25']

In [ ]:
preds_ans[:10]

['', '', '', '', '', '', '', '', '', '']

In [ ]:
labels_ans[:10]

['', '', '', '', '', '', '', '', '', '']

In [ ]:

labels = collated['labels'][:, 1:]
labels_masks = labels > 0

preds_full = [out[len(inp):] for inp, out in zip(collated['input_ids_generate'], gen_outputs_m2)]
labels_full = [lab[m][1:] for lab, m in zip(labels, labels_masks)]

print(len(preds_full), len(labels_full))

preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

preds_cot = [extract_cot(p) for p in preds_full_text]
preds_ans = [extract_answer(p) for p in preds_full_text]

labels_cot = [extract_cot(lab) for lab in labels_full_text]
labels_ans = [extract_answer(lab) for lab in labels_full_text]

acc_cot = np.mean([c == p for c, p in zip(preds_cot, labels_cot)])
acc_ans = np.mean([c == lab for c, lab in zip(preds_ans, labels_ans)])

print(f"Accuracy COT: {acc_cot}")
print(f"Accuracy Answer: {acc_ans}")

5 5
Accuracy COT: 0.6
Accuracy Answer: 1.0

In [ ]:
dataset = 'booydar/gsm8k'
train_dataset = datasets.load_dataset(dataset, split='train')
valid_dataset = datasets.load_dataset(dataset, split='valid')

# cot
args.use_cot = True

checkpoints = [
    "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR1e-03-cot/checkpoint-23500/pytorch_model.bin",
    "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR1e-05-cot/checkpoint-5000/pytorch_model.bin",
    "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR3e-04-cot/checkpoint-17500/pytorch_model.bin",
]

In [ ]:
# cpt_path = "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/test/4_by_4_mult/Llama-3.2-1B-Instruct/smol:qa1-5-1:9/SEGM_1x1024_1024_64_LR3e-04-lora-mnc-distill__short/checkpoint-5000/pytorch_model.bin"
# cpt_path = "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/test/4_by_4_mult/gpt2/SEGM_1x1024_1024_LR3e-04/checkpoint-25000/pytorch_model.bin"
# cpt_path = "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR3e-04/checkpoint-16500/pytorch_model.bin"
cpt_path = "/workspace-SR006.nfs2/Bulatov_A/rmt/runs/gsm8k/gpt2/SEGM_1x1024_1024_LR1e-03-cot/checkpoint-23500/pytorch_model.bin"
model.load_state_dict(torch.load(cpt_path), strict=False)

In [ ]:
# dataset_dir = "/workspace-SR006.nfs2/Bulatov_A/rmt/data/implicit_chain_of_thought/4_by_4_mult"

# train_path = os.path.join(dataset_dir, "train")
# valid_path = os.path.join(dataset_dir, "valid")
# train_dataset = datasets.load_from_disk(train_path)
# valid_dataset = datasets.load_from_disk(valid_path)

Generating train split: 100%|██████████| 384620/384620 [00:00<00:00, 935478.06 examples/s]
Generating valid split: 100%|██████████| 500/500 [00:00<00:00, 110028.96 examples/s]
Generating test split: 100%|██████████| 1319/1319 [00:00<00:00, 242176.81 examples/s]
Generating train_no_aug split: 100%|██████████| 6973/6973 [00:00<00:00, 436918.42 examples/s]

In [ ]:
class Holder:
    def __init__(self):
        pass
args = Holder()
# args.use_cot = False
args.use_cot = True
args.num_mem_tokens = None

In [ ]:

id_pad_value = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
think = ans = tokenizer.bos_token_id
eos = tokenizer.eos_token_id

def collate_fn(batch):
    input_ids, input_ids_generate, labels, labels_mask, attention_mask = [], [], [], [], []
    for sample in batch:
        task, lab, cot = sample['task'], sample['labels'], sample['cot']
        task_tokens = tokenizer.encode(task, add_special_tokens=False)
        labels_tokens = tokenizer.encode(lab, add_special_tokens=False)
        cot_tokens = tokenizer.encode(cot, add_special_tokens=False)

        if args.use_cot:
            full_input = task_tokens + [think] + cot_tokens + [ans] + labels_tokens + [eos]
            gen_input = task_tokens + [think]
        else:
            full_input = task_tokens + [ans] + labels_tokens + [eos]
            gen_input = task_tokens + [ans]
        
        inp_ids = torch.tensor(full_input)
        input_ids.append(inp_ids)
        input_ids_generate.append(torch.tensor(gen_input))


        lab = torch.tensor(full_input)
        lab[:len(task_tokens)] = -100
        labels.append(lab)

        lab_mask = torch.ones_like(inp_ids)
        lab_mask[:len(task_tokens)] = 0
        labels_mask.append(lab_mask)
        attention_mask.append(torch.ones_like(inp_ids))

    input_ids = pad_sequence(input_ids, padding_value=id_pad_value, batch_first=True)
    # input_ids_generate = pad_sequence(input_ids_generate, padding_value=id_pad_value, batch_first=True)
    attention_mask = pad_sequence(attention_mask, padding_value=0, batch_first=True)
    labels = pad_sequence(labels, padding_value=id_pad_value, batch_first=True)
    labels_mask = pad_sequence(labels_mask, padding_value=0, batch_first=True)

    collated = {'input_ids': input_ids,
                'input_ids_generate': input_ids_generate,
                'labels': labels,
                'attention_mask': attention_mask,
                }
    if args.num_mem_tokens is not None:
        # add labels mask only for RMT, ARMT
        collated['labels_mask'] = labels_mask.bool()
    return collated

In [ ]:
think_text = tokenizer.decode(think)
ans_text = tokenizer.decode(ans)

def extract_cot(text):
        try:
                return text[:text.index(ans_text)]
        except ValueError:
                return ''

def extract_answer(text):
        try:
                return text.split(ans_text)[1]
        except IndexError:
                return ''
                
def compute_accuracy(eval_pred):
        preds = eval_pred.predictions.argmax(axis=-1)[:, 1:-1]
        labels = eval_pred.label_ids[:, 2:]

        labels_masks = labels > 0
        preds_full = [p[m] for p, m in zip(preds, labels_masks)]
        labels_full = [lab[m] for lab, m in zip(labels, labels_masks)]

        print(len(preds_full), len(labels_full))

        preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
        labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

        preds_cot = [extract_cot(p) for p in preds_full_text]
        preds_ans = [extract_answer(p) for p in preds_full_text]

        labels_cot = [extract_cot(lab) for lab in labels_full_text]
        labels_ans = [extract_answer(lab) for lab in labels_full_text]

        acc_cot = np.mean([c == p for c, p in zip(preds_cot, labels_cot)])
        acc_ans = np.mean([c == lab for c, lab in zip(preds_ans, labels_ans)])

        return {'accuracy_cot': acc_cot, 'accuracy_ans': acc_ans}

In [ ]:
batch = [valid_dataset[i] for i in range(10)]
collated = collate_fn(batch)

out = model(**collated)
print(out.keys())

odict_keys(['loss', 'logits', 'past_key_values'])


### no teacher forcing

In [ ]:
model.generation_config.pad_token_id = tokenizer.pad_token_id

In [ ]:
model.generation_config.pad_token_id = tokenizer.pad_token_id
gen_outputs = [model.generate(inp.reshape(1, -1), 
                              attention_mask=torch.ones_like(inp.reshape(1, -1)),
                              max_new_tokens=50)[0] for inp in collated['input_ids_generate']]

gen_outputs_m2 = [model.generate(inp.reshape(1, -1), attention_mask=torch.ones_like(inp.reshape(1, -1)))[0] for inp in gen_outputs]

In [ ]:
# gen_outputs_m2 = [out[len(inp):] for inp, out in zip(collated['input_ids_generate'], gen_outputs_m2)]

In [ ]:
tokenizer.batch_decode(gen_outputs_m2)

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>><|endoftext|>300<|endoftext|>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>><|endoftext|>10<|endoftext|>',
 '<<2000*30/100=600>> <<2000-600=1400>><|endoftext|>1400<|endoftext|>',
 '<<21/7=3>> <<5*3=15>><|endoftext|>15<|endoftext|>',
 '<<200*3=600>> <<600*0.4=240>><|endoftext|>240<|endoftext|>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50+30=80>> <<100-80=20>><|endoftext|>20<|endoftext|>',
 '<<40*2=80>> <<80*2=160>><|endoftext|>160<|endoftext|>',
 '<<12*2=24>> <<4*1=4>> <<4*3=12>> <<24+4+12=40>> <<40/4=10>><|endoftext|>10<|endoftext|>',
 '<<2*2.25=4.50>> <<4.50+3.50+4+3.50=15.00>> <<2*2.50=5.00>> <<15+5+3.50=23.50>><|endoftext|>',
 '<<28/4=7>> <<3*7+1=22>><|endoftext|>22<|endoftext|>']

In [ ]:
preds = gen_outputs_m2
labels_masks = labels > 0

preds_full = gen_outputs_m2 #[out[len(inp):] for inp, out in zip(collated['input_ids_generate'], gen_outputs_m2)]
labels_full = [lab[m][1:] for lab, m in zip(labels, labels_masks)]

print(len(preds_full), len(labels_full))

preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

preds_cot = [extract_cot(p) for p in preds_full_text]
preds_ans = [extract_answer(p) for p in preds_full_text]

labels_cot = [extract_cot(lab) for lab in labels_full_text]
labels_ans = [extract_answer(lab) for lab in labels_full_text]

acc_cot = np.mean([c == p for c, p in zip(preds_cot, labels_cot)])
acc_ans = np.mean([c == lab for c, lab in zip(preds_ans, labels_ans)])

print(f"Accuracy COT: {acc_cot}")
print(f"Accuracy Answer: {acc_ans}")

10 10
Accuracy COT: 0.3
Accuracy Answer: 0.6

In [ ]:
preds_full_text

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>><|endoftext|>300<|endoftext|>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>><|endoftext|>10<|endoftext|>',
 '<<2000*30/100=600>> <<2000-600=1400>><|endoftext|>1400<|endoftext|>',
 '<<21/7=3>> <<5*3=15>><|endoftext|>15<|endoftext|>',
 '<<200*3=600>> <<600*0.4=240>><|endoftext|>240<|endoftext|>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50+30=80>> <<100-80=20>><|endoftext|>20<|endoftext|>',
 '<<40*2=80>> <<80*2=160>><|endoftext|>160<|endoftext|>',
 '<<12*2=24>> <<4*1=4>> <<4*3=12>> <<24+4+12=40>> <<40/4=10>><|endoftext|>10<|endoftext|>',
 '<<2*2.25=4.50>> <<4.50+3.50+4+3.50=15.00>> <<2*2.50=5.00>> <<15+5+3.50=23.50>><|endoftext|>',
 '<<28/4=7>> <<3*7+1=22>><|endoftext|>22<|endoftext|>']

In [ ]:
labels_full_text

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>><|endoftext|>300<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<30/100*2000=600>> <<2000-600=1400>><|endoftext|>1400<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<21/7=3>> <<5*3=15>><|endoftext|>15<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<200*3=600>> <<600*.4=240>><|endoftext|>240<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50-30=20>><|endoftext|>20<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<40/2=20>> <<20/2=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<12*2=24>> <<4*1=4>> <<3*4=12>> <<24+4+12=40>> <<12+4+4=20>> <<40/20=2>><|endoftext|>2<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<2*2.25=4.50>> <<2*4=8.00>> <<2*2.50=5.00>> <<4.50+8.00+.50+5.00+3.50+3.50=25.00>><|endoftext|>25<|endoftext|>',
 '<<32=32>> <<8=8>><|endoftext|>25<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>']

In [ ]:
preds_cot

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>>',
 '<<2000*30/100=600>> <<2000-600=1400>>',
 '<<21/7=3>> <<5*3=15>>',
 '<<200*3=600>> <<600*0.4=240>>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50+30=80>> <<100-80=20>>',
 '<<40*2=80>> <<80*2=160>>',
 '<<12*2=24>> <<4*1=4>> <<4*3=12>> <<24+4+12=40>> <<40/4=10>>',
 '<<2*2.25=4.50>> <<4.50+3.50+4+3.50=15.00>> <<2*2.50=5.00>> <<15+5+3.50=23.50>>',
 '<<28/4=7>> <<3*7+1=22>>']

In [ ]:
labels_cot

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>>',
 '<<30/100*2000=600>> <<2000-600=1400>>',
 '<<21/7=3>> <<5*3=15>>',
 '<<200*3=600>> <<600*.4=240>>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50-30=20>>',
 '<<40/2=20>> <<20/2=10>>',
 '<<12*2=24>> <<4*1=4>> <<3*4=12>> <<24+4+12=40>> <<12+4+4=20>> <<40/20=2>>',
 '<<2*2.25=4.50>> <<2*4=8.00>> <<2*2.50=5.00>> <<4.50+8.00+.50+5.00+3.50+3.50=25.00>>',
 '<<32=32>> <<8=8>>']

In [ ]:
preds_ans

['300', '10', '1400', '15', '240', '20', '160', '10', '', '22']

In [ ]:
labels_ans

['300', '10', '1400', '15', '240', '20', '10', '2', '25', '25']


### teacher forcing

In [ ]:
labels_masks.shape, preds.shape

(torch.Size([10, 172]), (10, 173))

In [ ]:
# preds = eval_pred.predictions.argmax(axis=-1)[:, :-1]
# labels = eval_pred.label_ids[:, 1:]

preds = out.logits.argmax(dim=-1).cpu().numpy()[:, :-1]
labels = collated['labels'][:, 1:]

labels_masks = labels > 0
# labels_masks[:, :1] = False
preds_full = [p[m][1:] for p, m in zip(preds, labels_masks)]
labels_full = [lab[m][1:] for lab, m in zip(labels, labels_masks)]

print(len(preds_full), len(labels_full))

preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

preds_cot = [extract_cot(p) for p in preds_full_text]
preds_ans = [extract_answer(p) for p in preds_full_text]

labels_cot = [extract_cot(lab) for lab in labels_full_text]
labels_ans = [extract_answer(lab) for lab in labels_full_text]

acc_cot = np.mean([c == p for c, p in zip(preds_cot, labels_cot)])
acc_ans = np.mean([c == lab for c, lab in zip(preds_ans, labels_ans)])

print(f"Accuracy COT: {acc_cot}")
print(f"Accuracy Answer: {acc_ans}")

10 10
Accuracy COT: 0.3
Accuracy Answer: 0.9

In [ ]:
preds_full_text

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>><|endoftext|>300<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<2000/100*2000=600>> <<2000-600=1400>><|endoftext|>1400<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<21/7=3>> <<5*3=15>><|endoftext|>15<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<200*3=600>> <<600*4=240>><|endoftext|>240<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50+30=20>><|endoftext|>20<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<40*2=20>> <<20/2=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<12*2=24>> <<4*1=4>> <<4*4=12>> <<24+4+12=40>> <<40+4+12=20>> <<40/20=2>><|endoftext|>2<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<2*2.25=4.50>> <<4*4=8.00>> <<2*2.50=5.00>> <<4.50+8+00+50+5+00+3.50=2.50=28.00>><|endoftext|>25<|endoftext|>',
 '<<28/32>> <<(.8>> <<8<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>']

In [ ]:
labels_full_text

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>><|endoftext|>300<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<30/100*2000=600>> <<2000-600=1400>><|endoftext|>1400<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<21/7=3>> <<5*3=15>><|endoftext|>15<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<200*3=600>> <<600*.4=240>><|endoftext|>240<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50-30=20>><|endoftext|>20<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<40/2=20>> <<20/2=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<12*2=24>> <<4*1=4>> <<3*4=12>> <<24+4+12=40>> <<12+4+4=20>> <<40/20=2>><|endoftext|>2<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<<2*2.25=4.50>> <<2*4=8.00>> <<2*2.50=5.00>> <<4.50+8.00+.50+5.00+3.50+3.50=25.00>><|endoftext|>25<|endoftext|>',
 '<<32=32>> <<8=8>><|endoftext|>25<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>']

In [ ]:
preds_cot

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>>',
 '<<2000/100*2000=600>> <<2000-600=1400>>',
 '<<21/7=3>> <<5*3=15>>',
 '<<200*3=600>> <<600*4=240>>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50+30=20>>',
 '<<40*2=20>> <<20/2=10>>',
 '<<12*2=24>> <<4*1=4>> <<4*4=12>> <<24+4+12=40>> <<40+4+12=20>> <<40/20=2>>',
 '<<2*2.25=4.50>> <<4*4=8.00>> <<2*2.50=5.00>> <<4.50+8+00+50+5+00+3.50=2.50=28.00>>',
 '<<28/32>> <<(.8>> <<8']

In [ ]:
preds_cot

['<<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>>',
 '<<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>>',
 '<<2000/100*2000=600>> <<2000-600=1400>>',
 '<<21/7=3>> <<5*3=15>>',
 '<<200*3=600>> <<600*4=240>>',
 '<<1/2*100=50>> <<3/5*50=30>> <<50+30=20>>',
 '<<40*2=20>> <<20/2=10>>',
 '<<12*2=24>> <<4*1=4>> <<4*4=12>> <<24+4+12=40>> <<40+4+12=20>> <<40/20=2>>',
 '<<2*2.25=4.50>> <<4*4=8.00>> <<2*2.50=5.00>> <<4.50+8+00+50+5+00+3.50=2.50=28.00>>',
 '<<28/32>> <<(.8>> <<8']

In [ ]:
preds_ans

['300', '10', '1400', '15', '240', '20', '10', '2', '25', '']

In [ ]:
labels_ans

['300', '10', '1400', '15', '240', '20', '10', '2', '25', '25']

### Older pretokenize

In [ ]:
# from torch.nn.utils.rnn import pad_sequence
# id_pad_value = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
# if args.use_cot in (False, None):
#     inputs_key = 'examples_nocot'
#     labels_key = 'labels_nocot'
# else:
#     inputs_key = 'examples_all'
#     labels_key = 'labels_all'
    
# def collate_fn(batch):
#     input_ids = [torch.tensor(b[inputs_key]) for b in batch]
#     labels = [torch.tensor(b[labels_key]) for b in batch]
#     attention_mask = [torch.ones_like(b, dtype=int) for b in input_ids]
#     # labels_mask defines which input_ids participate in loss calculation
#     labels_mask = [torch.sign(torch.tensor(b[labels_key])) for b in batch]


#     input_ids = pad_sequence(input_ids, padding_value=id_pad_value, batch_first=True)
#     labels = pad_sequence(labels, padding_value=id_pad_value, batch_first=True)
#     attention_mask = pad_sequence(attention_mask, padding_value=0, batch_first=True)
#     labels_mask = pad_sequence(labels_mask, padding_value=0, batch_first=True)

#     collated = {'input_ids': input_ids,
#                 'labels': labels, 
#                 'attention_mask': attention_mask,
#                 }
#     if args.num_mem_tokens is not None:
#         # add labels mask only for RMT, ARMT
#         collated['labels_mask'] = labels_mask.bool()
#     return collated

In [ ]:
# def extract_cot(text):
#     if '<|endoftext|>' not in text:
#         return ''
#     else:
#         return text.split('<|endoftext|>')[0].strip()

# def extract_answer(text):
#     if '####' not in text:
#         return ''
#     else:
#         ans = text.split('####')[-1]
#         ans = ans.split('<|endoftext|>')[0]
#         return ans.strip()
        
# def compute_accuracy(eval_pred):
#     preds = eval_pred.predictions[:, :-1]
#     labels = eval_pred.label_ids[:, 1:]
#     # inputs = eval_pred.inputs
#     # losses = eval_pred.losses

#     # labels = collated['labels'][:, 1:]

#     labels_masks = labels > 0
#     preds_full = [p[m] for p, m in zip(preds, labels_masks)]
#     labels_full = [l[m] for l, m in zip(labels, labels_masks)]

#     preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
#     labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

#     preds_cot = [extract_cot(p) for p in preds_full_text]
#     preds_ans = [extract_answer(p) for p in preds_full_text]

#     labels_cot = [extract_cot(l) for l in labels_full_text]
#     labels_ans = [extract_answer(l) for l in labels_full_text]
    
#     # Calculate accuracy only on the unignored tokens
#     acc_cot = np.mean([c == l for c, l in zip(preds_cot, labels_cot)])
#     acc_ans = np.mean([c == l for c, l in zip(preds_ans, labels_ans)])

#     return {'accuracy_cot': acc_cot, 'accuracy_ans': acc_ans}

In [ ]:
# predictions = eval_pred.predictions
# label_ids = eval_pred.label_ids
# inputs = eval_pred.inputs
# losses = eval_pred.losses
# # elements = (self.predictions, self.label_ids)

In [ ]:
batch = [valid_dataset[i] for i in range(10)]
collated = collate_fn(batch)

out = model(**collated)
print(out.keys())

odict_keys(['loss', 'logits', 'past_key_values'])

In [ ]:
out.loss

tensor(0.0672, grad_fn=<NllLossBackward0>)

In [ ]:
preds = out.logits.argmax(dim=-1).cpu().numpy()
preds.shape

(10, 175)

In [ ]:
preds_text = tokenizer.batch_decode(preds, add_special_tokens=True)

In [ ]:
# preds_text[0].split('<|endoftext|>')

In [ ]:
# ''.split('<|endoftext|>')[1]

In [ ]:
labels = collated['labels'][:, 1:]

labels_masks = labels > 0
preds_full = [p[m] for p, m in zip(preds[:, :-1], labels_masks)]
labels_full = [l[m] for l, m in zip(labels, labels_masks)]

preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

preds_cot = [extract_cot(p) for p in preds_full_text]
preds_ans = [extract_answer(p) for p in preds_full_text]

labels_cot = [extract_cot(l) for l in labels_full_text]
labels_ans = [extract_answer(l) for l in labels_full_text]

In [ ]:
# labels = collated['labels'][:, 1:]

# labels_masks = labels > 0
# preds_full = [p[m] for p, m in zip(preds[:, :-1], labels_masks)]
# labels_full = [l[m] for l, m in zip(labels, labels_masks)]

# preds_full_text = tokenizer.batch_decode(preds_full, add_special_tokens=True)
# labels_full_text = tokenizer.batch_decode(labels_full, add_special_tokens=True)

# preds_cot = [p.split('<|endoftext|>')[0].strip() for p in preds_full_text]
# labels_cot = [l.split('<|endoftext|>')[0].strip() for l in labels_full_text]

# # preds_ans = [p.split('<|endoftext|>')[1].strip()[4:] for p in preds_full_text]
# # labels_ans = [l.split('<|endoftext|>')[1].strip()[4:] for l in labels_full_text]

# preds_ans = [p.split('####')[1].strip()[4:] for p in preds_full_text]
# labels_ans = [l.split('####')[1].split('astrip()[4:] for l in labels_full_text]

In [ ]:
tokenizer.batch_decode(collated['input_ids'])

['John cuts his grass to 2 inches.  It grows .5 inches per month.  When it gets to 4 inches he cuts it back down to 2 inches.  It cost $100 to get his grass cut.  How much does he pay per year?<|endoftext|><<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>><|endoftext|>300<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 'Hannah has three dogs. The first dog eats 1.5 cups of dog food a day. The second dog eats twice as much while the third dog eats 2.5 cups more than the second dog. How many cups of dog food should Hannah prepare in a day for her three dogs?<|endoftext|><<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 'Travis wants to fly to Australia. The regular tickets cost about $2000. As Travis is a student, he will get a 30% discount on this price. How much does he need to pay for his ticket?<|endoftext|><<30/100*2000=600>> <<2000-600=1400>><|endoftext|>1400<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 'A set of 7 spoons costs $21. If each spoon would be sold separately, how much would 5 spoons cost?<|endoftext|><<21/7=3>> <<5*3=15>><|endoftext|>15<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 'Tom bought his games for $200.  They tripled in value and he then sold 40% of them.  How much did he sell the games for?<|endoftext|><<200*3=600>> <<600*.4=240>><|endoftext|>240<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 "Maggie went to Lou's aquarium and saw 100 goldfish in the aquarium. She asked if she could take some home to care for, and she was allowed to catch half of them. While using a catching net, she caught 3/5 of the total number of goldfish she was allowed to take home. How many goldfish does Maggie remain with to catch to get the total number she was allowed to take home?<|endoftext|><<1/2*100=50>> <<3/5*50=30>> <<50-30=20>><|endoftext|>20<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>",
 'Kenny played basketball last week. He ran for twice as long as he played basketball, and he practiced on the trumpet for twice as long as he ran. If he practiced on the trumpet for 40 hours, how many hours did Kenny play basketball last week?<|endoftext|><<40/2=20>> <<20/2=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 'Marcia wants to buy some fruit. Apples cost $2, bananas cost $1, and oranges cost $3. If Marcia buys 12 apples, 4 bananas and 4 oranges, what is the average cost of each piece of fruit in dollars?<|endoftext|><<12*2=24>> <<4*1=4>> <<3*4=12>> <<24+4+12=40>> <<12+4+4=20>> <<40/20=2>><|endoftext|>2<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 "It’s Meghan’s turn to pick up her team's coffee order.  She needs 2 drip coffees that are $2.25 each and one double shot espresso that’s $3.50.  She needs 2 lattes that are $4.00 and needs to add vanilla syrup to one of those for an additional $0.50.  She also needs 2 cold brew coffees that are $2.50 each and 1 cappuccino for $3.50.  How much is the coffee order?<|endoftext|><<2*2.25=4.50>> <<2*4=8.00>> <<2*2.50=5.00>> <<4.50+8.00+.50+5.00+3.50+3.50=25.00>><|endoftext|>25<|endoftext|>",
 'Roman and Remy took separate showers. Remy used 1 more gallon than 3 times the number of gallons that Roman used for his shower. Together the boys used 33 gallons of water.  How many gallons did Remy use?<|endoftext|><<32=32>> <<8=8>><|endoftext|>25<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>']

In [ ]:
labels_full_text

['<|endoftext|><<4-2=2>> <<2/.5=4>> <<12/4=3>> <<100*3=300>><|endoftext|>300<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<1.5*2=3>> <<3+2.5=5.5>> <<1.5+3+5.5=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<30/100*2000=600>> <<2000-600=1400>><|endoftext|>1400<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<21/7=3>> <<5*3=15>><|endoftext|>15<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<200*3=600>> <<600*.4=240>><|endoftext|>240<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<1/2*100=50>> <<3/5*50=30>> <<50-30=20>><|endoftext|>20<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<40/2=20>> <<20/2=10>><|endoftext|>10<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<12*2=24>> <<4*1=4>> <<3*4=12>> <<24+4+12=40>> <<12+4+4=20>> <<40/20=2>><|endoftext|>2<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>',
 '<|endoftext|><<2*2.25=4.50>> <<2*4=8.00>> <<2*2.50=5.00>> <<4.50+8.00+.50+5.00+3.50+3.50=25.00>><|endoftext|>25<|endoftext|>',
 '<|endoftext|><<32=32>> <<8=8>><|endoftext|>25<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>']

In [ ]:
preds_cot

['', '', '', '', '', '', '', '', '', '']

In [ ]:
labels_cot

['', '', '', '', '', '', '', '', '', '']

In [ ]:
labels_ans

['', '', '', '', '', '', '', '', '', '']

In [ ]:
preds_ans

['', '', '', '', '', '', '', '', '', '']

In [ ]:
labels_text
[0].split('<|endoftext|>')

NameError: name 'labels_text' is not defined

In [ ]:
for p, l, m in zip(preds, collated['labels'], collated['labels_mask']):
    print(p[m], l[m])

KeyError: 'labels_mask'

In [ ]:
preds[0]

array([   11,   860,   860,   604,  1635,   657,   657,   767,   657,
         642,   642,   642,   642,   718,   352,  1343,   657,   657,
         718,   604,   860,   657,   357,   642,   642,   352,   352,
         352,   352,  1267,  1343,   657,   657,   642,   860,   657,
         767,   657,   357,   642,   642,   718,   657,   362,   807,
         657,  1267,  1343,   657,   657,   657,   657,   718,   604,
         860,   657,   220, 50256,  1303, 21017,   642,   642,   718,
         657,   807,   362,   657,   352,   220, 50256,  1303])

In [ ]:
pred_texts = tokenizer.batch_decode(preds, skip_special_tokens=False)
print(pred_texts)

[', 9 9 4 * 0 0 7 0 5 5 5 5 6 1 + 0 0 6 4 9 0 ( 5 5 1 1 1 1 ) + 0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 ) + 0 0 0 0 6 4 9 0 <|endoftext|> #### 5 5 6 0 8 2 0 1 <|endoftext|> #', ' the 0 1 6 0 1 0 8 3 6 6 7 1 1 3 + 0 4 8 7 0 2 ( 6 1 0 9 3 2 ) + 0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 ) + 0 0 0 2 7 3 6 3 <|endoftext|> #### 6 1 4 9 8 6 8 3 <|endoftext|> #', ' the 0 8 4 + 2 8 3 0 8 8 0 0 5 7 + 0 4 8 3 4 8 ( 8 4 8 8 1 9 ) + 0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 ) + 0 0 0 2 3 6 5 6 <|endoftext|> #### 8 4 4 8 8 4 7 6 <|endoftext|> #', ', 2 3 2\n 0 0 0 1 9 9 0 9 2 1 + 0 2 1 2 7 1 ( 9 2 0 5 8 1 ) + 0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 ) + 0 0 0 5 1 5 1 2 <|endoftext|> #### 9 2 8 1 8 2 4 2 <|endoftext|> #', ' the 1 - 0 0 0 1 3 2 0 0 4 6 8 5 + 0 0 5 6 6 3 ( 0 4 1 5 2 4 ) + 0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 ) + 0 0 0 0 5 6 6 3 <|endoftext|> #### 0 4 1 3 7 4 1 4 <|endoftext|> #', ', 4 5 1 0 8 2 8 1 2 2 5 2 4 2 + 0 9 8 1 8 1 ( 2 4 1 6 0 2 ) + 0 0 4 0 5 8 4 ( 2 4 5 6 5 0 5 ) + 0 0 0 1 4 4 2 4 <|endoftext|> #### 2 4 5 7 9 4 7 4 <|endoftext|> #', ' the 7 0 9\n 0 8 3 0 0 8 4 7 9 0 + 0 6 6 8 3 4 ( 8 0 4 8 4 4 ) + 0 0 4 7 8 4 0 ( 8 0 8 5 3 9 0 ) + 0 0 0 4 4 2 9 2 <|endoftext|> #### 8 0 8 9 7 1 0 3 <|endoftext|> #', ', 3 9 2 0 0 0 3 0 0 0 0 0 0 0 + 0 0 6 4 8 0 ( 0 0 6 4 8 0 ) + 0 0 2 9 6 1 0 ( 0 0 8 3 5 2 0 ) + 0 0 0 8 2 2 5 1 <|endoftext|> #### 0 0 8 1 8 4 5 1 <|endoftext|> #', ', 7 7 3average 1 0 0 2 5 5 5 5 2 2 + 0 6 6 0 7 2 ( 5 1 2 3 9 2 ) + 0 0 0 0 0 0 0 ( 5 1 2 3 9 2 0 ) + 0 0 0 5 5 5 2 2 <|endoftext|> #### 5 1 2 8 4 8 2 2 <|endoftext|> #', ', 5 9 1ACH 0 3 7 0 0 0 0 0 0 0 + 0 7 3 9 5 3 ( 0 7 3 9 5 3 ) + 0 0 9 7 9 1 1 ( 0 7 2 7 5 5 1 ) + 0 0 0 9 7 9 1 1 <|endoftext|> #### 0 7 2 6 3 5 3 1 <|endoftext|> #']

In [ ]:
labels_texts = tokenizer.batch_decode(collated['input_ids'], skip_special_tokens=False)
print(labels_texts)

[' 5 6 3 2 * 7 4 3 4 <|endoftext|> 5 5 5 6 1 + 0 0 6 4 9 0 ( 5 5 1 1 1 1 ) + 0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 ) + 0 0 0 0 6 4 9 0 <|endoftext|> #### 5 5 6 0 8 2 0 1 <|endoftext|>', ' 6 9 1 5 * 6 4 4 7 <|endoftext|> 6 7 1 1 3 + 0 4 8 7 0 2 ( 6 1 0 9 3 2 ) + 0 0 4 8 7 0 2 ( 6 1 4 7 1 3 2 ) + 0 0 0 2 7 3 6 3 <|endoftext|> #### 6 1 4 9 8 6 8 3 <|endoftext|>', ' 6 7 3 9 * 8 9 1 7 <|endoftext|> 8 0 0 5 7 + 0 4 8 3 4 8 ( 8 4 8 8 1 9 ) + 0 0 6 7 3 9 0 ( 8 4 4 6 5 8 1 ) + 0 0 0 2 3 6 5 6 <|endoftext|> #### 8 4 4 8 8 4 7 6 <|endoftext|>', ' 3 0 3 4 * 3 4 6 5 <|endoftext|> 9 0 9 2 1 + 0 2 1 2 7 1 ( 9 2 0 5 8 1 ) + 0 0 8 1 8 5 2 ( 9 2 8 6 6 7 2 ) + 0 0 0 5 1 5 1 2 <|endoftext|> #### 9 2 8 1 8 2 4 2 <|endoftext|>', ' 0 3 3 7 * 8 5 6 5 <|endoftext|> 0 4 6 8 5 + 0 0 5 6 6 3 ( 0 4 1 5 2 4 ) + 0 0 0 8 9 3 4 ( 0 4 1 3 2 8 4 ) + 0 0 0 0 5 6 6 3 <|endoftext|> #### 0 4 1 3 7 4 1 4 <|endoftext|>', ' 3 6 0 6 * 4 3 8 7 <|endoftext|> 2 5 2 4 2 + 0 9 8 1 8 1 ( 2 4 1 6 0 2 ) + 0 0 4 0 5 8 4 ( 2 4 5 6 5 0 5 ) + 0 0 0 1 4 4 2 4 <|endoftext|> #### 2 4 5 7 9 4 7 4 <|endoftext|>', ' 4 7 8 4 * 2 9 1 6 <|endoftext|> 8 4 7 9 0 + 0 6 6 8 3 4 ( 8 0 4 8 4 4 ) + 0 0 4 7 8 4 0 ( 8 0 8 5 3 9 0 ) + 0 0 0 4 4 2 9 2 <|endoftext|> #### 8 0 8 9 7 1 0 3 <|endoftext|>', ' 2 9 6 1 * 0 5 1 9 <|endoftext|> 0 0 0 0 0 + 0 0 6 4 8 0 ( 0 0 6 4 8 0 ) + 0 0 2 9 6 1 0 ( 0 0 8 3 5 2 0 ) + 0 0 0 8 2 2 5 1 <|endoftext|> #### 0 0 8 1 8 4 5 1 <|endoftext|>', ' 1 1 5 4 * 5 6 0 5 <|endoftext|> 5 5 5 2 2 + 0 6 6 0 7 2 ( 5 1 2 3 9 2 ) + 0 0 0 0 0 0 0 ( 5 1 2 3 9 2 0 ) + 0 0 0 5 5 5 2 2 <|endoftext|> #### 5 1 2 8 4 8 2 2 <|endoftext|>', ' 3 9 9 3 * 0 9 3 3 <|endoftext|> 0 0 0 0 0 + 0 7 3 9 5 3 ( 0 7 3 9 5 3 ) + 0 0 9 7 9 1 1 ( 0 7 2 7 5 5 1 ) + 0 0 0 9 7 9 1 1 <|endoftext|> #### 0 7 2 6 3 5 3 1 <|endoftext|>']

In [ ]:
collated['input_ids'].shape

torch.Size([10, 71])

In [ ]:
pred_texts[0]

', 9 9 4 * 0 0 7 0 5 5 5 5 6 1 + 0 0 6 4 9 0 ( 5 5 1 1 1 1 ) + 0 0 5 9 0 7 0 ( 5 5 6 0 2 8 0 ) + 0 0 0 0 6 4 9 0 <|endoftext|> #### 5 5 6 0 8 2 0 1 <|endoftext|> #'

In [ ]:
preds[0]

array([   11,   860,   860,   604,  1635,   657,   657,   767,   657,
         642,   642,   642,   642,   718,   352,  1343,   657,   657,
         718,   604,   860,   657,   357,   642,   642,   352,   352,
         352,   352,  1267,  1343,   657,   657,   642,   860,   657,
         767,   657,   357,   642,   642,   718,   657,   362,   807,
         657,  1267,  1343,   657,   657,   657,   657,   718,   604,
         860,   657,   220, 50256,  1303, 21017,   642,   642,   718,
         657,   807,   362,   657,   352,   220, 50256,  1303])

In [ ]:
collated['input_ids'][0]

torch.Size([71])

In [ ]:
for p, t in zip(preds[0], collated['input_ids'][0][1:]):
    # print(p, tokenizer.decode([p]), t, tokenizer.decode([t]))
    print(tokenizer.decode([p]), tokenizer.decode([t]))

,  6
 9  3
 9  2
 4  *
 *  7
 0  4
 0  3
 7  4
 0
 5 <|endoftext|>
 5  5
 5  5
 5  5
 6  6
 1  1
 +  +
 0  0
 0  0
 6  6
 4  4
 9  9
 0  0
 (  (
 5  5
 5  5
 1  1
 1  1
 1  1
 1  1
 )  )
 +  +
 0  0
 0  0
 5  5
 9  9
 0  0
 7  7
 0  0
 (  (
 5  5
 5  5
 6  6
 0  0
 2  2
 8  8
 0  0
 )  )
 +  +
 0  0
 0  0
 0  0
 0  0
 6  6
 4  4
 9  9
 0  0

<|endoftext|> <|endoftext|>
 #  #
### ###
 5  5
 5  5
 6  6
 0  0
 8  8
 2  2
 0  0
 1  1

<|endoftext|> <|endoftext|>